### PR TITLE
fix: Disable 'We expected `peer_id` to belong to a component' warning

### LINKED ISSUE #5563: We expected `peer_id` to belong to a component warnings
I started a new testnet rpc node recently and I saw the log is flooded with these warnings 

```
Dec 01 18:52:33.547  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.547  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere```

Not sure if they indicate any issues or just a benign warning. In the previous case, we should fix the issue. In the latter case, we should decrease the frequency of printing these warnings.

### PR DESCRIPTION
**Pull request by pmnoxx**
Let's disable`We expected peer_id to belong to a component` warning for now

Resolves #5563

Doc in https://github.com/near/nearcore/pull/5618

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
Do we have any test that tests the behavior of this part of the code? How do we make sure that the change here does not break anything?

**Comment by pmnoxx** [comment]
@bowenwang1996 I changed this PR  to only disable the warning.
I want to do further testing, before changing the logic of this function.

**Comment by bowenwang1996** [comment]
> @bowenwang1996 I changed this PR to remove both warnings. After analyzing the algorithm, I figured out that's it's normal for both of those warnings to happen.
> 
> I think the current logic is fine, but just needs a bit of explanation. I'll later add a documentation, to explain what's going on.

yeah that would be very helpful

**Comment by pmnoxx** [comment]
@bowenwang1996 Here is the explanation of the bug: https://github.com/near/nearcore/pull/5618

**Comment by bowenwang1996** [comment]
> @bowenwang1996 Here is the explanation of the bug: #5618

I think it is better to combine two PRs into one since they are about the same issue. It was more difficult for me to review them separately because in order to review one, I have to look at the other as well to understand the context

**Comment by pmnoxx** [comment]
@bowenwang1996 
My understanding was the main issue was excessive logging. I split it into two parts. This way we could have shipped a hotfix immediately to fix the TestNet nodes. It has already been 5 days, and the fix for logging has not been reviewed, nor merged. 

And, meanwhile, we could have worked on doing the documentation, refactoring, etc.

From each of those PR's I gave the link to the other one to make it clear what is going on. One change contains the fix to excessive logging.  Another, one adds documentation to the method.  In my option, both changes, make sense to be shipped independently. If there is anything, not clear, please let me know, I'm always happy to explain, either through discussion or a DM.

**Comment by pmnoxx** [comment]
> > @bowenwang1996 Here is the explanation of the bug: #5618
> 
> I think it is better to combine two PRs into one since they are about the same issue. It was more difficult for me to review them separately because in order to review one, I have to look at the other as well to understand the context

@bowenwang1996 If we combine those two PR's together. Should this be `fix:` indicating, that the PR is a bugfix, or marked as `doc:`. Saying that this PR is a documentation. Please, provide me a link to guidelines what to do in those cases.

**Comment by pmnoxx** [comment]
@bowenwang1996 I combined changes from both PRs into https://github.com/near/nearcore/pull/5618/files.
#5618 is now based on top of #5566

**Review by bowenwang1996 — APPROVED** [review]

**Pull request merged**
