### PR TITLE
snapshot: remove the error about missing snapshot on node startup

### PR DESCRIPTION
**Pull request by wacban**
you know what this is

### CODE REVIEW

**Comment by wacban** [comment]
please go ahead and merge if there are no comments

**Review by marcelo-gonzalez — APPROVED** [review]
yes +100

**Comment by marcelo-gonzalez** [comment]
although one thing maybe worth doing is to have this function tell whether the error is an actual serious problem, because right now we get an `anyhow::Error` whether it's just an expected case of a missing snapshot, or whether there's some actual problem opening an existing one

**Comment by wacban** [comment]
Forgive I'm going to be lazy and leave that for another time :) 

The log line does contain the error so it's still somewhat possible to tell what happened provided you know what error means what.

**Pull request merged**
