### PR TITLE
re: Stop using conditional imports in `near-network`

### PR DESCRIPTION
**Pull request by pmnoxx**
We should improve code quality by removing conditional imports.

There are a few issues with conditional imports:
-  high maintenance  cost - modifying code under conditional flags, requires manually adding #[cfg(feature=)] for each import. Rust plugin for Intellij doesn't support them well.
- readability - this makes code more readable, it's good to see what's being imported when to feature flags are used. 
- fragility CI - I've seen a lot cases, where I submit PR, only to find out, something didn't compile with some subset of features.

### CODE REVIEW

**Comment by pmnoxx** [comment]
@matklad What do you thing about it?

**Review by mm-near — APPROVED** [review]
I like it - but I'm also curious of what @matklad  thinks

**Review by matklad — APPROVED** [review]
As evidenced by the diff stat, much better!

One further improvement would be to pull `#[cfg(features = "delay_detoctor")]` into delay detector itself, such that we don't need to add cfg at every call-site: 

```rust
pub struct DelayDetector<'a> {
    repr: DelayDetectorRepr<'a>,
}

#[cfg(features = "performance_stats")]
struct DelayDetectorRepr<'a> {
    min_delay: Duration,
    msg: Cow<'a, str>,
    started: Instant,
    started_cpu_time: ProcessTime,
    snapshots: Vec<((String, String), Snapshot)>,
    last_snapshot: Option<(String, SnapshotInstant)>,
}

#[cfg(not(features = "performance_stats"))]
struct DelayDetectorRepr<'a> {
    ghost: PhantomData<&'a str>,
}
```

**Comment by pmnoxx** [comment]
> delay_detoctor

We could do that. However, right now `delay-detector` package is optional. Do we want to make that package mandatory?

**Comment by pmnoxx** [comment]
@matklad I we want to do it, here is the PR: https://github.com/near/nearcore/pull/6176

**Pull request merged**
