### PR TITLE
feat(o11y): Disable span events in logs by default

### PR DESCRIPTION
**Pull request by nikurt**
Provide a command-line flag to enable span events.
This reduces debug log volume by a factor of approximately x8.

### CODE REVIEW

**Comment by matklad** [comment]
Can we disable span events for stderr output, but retain them for data we send to the log aggregator?

**Comment by nagisa** [comment]
How is that useful? We send the spans properly to tempo, so if one is looking at an aggregator it isn’t that far away from being able to view spans properly.

**Review by nagisa — APPROVED** [review]
This seems good to me, approving, but should give matklad an opportunity to describe an use-case for sending the span events as logs to otel, if there is any.

**Comment by nikurt** [comment]
> Can we disable span events for stderr output, but retain them for data we send to the log aggregator?

There are three possible uses for the span events:
1) Log them to stderr
2) Ingest span-enter and span-close events into a logs aggregator, e.g. Grafana Loki
3) Ingest spans as tracing information, e.g. into Grafana Tempo

The flag controls both the first and the second use.
The third use case is independent. Tracing information always contains information about entering or exiting a span.

The second use case can possibly be a concern, but I think this PR is acceptable due to the following reasons:
A) We don't have any log aggregator (Grafana Loki or similar) configured
B) Span information in the logs is very hard to use. The same information in the form of tracing is a lot easier to consume. Measuring a delay between two related spans requires a lot of manual actions when using logs, and instant when using Grafana Tempo. See the attached screenshot for an example.

image

**Comment by nikurt** [comment]
cc: @marcelo-gonzalez

**Comment by matklad** [comment]
So the main thing I am worrying here is having span durations recorded *somewhere* by default, that feels like a very useful information to have.

**Comment by nikurt** [comment]
> So the main thing I am worrying here is having span durations recorded somewhere by default, that feels like a very useful information to have.

Span durations are useful in a context. They are useful when they can be compared to something.
If a span executes for 100ms is that too much or too little?
Given the amount of spans logged, and that they are without context, I believe it doesn't do much good to log them. Recording them in Grafana Tempo though is useful, because it makes outliers obvious and allows comparing span durations between nodes, which provides some context.
A case in which span durations are undoubtedly useful is replaying a certain block to investigate a performance issue. For this case a command-line flag is available: `neard --log_span_events view-state ...`

**Comment by nagisa** [comment]
I think this discussion makes it clear we need to figure out what we want our o11y to look like in the end. For every style of output we have, there should be a strong motivating case. Otherwise we will eventually end up with a third, fourth, and tenth largely-equivalent introspection mechanism. Lack of focus is never a great state to be in.

---

My personal opinion is that high-throughput logs are unusable in isolation. By their nature, they are difficult to scan, visualize, contextualize and interpret. More messages is a solution only to one of those issues. All that considered, targeting no more than ½ messages per second would actually make them logs objectively _better_.

What we do have is opentelemetry which elegantly deals with all of these problems, and more. Our integration of it is also quite advanced now. We should just require that any deployment includes the otel sidecar and necessary configuration to send all the collected data somewhere.

OTOH, if the desire is to make it operationally super straightforward to deploy the thing, then we should look into toning down our otel efforts and look into making logs _usable_ (which among other things would mean adding the missing context and introducing tooling that would solve problems solved by the grafana+otel stack.) Doing both feels like a waste of time and resources

**Comment by matklad** [comment]
Sorry, was OoO and dropped out of discussion. 

>Given the amount of spans logged, and that they are without context, I believe it doesn't do much good to log all of them to stderr by default. Recording them in Grafana Tempo though is useful

Yeah, that's exactly want I want: don't pollute stderr, but keep the info available somewhere. Spans record timing, so they can tell which stuff is slow. What makes spans particularly valuable is that they cast a wide net: if a slow operation is within dynamic extent of some span, it would be visible.

**Pull request merged**
