### PR TITLE
Fix: get branch on RELEASE event triggered workflow

### PR DESCRIPTION
**Pull request by andrei-near**
On release triggered workflow runs, the HEAD is detached and no local branch is present.
Due to this, BRANCH var ends up as an empty string and this causes failures to publish artifacts:
https://github.com/near/nearcore/actions/runs/7640475082/job/20815674136
++ git branch --show-current
+ BRANCH=
++ git rev-parse HEAD
+ COMMIT=c869dd6c1e942f21e27a74c7e47a698de
++ uname

this leads to incorrect S3 paths:
`s3://build.nearprotocol.com/nearcore/$(uname)/${BRANCH}/latest` -> `s3://build.nearprotocol.com/nearcore/Linux//latest`

### CODE REVIEW

**Review by Ekleog-NEAR — COMMENTED** [review]
Can we use `${{ github.event.release.tag_name || ’master’ }}` instead? This’d also remove the name for the `BRANCH` variable altogether

**Review by posvyatokum — APPROVED** [review]
Thanks! Can you rerun the workflow for 1.37.0-rc.1 after it is corrected?

**Comment by andrei-near** [comment]
> Thanks! Can you rerun the workflow for 1.37.0-rc.1 after it is corrected?

This would need to be merged into 1.37 branch as well. Only then the triggered WF would function correctly.

**Comment by andrei-near** [comment]
> Thanks! Can you rerun the workflow for 1.37.0-rc.1 after it is corrected?

Done this yesterday, binary is published and already released

**Comment by andrei-near** [comment]
> Can we use `${{ github.event.release.tag_name || ’master’ }}` instead? This’d also remove the name for the `BRANCH` variable altogether

we could in the workflow but still need to adjust the binary release bash script because context vars are not passed to it

**Pull request merged**
