### PR TITLE
pytest: add scripts/check_pytest.py checking if tests are listed

### PR DESCRIPTION
**Pull request by mina86**
On high level, this simply lists all `pytest/tests/**/*.py` files and
checks whether they are listed somewhere in `nightly/*.txt` files.
The end goal is to have this as a required check before a commit
is accepted so that no pytest’s are forgotten.

Currently though, there are 9 files which the script complains
about.  The output of the script is:

    Found 9 pytest files (i.e. Python files in pytest/tests directory)
    which are not included in any of the nightly/*.txt files:

     -  pytest/tests/adversarial/gc_rollback.py
     -  pytest/tests/sanity/concurrent_function_calls.py
     -  pytest/tests/sanity/proxy_example.py
     -  pytest/tests/sanity/restart.py
     -  pytest/tests/sanity/rpc_finality.py
     -  pytest/tests/sanity/rpc_tx_submission.py
     -  pytest/tests/sanity/state_migration.py
     -  pytest/tests/stress/network_stress.py
     -  pytest/tests/stress/saturate_routing_table.py

    Add the tests to one of the lists in nightly/*.txt files.  For example
    as:

        pytest sanity/rpc_tx_submission.py

    If the test is temporarily disabled, add it to one of the files with an
    appropriate TODO comment.  For example:

        # TODO(#1234): Enable the test again once <some condition>
        # pytest sanity/rpc_tx_submission.py

    Note that the TODO comment must reference a GitHub issue (i.e. must
    contain a #<number> string).

    If the file is not a test but a helper library, consider moving it out
    of the pytest/tests directory to pytest/lib or add it to HELPER_SCRIPTS
    list at the top of scripts/check_pytests.py file.

Before this check is incorporated in checks pipeline, the above needs
to be resolved.

Issue: https://github.com/near/nearcore/issues/2736

### CODE REVIEW

**Comment by bowenwang1996** [comment]
@mina86 we should certainly exclude scripts in `/stress/hundred_nodes` as they are used to orchestrate the mocknet nodes

**Comment by mina86** [comment]
Done.

**Review by bowenwang1996 — APPROVED** [review]
I think we should use just one txt file to avoid confusions. Otherwise looks good.

**Comment by mina86** [comment]
> I think we should use just one txt file to avoid confusions. Otherwise looks good.

While that may be true, I’d much rather deal with that separately along with adding all the nine files listed here. There’s 14 files which are in one of the `*.txt` files other than `complete_nayduck_set.txt`.

**Comment by bowenwang1996** [comment]
@chefsale @mhalambek looks like this PR requires approval from you

**Review by chefsale — APPROVED** [review]

**Pull request merged**
