### PR TITLE
chore: Update `primitive-types` to `0.10`, and remove old EVM dependencies

### PR DESCRIPTION
**Pull request by joshuajbouw**
On Aurora, some of our dependencies updated to the latest `ethereum-types` which is preventing us from progressing. This simply just updates this dependency. No issues or extra code is needed from what I could see.

This also removes unused `ethabi` or other `eth` related crates.

### CODE REVIEW

**Comment by frol** [comment]
@joshuajbouw Thanks for bringing it up!

> One question, what is the recommended way to resolve the `check bans`?

Review the duplicates and consider upgrading the other dependencies to arrive to a single version, otherwise, whitelist it in `deny.toml`

**Comment by joshuajbouw** [comment]
Hmm, looks to be like a nightmare to get everyone on the same page. Think this will be a fit for `deny.toml` @frol ?

**Comment by frol** [comment]
Yeah, that is fine. Also, you may consider patching 0.11 with 0.12 version if they are compatible for our usage. I used to do that: https://github.com/near/nearcore/pull/3869/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R73-R74

**Review by bowenwang1996 — APPROVED** [review]

**Comment by joshuajbouw** [comment]
Actually, I see a bit of cleanup that I can target with this and get what we wanted in.

**Comment by joshuajbouw** [comment]
@bowenwang1996 is there something wrong with the test suite currently? Pretty confused as to why it is failing where it is when that isn't an area that I had modified.

**Comment by joshuajbouw** [comment]
Ok, looks like it was re-run and was successful. This is ready then.

**Comment by frol** [comment]
@joshuajbouw CI still fails.

**Comment by joshuajbouw** [comment]
@frol thats funny. Was added into `master` branch as I was updating it. Anyways, lets see how this run goes.

**Comment by frol** [comment]
@joshuajbouw the PR name seems to be outdated :smile:

**Comment by joshuajbouw** [comment]
@frol Haha, sure. It's good to go.

**Review by frol — APPROVED** [review]

**Pull request merged**
