### PR TITLE
cleanup: Fix clippy::clone_on_copy and clippy::redundant_clone

### PR DESCRIPTION
**Pull request by akashin**
These seem to lead to reasonable readability improvements, so adding them.
Am I right that we'll ultimately need to add them to https://github.com/near/nearcore/blob/master/scripts/run_clippy.sh to prevent backsliding?

Commands to generate the fix:
```sh
cargo clippy --fix -- -A clippy::all -W clippy::useless_format -W clippy::clone_on_copy
cargo clippy --fix -- -A clippy::all -W clippy::useless_format -W clippy::redundant_clone
```

This is part of https://github.com/near/nearcore/issues/8145

### CODE REVIEW

**Comment by akhi3030** [comment]
> Am I right that we'll ultimately need to add them to https://github.com/near/nearcore/blob/master/scripts/run_clippy.sh to prevent backsliding?

Yes I am all for enabling additional lints as long as it helps improve the quality of the code and are not artificial annoyances that get in the way.  Given that nagisa is asked for reviewing this, I am sure they will have a good opinion on it.

**Comment by wacban** [comment]
The redundant clone one is awesome. 

Why not add it to the run_clippy in this PR?

**Review by nagisa — APPROVED** [review]
Please make sure these lints are denied in the CI (`run_clippy`)

The redundant_clone lint is awesome. I’m less sure about the `format!` one though – one might reach for `format!` almost naturally, and replacing instances of it with `to_string()` is a chore. On the other hand, using `format!` invokes the entire formatting machinery so its a tradeoff between convenience and performance. So while its fine to replace them occasionally, I probably wouldn’t -D the `format!` lint.

**Comment by nagisa** [comment]
To be clear, I think a global fix for `format!`, and the style rule are both in a good spot. Just saying that denying the lint in the CI is probably not something we want.

**Comment by akashin** [comment]
There were only 5 cases across the whole codebase where `format!` -> `to_string` replacement was needed, so seems like a minor change that I'll do anyone.

I haven't found a way to remote this particular check from the overall `redundant_clone` lint and given that it's already in our code style guidelines, I think we should enable it despite the minor annoyance. If this introduces too much hassle, we can review this again in the future.

**Review by nagisa — APPROVED** [review]

**Comment by akashin** [comment]
To sum up, I've applied both `clippy::clone_on_copy` and `clippy::redundant_clone` to the whole codebase and added them to the list of enforced lints. It touches a lot of files, but I think it's a readability and consistency win across all of them.

**Pull request merged**
