### PR TITLE
Fix(storage): some outcomes are corrupted due to an enum variant dropped

### PR DESCRIPTION
**Pull request by ailisp**
Fix https://github.com/near/nearcore/issues/4624 and https://github.com/near/nearcore/issues/4628. The bug seems to be  introduced in 6c3c2f7475a5e8c258a39ed94f11f6a8a7b2108e that `MethodUTF8Error` variant is dropped without a migration. I figured out the issue by deserialize field one-by-one. The specific error case does not happen on mainnet archive node to be caught. Note, two enum variants after MethodUTF8Error can be wrong too, but i don't have a good way to fix them unless reapply all blocks again, but even doing that still don't fix non-canonical blocks and very slow. So I decide to accept these off-1 outcomes. The harm is small: some MethodNotFound would be misclassified as MethodInvalidSignature

Test Plan
---------
Download testnet archive node state, run node, finish all migration and node doesn't crash. 
Test on mainnet archive node backup again it still works

### CODE REVIEW

**Comment by ailisp** [comment]
@khorolets This are problematic outcomes that changed in migration testnet archive node, please re-fetch and update them in indexer side:
```
! Byte Changed. Check outcome id, block hash for indexer: ZnD2ydFaa8ePVmUv7jMvTtjt3ghWwYTZsFpW8zbYEjb,Eo3EgA7fxxNFT6roPVLuGxjjyks3kXifdR6zyrfuELkP
! Byte Changed. Check outcome id, block hash for indexer: 2VVrqYgB6rJpXBKH7rAb4aRaiubBkvCUP2SnBoPAX2jx,2taKcQuwEfg6KbNY5xjheYXqN1WVn2mhRPFinhJrpfMA
! Byte Changed. Check outcome id, block hash for indexer: 2jwJaThYcdg3zoD99VDGwG8TSQqMH3EDL7FeD9ToLBCs,8TqikgeCtZKK8AkFsJG8kNpT6WdMt7HeSuZk4PBXvLNJ
! Byte Changed. Check outcome id, block hash for indexer: 2qE5qj6reiGuBM1rXnvFqUYLpAETeXJQBko1fswE6nYf,NsTA3oxWYghDzVnjSZja1YmNqMCYad1hNyrk5dF7E97
! Byte Changed. Check outcome id, block hash for indexer: 2zP2oREULxLy9u2yykhaYL3Jmf9yw3RB3A74gTy8Hv26,8zumPpj1d4LQ9uDMSxMxumE9NuvnkJYoTUMA6iSyYX2
! Byte Changed. Check outcome id, block hash for indexer: 2zm87BBse673DyhrLVQ8KByUBnVAnFmwA18MgmwBAuda,4AxZF4UYsjpoHP1opVqhTt1X73gPPLS8ESSSUfpaCzR3
! Byte Changed. Check outcome id, block hash for indexer: 3XTSG9NcQ5UmpqnC3WK3V7pkFgjrifSrao7Cc9T8S34T,4p12sSCs7MLPbS5LudxG8UEY87JiHHNHBYBpcFDeJnay
! Byte Changed. Check outcome id, block hash for indexer: 3hiDoRnsbd89JfT3LYT4ZGYEK7zHrMs5JHKJ8gxtXgDA,nfvdzSbhJJ5FFp1xscuJK2odoWZeKtfiigAPbYZ5d9A
! Byte Changed. Check outcome id, block hash for indexer: 3jagALPm8gvcmCHuJgfSpxQb1UmBry8QmzTSE23dsB7z,JCbNKsZcB9e2iyjmN9Yy68Jd3pN5rmQBdD5ARmiSQ2gJ
! Byte Changed. Check outcome id, block hash for indexer: 43Zs4cnh87wEnDsWYfAncayvvV1Xozg15WiSvawNgWuA,eRdYRQ6fDbs5BcPe7wVVWnALqczJEZ4kfPhkEDur6PZ
! Byte Changed. Check outcome id, block hash for indexer: 4TyqJu2v9dvD92qJrZavQBcJBczbForfazuvzmHE4h4q,55Stpaac8MowZ23PvcpJVVmKrKBChjizcBzWwoQeoPoY
! Byte Changed. Check outcome id, block hash for indexer: 4UQsTdqWjF4rpXLmXKtS5dxue7NPACHxMMeGcb74A9WU,E75a2PtNtAkjZ18J1UrZzd6GQaWD4ay71nkGg4HPbLUB
! Byte Changed. Check outcome id, block hash for indexer: 4YGKhbPoV63CG9GbEa6DKAJBvRUWp3ZAxoFYZDXbZ1v2,A6m5wGrK8A12yZtMrdtZdmN6yuSoL7p4JWSCrqKDqZXV
! Byte Changed. Check outcome id, block hash for indexer: 4ejiPq69uc2J1tsFM542iyHtsgZcPYmHU6hznZvy63e6,6WkmsR4rtWT64u8ChGhVpAgc4XxpFcEXzBcYNnMfz8F8
! Byte Changed. Check outcome id, block hash for indexer: 4zgjuWaijjLbk9FP9CjsgvMhZS9wuZ7qQcukr3eiSjCv,4g46k4HP6AsirSjNSA4o38HxNyLZjjx2qnmnwutU3Ay7
! Byte Changed. Check outcome id, block hash for indexer: 5QX6hZ8iDUxipfFryQGEBkmuZf9nt1PK439h7uTvcCjP,988EN9PtSnjsJRfiMcnW9EoGaeTbAMLgzHm8vmPGLX5g
! Byte Changed. Check outcome id, block hash for indexer: 5U5Aj7gjzmhjTVJMvnxmPD7s2B5gZqU3F49o9dsZNK4r,9R4oVdUsY8iURNyWjjVDNXAQrozuYuN8v7NQeaifpW8i
! Byte Changed. Check outcome id, block hash for indexer: 5UdDpZwJgn8KiaYZHRUH9NmYuhDSCEtDDCJzaVYFQFyS,65bzj1wkphdH24aW2V2Z7FrSGCX1utXBbaiD6FbJZFc4
! Byte Changed. Check outcome id, block hash for indexer: 5VoBKUiXMqYQhb3X8ejxGifwcbb1rciSDjxis2CQUmPY,GbcYBwRcnXpc4qiLAyDsXRKagxaZmNRyjbpYUL2QnN9P
! Byte Changed. Check outcome id, block hash for indexer: 5XyM18AzkHtyHizDZ2vDVQkeXZAjuaLHDBah5KRAh5YJ,3GrfLANadraEh9LAujMmWai5aEUZxhk3g1J1Laa9ZPeM
! Byte Changed. Check outcome id, block hash for indexer: 5kyCzxWYZL4xqKrwHwqQybaXq8UFPafDX48igfScopYw,BRbjEv15DqqmSMNp5NfmfPHVZjpiKBHrXJxuavfrHbmZ
! Byte Changed. Check outcome id, block hash for indexer: 61nJYxJsDKXxSAFcATSdvuJF1nHgTevs1QsNZbDrZfVf,GQqkC8RkBBYu4mXxy2edtUZZewUbWzZ1qm9gX9TdyyCW
! Byte Changed. Check outcome id, block hash for indexer: 657Kf7e6QaeNYi1koGQaRfxXCdBuUBBzBBXThoJYRJQm,GMGnFFYnjcbBYPdtmQxawHiJ2YQqmGFir7yjbXN3Ez4i
! Byte Changed. Check outcome id, block hash for indexer: 6YSwcKymAks57G25ZD3f1foNMT8gutThShWMRCVCyUMb,BxmkTWs1pCL2NN7qJfHHtX57ZVK3oMtdwCrrXQsmXdmm
! Byte Changed. Check outcome id, block hash for indexer: 6YXJAQtmAmQbBuw5kYDDgPSjmQPgjx14VLNXBn4SZ24E,5i3VmjdHtVbD7Y6a13pLX2yhnTHVDjbvTywBqxWuG1Wf
! Byte Changed. Check outcome id, block hash for indexer: 6aEn5sWxEkNLyfuDtpNnQhTRSpxZ8ZmvfAjGNmujw7xv,8mTFpurQw1kJxTnTN2z4aPbKsU2tFB9CpVt6dP9YeDhn
! Byte Changed. Check outcome id, block hash for indexer: 6agkXdLZdRZtZJB234tjhY5wHr53C7pHyvJAXwmobAWJ,CUz6k3Uyv3LShGriJv2G8HfqdHNNQ9uu6hSrQJfpm8bi
! Byte Changed. Check outcome id, block hash for indexer: 6xhjbqpefMUx45fgxkdQUvY712eLTx9DMMUhx9G7b5oB,2dmfGrHPKEDAKuqWExnBncBgMK8xaBvxBcaLfRTzBerP
! Byte Changed. Check outcome id, block hash for indexer: 74pFCGvne34S8bhbfiV9avEvuzSrWy8N8vWi2mcrfizp,CKa39Sd1vwCunWLDNpjGH2tidyi1RGr6xmbBfQVruGif
! Byte Changed. Check outcome id, block hash for indexer: 7AUJurM15hZiskV98XjythuL9WN5orFjU5a2UiaSP74F,3EKbiTqWrQwTV6m52zrBVSachGCQsPtRZQY9JN8UuzFo
! Byte Changed. Check outcome id, block hash for indexer: 7NUdFgxE66nHB4TYC5sKvK3Ft8VHZ5NM12nFfW5ZdWpV,9GmiJPx4KeeAUeZssJJmXKYYnwVnkf2VbdndZ4M5AmKT
! Byte Changed. Check outcome id, block hash for indexer: 7QiVRb3ym5iXa7qV3aEpwV4tcXCg9eVarrJRPgeGXeC7,EgBvcphuiyQc5JApoNkduCw6ERZLGKs5gN9f3TS5FBJx
! Byte Changed. Check outcome id, block hash for indexer: 7R4SKLT8EY31fjoupCWLPqRHVjBF5etWX8rsbFXYKgH7,EZbF1jPopLNNpSrGVKbK4kBeJGkSiek5GC1tporu2JZ9
! Byte Changed. Check outcome id, block hash for indexer: 7T95gCwpgWhDXGh1uCgjgzNyd4bT2Pwa68DYCmkizkFN,2pJci8iebCpRdsRvmz37P7bSGeZF9cVqxqfVM9Prpwi1
! Byte Changed. Check outcome id, block hash for indexer: 7o9BjtAfSjZ5MdAF8n2JhFLDG9upRV2YP88urY55VXC3,4z2gXLutyvxM1G1pHyHqngZzyC6ZT53hu4Ko3adfwgLC
! Byte Changed. Check outcome id, block hash for indexer: 819nniy1Gyoad4i1ozYyndUSKnfU2dVT7jGSb783NAuA,HX95ESecijNq8aoKAjFHA1rpMZW3gUz2jKBHsedzxyA6
! Byte Changed. Check outcome id, block hash for indexer: 88Ku2JzBJEx7AnhKyzmHVNSuUHqBpuRYvJE55Txa7ENt,J8SCcDM2utwUzudArkMUKDJ8z5GETq4Squbx8G6RhVVk
! Byte Changed. Check outcome id, block hash for indexer: 8CiHx1vPRTaddLPZvCQ3CFjsukwdJpWUhzjKWCwQf1S3,89RiSY4wMxkrAkGYp2teZFLhTFJKHXPaFur1BbvaEw6f
! Byte Changed. Check outcome id, block hash for indexer: 8Pmxbk7dtTT7AQ5nv8dKcFwpHejL3SASq4ELQkhZea1T,9tNUPuAWxNkXrZu4bQUXpvcaTqNjfQLNhZs9pRgZcdmZ
! Byte Changed. Check outcome id, block hash for indexer: 8xcdeURuPkL29P6AHVcCBtDWJdiYYeMPEJpJkNYYYNhY,4gLHrEnRb9moGqX8QQDtCyjMsuDmyVLCiQJyPD5s4g5d
! Byte Changed. Check outcome id, block hash for indexer: 93Sw28tPhwAiHg33ADQwVA5HyHsC6Knc26KMd4xujnMU,5YyBLQhaydjZ4XFwLiqMFWmEWLFE8eL8r6hGs5Gb9Q6h
! Byte Changed. Check outcome id, block hash for indexer: 9DDh4QYakzD2N1oa9rzTzGVVZZFBcqbXcVt2Ez7pjkuy,5davpDxwKFPLmz3hTQcUhZUx3BaPgXHY8yHfQVuzNwkn
! Byte Changed. Check outcome id, block hash for indexer: 9LK2RiaMMrUTWoo3pMco19tQvWjQYG2gZewpoJ7jokEt,W23TWCeVCzzXmE7Ebo1GoSUMM8PDAJFPtjQMCYg5eft
! Byte Changed. Check outcome id, block hash for indexer: 9N4KCBASQYZaDn62Tf4MMuLZqkV4rhrzTo6X3gaq3iW6,Ey5CVdybVN6exujQAFiLnnLoqJfSW5xUdCZVQHxoPMQt
! Byte Changed. Check outcome id, block hash for indexer: 9jRCRWTqPzNxehKaTtkiUVxxYjQwGFzXoyUUyHMZrBGB,9GC46PcvUU2cQkSymrQY9BewEr7RkMzGQ4fFMxuMaF3j
! Byte Changed. Check outcome id, block hash for indexer: 9mKbzZu2YzCKAErFTVMFE9UWWHir8zj6zs8dhyzNKMK4,9hP8vbBhxrZizBcQJNqDskNeQ1wyx3zATc2rhPp27Hon
! Byte Changed. Check outcome id, block hash for indexer: 9xjz1LYfruF9gpB6MagVDSo2dBQfANFNHC2TWkG2MiK3,7GxaM2qbhz36c9vBUKe2G7q7TC74usVjdEYA4nz2UsJm
! Byte Changed. Check outcome id, block hash for indexer: A1w4LKatbJZNJcM6PcmZqZ3wc7eVw6tGAtTiB81dGhJd,ECVqdj7K52qpmPSVMbfnSGkh9w1JPGnNeWaGb87YEzWy
! Byte Changed. Check outcome id, block hash for indexer: A5ggDVnZ5fffdjjBnZPUrJqs5PCUDqx4r6EYDU6CWrgv,8HmMVsGBfG2fRjFcLERmoQCLThvUcvTRwxdsjfAwWdda
! Byte Changed. Check outcome id, block hash for indexer: A6XacgoCz2TsS4U2SjEKVH3x6uGLC6fdY6TRwQ6GV8eQ,88TSj1Kdxc3AR1vn6LBG9Uyoo1L9ayEmbXzM59jsKiio
! Byte Changed. Check outcome id, block hash for indexer: A9KUWbZV6DCJt1rEy5pUZpU2QJ4tfQRmVakfktY4vwU6,DJxnCDN738qVLyy5SSLYuhpHPdV7BaWaEzjfxWpAo8Wb
! Byte Changed. Check outcome id, block hash for indexer: ARVWj2h9LRntkPSWhTaQyDvuoUPs4MMpNnuTTd19VDUP,FXooWReEkmtXWUNTL7Ph6U8dfgTQP9nJJgPDU7F65nyp
! Byte Changed. Check outcome id, block hash for indexer: AZJ5TLNuobbqjuY2Cd6YxGb6AUiXRWPT6XWeTsYDnQ4V,5Gp8QYahL5x4bp1kx7kzYnn4pYNyE3od23oRTr7kDC6p
! Byte Changed. Check outcome id, block hash for indexer: AdM2HpEuja1GJqsHaJkQyjdEAsNZxgtMGfnkymDMM6Fc,4kiH8bWS2RLuuxYJ2w5uXrMTLueK2SocTkpMdSiaTVMC
! Byte Changed. Check outcome id, block hash for indexer: AfUM3KBHJefekZfV1aGZWvEbSjuYAPyweWjvz1KBnNNh,4Hbm91znxhJo2ixRDHd5x8ivgWXo5tUatUJAoW917xMf
! Byte Changed. Check outcome id, block hash for indexer: AxSLXbwRLt7aZKTw5CBNzGmnsffoM6iwZJRMmVKjKigc,4B2QZjnpbMoGes1bLGYiy7QxiXvAiG4K7BCVNnTEEycW
! Byte Changed. Check outcome id, block hash for indexer: BRHCFkFUWcher3qnxWKMYaNydH3AL58egwzJAeMjYNVC,BhjRKB7DENg38FNLTEZZjZo8v3cbvb9qA9Tz3S5TeudR
! Byte Changed. Check outcome id, block hash for indexer: BTDcuMMU4ifDtCUVWvjshQDUPiwFNqTrKiyKTkBbXD6r,Et9mxrib9yF1Ma4tfE1BgLGEX7dgKitGVJy3vwyZNfDs
! Byte Changed. Check outcome id, block hash for indexer: BVH6Hk77BWM63mXoKiqPcsozwZYdMS3jchZ7PybswbTG,Bac7uvfiQSKyXPpSo5vWfpBNVNZz11zQ6pW4FDwE9Vh1
! Byte Changed. Check outcome id, block hash for indexer: BeFwTMJS1bAm7rSBsp9ATqjyBomivicV5BpcjaLWqHxi,TXhgrjw3ruZY1N734kip2gSz5y2xLx2oVBXNyvC84xf
! Byte Changed. Check outcome id, block hash for indexer: BytoeJPCFXbb65hfmGGp33sumX5HgTumgFGneoHdWA2b,AJsfibF4Wt6V7utvUhp8m3GbUzbmhrvfft4wvMS9UHmu
! Byte Changed. Check outcome id, block hash for indexer: C4Fax2RBNJm357GABNgNATm4gx2hkB4mP7vGkqy36tNw,Dv31ayvmztH73o5oHgGnjqkxNb8LqgxKLR46HZ8eBA4k
! Byte Changed. Check outcome id, block hash for indexer: CKwRRodcRuNWWUoK9dyKvaN7Tc99hrqQ2dXMdijHj2VV,CJ9K6miHzKEcuAZZ6qnrQRUKa5WU2oSDwxSNH3N29Zir
! Byte Changed. Check outcome id, block hash for indexer: CRJFWCTxnBYMF6waYkuN4zRobmBw7zpyDzp2YKLe5Mu3,4T4PS1aFrhAPCEc5mY9rVutKsxHhiwq3tBb7apuLkmvH
! Byte Changed. Check outcome id, block hash for indexer: DNqGZvoTtShaqUKXpvNoMQV9akQWAFN9CazmirLKQEKe,FScG52r77tercrtxf1MdPtiN9CZF9Tiy77qwHRaBhtfw
! Byte Changed. Check outcome id, block hash for indexer: DP1UXCMLeJLgiYDLm4TTVv1qu8fEvdM6KFrAPdD2bMEX,2qq7EM3ihsdJBBqM67QYpg9KGDrCx4Pt9fRTXDhQPiBP
! Byte Changed. Check outcome id, block hash for indexer: DUZUDYEiFf1w1jekQ81RCCHWbCFuEEuJnSCm3BY3hS5H,GNKAqAgskpdApdyzBEE7u6znG4AEcYhK8cfvPeBo1up2
! Byte Changed. Check outcome id, block hash for indexer: DtG9MWHaJpVGnvhAMwDEpsbEodSW8kRKNmjTwq5AdTGx,GHTNNQ89LfXPs1v3Smn4qWWkuAserEcHxvRa8y7t43eG
! Byte Changed. Check outcome id, block hash for indexer: EK7bWDWds5zuySVsKT4Bgqsh71Ctq4Ysy3kpKCLLuAUv,B6AuMYYg9WyUH6d8zMhNb48Q276HF6KqceXtTCjXFaLD
! Byte Changed. Check outcome id, block hash for indexer: Ebev34WDpoaDa1vVBrtqMyyknZZnJ4hc5TvRPBB8zvEZ,99m9eAYmry6Hjt45QYAYrqYxDs44ZNrzz6rcdTPFJFT8
! Byte Changed. Check outcome id, block hash for indexer: EbuYRzduWZ8UziU5mt5L1UVpUrX9gaaZeQqqqEnNALaV,GsXWTguZTNLnk7c6iGtT6UoSUmrTrNatMAgGJTwykTwU
! Byte Changed. Check outcome id, block hash for indexer: FEibbPFQpcFLu9cyqgVZ94aDJXxjoKUutpAqQe3oMdVQ,GDoQ4vybvaBuj9YBE7KfrH2Bu3zYtupkUvMP3VS2HyVu
! Byte Changed. Check outcome id, block hash for indexer: FNtyNpov2z5tDbJfNb44bx1JazbjEVsekrqehbkFbV76,J5u964okuwDrq41dcBUexYoMt7Up213phUmCZPL2pjQQ
! Byte Changed. Check outcome id, block hash for indexer: FWdPycKqvdp8hDdbdfFUu4xv5XJjygKSf43d3GRYYAEL,3mibBDfmVUh2YE9bS3wfTdnKFrmXGbQZGCfy8R31DsW5
! Byte Changed. Check outcome id, block hash for indexer: FZQuoimYXGjVzD1TB3HRJFyidM3ppeZj2jjQxQEfCiLZ,9U7wTMphJ3MepYQDoR9rByN2EStUM7bHQSYt8nvG5Ea3
! Byte Changed. Check outcome id, block hash for indexer: Fj3s5MBoVzEkjEAcdZjfVzjcbzamwfkZCfqLkah9xKs7,3jFPnyZBBWuKpUXMEGH79d8DruLSKdze4p6bfrEhC6oc
! Byte Changed. Check outcome id, block hash for indexer: G4sa6CEKUqexbTBhXac2FYq4RbNX28Qj57MCxYdeWYqF,EYnMDCWubXzDkPBaCehAkmcbeMEDgHKrWKG9jbfTJ8CU
! Byte Changed. Check outcome id, block hash for indexer: GEPgUK5xbdyft4mQoorjsF6MHd6qjc6zPcRpvSwUqX6f,HJv3AEfETF9StpsBgGQaTBfmE7jbEvdesNstFkGMfqJW
! Byte Changed. Check outcome id, block hash for indexer: GgoB1E2ad7Uw37jC5G4NqLa6Vt4mpQUjp27ug9HxV79L,BqvbsiPWPsFqutKFoZKAAJfYSt8jF4xAZdj2mc3rsYVy
! Byte Changed. Check outcome id, block hash for indexer: Gk7hqGvkq66NZ7Zije89r5usGeSy2mTvcV53SMKQgTKS,ETmQCcWL6jAWu2jeSsBTLySRrT9b4dByhc6XPF1DhCBx
! Byte Changed. Check outcome id, block hash for indexer: GxnMzJ4NWexCSkLFMHWLFdgfrCCvE4YEav96KM5uhwJj,7tGG3THtzqz7Eazij4LzV5BDgwsGb6rDaFp3zQ1HhRr9
! Byte Changed. Check outcome id, block hash for indexer: H3JjFfvSfafWT6q1iWkDRH1P4qcMvfJNPCeKzADpi96W,8i76tRXTU5zF4c5KMs5A3Ej56zgCt5t828JcVEyA3fxp
! Byte Changed. Check outcome id, block hash for indexer: HLdswcsjJbHivQMmB4JSQ72JFNWAvCJTU8gK4LivXdrB,GqUsZ2rdgjUFZAa9ebZYxuGVWspRwAiqAbsE4VvBzBUo
! Byte Changed. Check outcome id, block hash for indexer: HkMkymcnCngFc2Mhj3xnDhV7YZvyVSY1zKZ5PGaYBaHT,FFeSYaa8dMZnG4oigzv5RXbyxhw5VDTvQj1z36Dcyj8m
! Byte Changed. Check outcome id, block hash for indexer: HkYpTAftiegQsmGRJ3z8hce1tuUrbdzSBBQJAnfLUggn,GgtPkhV2Arj83bRxbJYcX3SwQWQEccp9RbWajy749jbj
! Byte Changed. Check outcome id, block hash for indexer: HqKNqUuzoc6Kk6qofJeZvw3ZVLbyGugvTVh5SiKgskZD,7yQwohAaBFkGNnpukoAZTj4suikcPt2gUwHMEzK6BsP
! Byte Changed. Check outcome id, block hash for indexer: J2CkPAxJQuEZbqY4JiLzmsYKGja5GRTQm1Fgyusjm9GZ,EJ4Y6L6nVbedCUfjit6B2Z7R1g3qSAPmkzzFb9nABHru
! Byte Changed. Check outcome id, block hash for indexer: J4pCyHMRXTtw68Dgyb3u4jpZzt6isEhk7yrDSJC9eXn8,9bJW4eYnQHFXDbTUwFkPJnEXTdssAAj3TLyttKRnFcta
```

**Comment by ailisp** [comment]
@frol There's a few other way to fix but any of them is imperfect. Another quick fix would be just add the variant back as `_Unused_BadUTF8Error`. It also suffers from mis-classification problem. Another thorough fix is drop outcome column and reapply all blocks but quite slow to fix, could hit into other corner cases, and lost outcomes from non-canonical blocks. So by comparing the disadvantages I feel fix the migration is better. 

Also note, there're three kinds of outcomes:
1) deseralizable and correct
2) deserializable but wrong (off-one variant)
3) not deserializable (off-one variant that overflow)
Type 3 is junk since it's not deserializable, without the fix we cannot do anything with it. This fix turn type 3 into type 1 while ignore type 2 by only attempt to fix on non deserializable outcomes. It does not break anything good and fix some very bad records that are blocking.

**Review by bowenwang1996 — APPROVED** [review]
> @bowenwang1996 ouch! How do we deal with this? I don't feel that this migration is the right place for the fix, and I am not sure if this is the best way to handle it.

Given that this does not happen on mainnet, I think the fix is fine. @ailisp could you add a comment in the fix on why we need to manually check the bytes and add a link to the PR that dropped `MethodUTF8Error`

**Comment by frol** [comment]
Thanks for all the clarifications!

**Comment by frol** [comment]
@ailisp @bowenwang1996 I am trying to understand how this misclassification can hurt us. Correct me if I am wrong, but I feel that due to this misclassification we cannot really reapply transactions from genesis without hitting a fork since the outcome will have a different hash. I believe the misclassification is still present on mainnet and we just did not hit `MethodInvalidSignature` variant, while `MethodNotFound` can be encoded as 2 or 1 (before and after 6c3c2f7). Do I miss something?

**Comment by matklad** [comment]
Ouch, sorry for introducing that error, in #4007 I wasn't yet aware that enum variant order is significant for many things in nearcore.

>a fork since the outcome will have a different hash

My current understanding is that isn't the case -- only `PartialExecutionOutcome` affects the hashes, and that doesn't detail the error (just stores the fact that an error occured). 

Still, I agree that this leaves some misclassifications in, and that's unfortunate -- when we do look for a full error of a transaction, it's better if  we get the correct one. Am I correct that 6c3c2f7 already hit the main net? If that's the case, I think that the best solution is probably this PR: messing the specific variant of `MethodResolveError` is probably not a big deal. If the code didn't hit the main net, one alternative we can do is adding an explicit `Unused` enum variant, to preserve error code. 

I am also surprised that the bug wasn't caught in tests. I suggest adding some smoke binary compatibility tests, a-la

https://github.com/near/nearcore/pull/4312/files#diff-c0cb71be9c57de08ac1ac5752b7af7a55f7ff6226435f786d8199baecc0bb4f4R1785

**Comment by bowenwang1996** [comment]
> but I feel that due to this misclassification we cannot really reapply transactions from genesis without hitting a fork since the outcome will have a different hash

As @matklad pointed out the exact error variant is not merklized

**Comment by ailisp** [comment]
@frol 
> believe the misclassification is still present on mainnet and we just did not hit MethodInvalidSignature variant, while MethodNotFound can be encoded as 2 or 1 (before and after 6c3c2f7)

Yes as 6c3c2f7 land on mainnet this should be the case. Although the fact is surprising that no one hit MethodInvalidSignature on mainnet. Is that people have test their contracts well on testnet?

@matklad I think it's not your fault, more like a team mistake that we didn't catch the incompatible in PR review.

>  Am I correct that 6c3c2f7 already hit the main net? If that's the case, I think that the best solution is probably this PR: messing the specific variant of MethodResolveError is probably not a big deal. If the code didn't hit the main net, one alternative we can do is adding an explicit Unused enum variant, to preserve error code.

Yes. https://rpc.mainnet.near.org/status indicates it hit mainnet, so we cannot add a Unused variant back.

> I am also surprised that the bug wasn't caught in tests. I suggest adding some smoke binary compatibility tests, a-la

Good idea. I did some thinking on this and think that a high coverage backward compatible test is hard. Like this one it can be caught only if: send some txn hit exactly the last enum variant error case, write to database by the old binary, and request result through rpc of the new binary.

**Pull request merged**
