### PR TITLE
publish near-vm crates

### PR DESCRIPTION
**Pull request by Ekleog-NEAR**
This is needed for https://github.com/near/nearcore/pull/8782 to go well with the changes incoming with landing near-vm.

I have literally no idea how to test this, so I tried copying the way of doing things of #8782 and hope it’s right.

### CODE REVIEW

**Review by khorolets — APPROVED** [review]
> I have literally no idea how to test this
Appreciate you're being honest on that :)

P.S. I am pretty sure my PR does it right (it managed to do it right, just failed with one not-necessary-to-publish crate among others that made it)

**Comment by Ekleog-NEAR** [comment]
Great! I’m re-requesting a review because, as near-vm is a fork of wasmer, we unfortunately can’t change the license without at least involving legal and it’s probably not worth it; so I’m sending in a change relaxing our sanity-checker in order to gets CI to pass.

Should we land this now, or wait and land it after a decision is made for #8782? (right now near-vm-runner does not depend on near-vm yet so there’s no ordering, but it’ll probably come during next week as I’m making good progress on that front, so even if we wait we’ll still have to land it just before #8782)

**Review by jakmeier — APPROVED** [review]
I think we can land this now and we should probably also not get hung up on #8782 either.

One question for this PR, though: Considering that all readmes will be displayed on crates.io, would it make sense to update all the readmes we inherited from wasmer?
Maybe just add a one-liner on top of each like "hey, this is the NEAR fork of wasmer, the description below is copied from source and probably inaccurate"?

Long-term (not for this PR) it would be great if we can describe all near-specific details and what we changed compared to the fork. I vaguely remember a discussion around this type of documentation but IIRC we haven't done anything on that front, right?

**Comment by Ekleog-NEAR** [comment]
👍 I’ve opened https://github.com/near/nearcore/issues/8872 and linked it from https://github.com/near/nearcore/issues/8203 so we don’t lose track of fixing the near-vm documentation as a whole :)

**Pull request merged**
