### PR TITLE
refactor: combine part_id+num_parts into PartId struct #5731

### PR DESCRIPTION
**Pull request by kakoc**
Basically this is just an updated version of https://github.com/near/nearcore/pull/5731 which is not updated for several months.

### CODE REVIEW

**Comment by mm-near** [comment]
Thanks @kakoc 

@jc-near - can you be the first reviewer?

**Review by jc-near — APPROVED** [review]
Looks great. Everything makes sense.

**Comment by jc-near** [comment]
@mm-near  Sure!

**Review by mm-near — APPROVED** [review]
Thank you.

**Review by matklad — APPROVED** [review]
:heart:

**Review by mzhangmzz — APPROVED** [review]

**Pull request merged**
