### PR TITLE
feat: debug param estimator in docker via interactive bash

### PR DESCRIPTION
**Pull request by matklad**
Test Plan
---------

Manually check that it works

### CODE REVIEW

**Review by olonho — APPROVED** [review]

**Comment by matklad** [comment]
@chefsale what's the right way to re-try the merge if the failure is spurious (some network error while fetching some git repo)?

**Comment by chefsale** [comment]
@matklad I retried it, it should be fine.

**Review by chefsale — APPROVED** [review]

**Comment by matklad** [comment]
test failure seems unrelated

```


[2021-10-06T12:03:01Z] ---- sharding_upgrade::test_shard_layout_upgrade_simple stdout ----
--
  | [2021-10-06T12:03:01Z] thread 'sharding_upgrade::test_shard_layout_upgrade_simple' panicked at 'assertion failed: execution_outcome.status.as_success().is_some()', integration-tests/tests/client/sharding_upgrade.rs:220:17

```

cc @mzhangmzz

**Comment by matklad** [comment]
>what's the right way to re-try the merge if the failure is spurious

For posterity: there's rebuild button

image

but (what got me) you gotta be logged in to see it.

**Pull request merged**
