### PR TITLE
update seek_prefix

### PR DESCRIPTION
**Pull request by blasrodri**
Following up: https://github.com/near/nearcore/pull/7509#discussion_r961250476

### CODE REVIEW

**Comment by blasrodri** [comment]
@mina86 we continue the discussion here :)

**Comment by mina86** [comment]
Could you Allow edits from maintainers?

**Comment by blasrodri** [comment]
I don't have rights. Sorry.

**Comment by akhi3030** [comment]
> I don't have rights. Sorry.

@blasrodri : it is important to allow edits from maintainers to be able to make progress here.  Can you get in touch with someone who has rights or create the PR from a different repo where you have sufficient rights.

**Pull request closed without merging**
