### PR TITLE
Restructure network code

### PR DESCRIPTION
**Pull request by pmnoxx**
We working on network documentation (https://github.com/near/nearcore/issues/5156). It's going to be much easier to explain code structure once we move files to proper places.

- renamed `peer.rs` to `peer_actor.rs`
- renamed  `Peer` to `PeerActor`
- renamed `peer_manager.rs` to `peer_manager_actor.rs`
- renamed `edge_verifier.rs` to `edge_verifier_actor.rs`
- move files related to stats to `/stats` subfolder
- move files related to routing to `/routing` subfolder

### CODE REVIEW

**Comment by pmnoxx** [comment]
@bowenwang1996 @mm-near Can you take a look?

**Review by nikurt — APPROVED** [review]

**Review by mm-near — APPROVED** [review]
Thanks for cleaning  / moving the code.

As you have the others PRs pending - you should decide when you want to merge this one (as it will impact the others).

(I'd personally do it at the end once other are merged)

**Comment by pmnoxx** [comment]
@chefsale, @frol, @khorolets Can you take a look?

**Review by chefsale — APPROVED** [review]

**Comment by pmnoxx** [comment]
@bowenwang1996 @mzhangmzz Can you take a look?

**Review by bowenwang1996 — APPROVED** [review]

**Pull request merged**
