### PR TITLE
added build metadata badge

### PR DESCRIPTION
**Pull request by Rishabhraghwendra18**
issue: #5447

### CODE REVIEW

**Comment by Rishabhraghwendra18** [comment]
@chefsale may you review my changes ?

**Review by chefsale — APPROVED** [review]

**Comment by Rishabhraghwendra18** [comment]
Hi @bowenwang1996  . It's showing me that `cargo test` command failed in `buildkite/nearcore` . Here's the error msg:
```
BBBB Slept 15001; max_wait_ms 15000
--
  | thread 'routing::archival_node' panicked at 'Timed out waiting for the condition', chain/network/src/test_utils.rs:123:21
  | stack backtrace:

```
May you guide me what's wrong here . I am new to Rust that's why I am not able to figure it out

**Comment by bowenwang1996** [comment]
@Rishabhraghwendra18 it is unrelated to this PR and is a known issue #5718

**Comment by Rishabhraghwendra18** [comment]
> @Rishabhraghwendra18 it is unrelated to this PR and is a known issue #5718

Sorry I didn't see that issue

**Pull request merged**
