### PR TITLE
[DO NOT COMMIT] New import example

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
This PR is used for testing of adding new host method imports.

Not to be committed

### CODE REVIEW

**Review by ailisp — COMMENTED** [review]
Test looks good

**Comment by ilblackdragon** [comment]
Can we add this to nearcore contribution documentation / link from Nomicon in the section how to add new precompiles?

**Comment by bowenwang1996** [comment]
Action item: add to /docs about how to add a new host function

**Comment by akhi3030** [comment]
I do not think this is needed anymore for adding new host functions.

**Pull request closed without merging**
