### PR TITLE
chain: refactor `shard_assignments` module testing code

### PR DESCRIPTION
**Pull request by mina86**
Introduce `tests::assign_shards` wrapper which takes care of calling
the actual `assign_shards` function and performs basic validation on
the result.  Furthermore, make it return aggregated data which is
easier to assert on.

In that new function check whether all chunk producers have been
assigned to at least one shard and whether there isn’t imbalance in
how many shards chunk producers are assigned to.

With all that, adjust test cases to use the new function (which
usually makes them shorter) and make `test_distribution_common` a bit
more verbose when reporting failures.

Issue: https://github.com/near/nearcore/issues/5932

### CODE REVIEW

**Comment by mina86** [comment]
@mm-near, @mzhangmzz, friendly ping

**Review by mzhangmzz — APPROVED** [review]
LGTM!

**Comment by mzhangmzz** [comment]
One question though, this PR doesn't fix https://github.com/near/nearcore/issues/5932, right?

**Comment by mina86** [comment]
> One question though, this PR doesn't fix #5932, right?

Correct. I have subsequent changes that will fix it.

**Pull request merged**
