### PR TITLE
feat(workflow) Allow ci workflow to be started on demand.

### PR DESCRIPTION
**Pull request by VanBarbascu**
now you can start this workflow with `gh workflow run ci.yml --repo near/nearcore --ref <branch>`

### CODE REVIEW

**Review by nagisa — APPROVED** [review]

**Comment by nagisa** [comment]
I did approve since it seems nice, but also there's rarely a case where anybody should be pushing branches to near/nearcore anymore, so it isn't clear to me how much use this can get. Maybe for releases? But that could very well be triggered automatically.

**Comment by frol** [comment]
@race-of-sloths invite

**Comment by race-of-sloths** [comment]
@frol Thank you for calling!
    
@VanBarbascu Thank you for the contribution! Join [Race of Sloths](https://race-of-sloths.com) by simply mentioning me in your comment/PRs description and start collecting Sloth Points through contributions to open source projects.

<details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/VanBarbascu)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called
</details>

**Comment by VanBarbascu** [comment]
Given that we don't want to encourage people to add branches in upstream. I will abandon this change.

**Pull request closed without merging**
