### PR TITLE
fix(sync): fix a syncing stall when a shard split is happening soon

### PR DESCRIPTION
**Pull request by marcelo-gonzalez**
The client code will actually only update its sync state if
state_sync.run() returns Completed or Changed. If the sync state is
changed in StateSync::sync_shards_status() but the return value is
(false, false), then this won't happen. Note that forgetting to update
update_sync_status only really leads to problems when need_shard and
this_done are both left unset. But can't hurt to just set it to true
whenever we update the status in the code. Concretely, this bug leads
to a stall when syncing state if a shard split is incoming, with log
lines like the following showing up over and over:

022-05-29T17:16:12.216741Z DEBUG sync:run{sync="StateSync"}: sync: syncing state ..... status: StateDownloadComplete ...
...
...
022-05-29T17:16:12.216741Z DEBUG sync:run{sync="StateSync"}: sync: syncing state ..... status: StateDownloadComplete ...
...
...
022-05-29T17:16:12.216741Z DEBUG sync:run{sync="StateSync"}: sync: syncing state ..... status: StateDownloadComplete ...

This is sadly actually pretty hard to add a test for. A unit test
would be nice, but KeyValueRuntime doesn't update its shard layout, so
we can't actually get will_shard_layout_change_next_epoch() to return true
in the test code without adding that functionality. Also just using a
real NightshadeRuntime isn't possible since near-client doesn't import
nearcore, and it feels wrong to import that just for this test...

And then pytests are actually not easy to implement to get this to
fail either, since changing the shard layout in the genesis config and
setting the initial protocol version to 47 (like in
state_sync_fail.py) will cause the shard split to happen at epoch
height 2.  So to trigger this bug we want state sync to happen from
epoch height 1, but there's only actually a small corner case that
will allow that, where we start state sync when our header head is at
epoch height 2, but within 5 blocks of the epoch start. (this is actually
what happened when I ran into the stuck logs above)

### CODE REVIEW

**Comment by matklad** [comment]
Rather than not forgetting to set this variable, can we compare whether the status changed at the end? 

```diff
diff --git a/chain/client/src/sync.rs b/chain/client/src/sync.rs
index 91e73a075..c68bce05b 100644
--- a/chain/client/src/sync.rs
+++ b/chain/client/src/sync.rs
@@ -733,6 +733,7 @@ impl StateSync {
                 need_shard = true;
                 init_sync_download.clone()
             });
+            let old_status = ShardSyncStatus::StateDownloadHeader;
             let mut this_done = false;
             match shard_sync_download.status {
                 ShardSyncStatus::StateDownloadHeader => {
@@ -755,7 +756,6 @@ impl StateSync {
                             ],
                             status: ShardSyncStatus::StateDownloadParts,
                         };
-                        update_sync_status = true;
                         need_shard = true;
                     } else {
                         let prev = shard_sync_download.downloads[0].prev_update_time;
@@ -791,7 +791,6 @@ impl StateSync {
                         }
                     }
                     if parts_done {
-                        update_sync_status = true;
                         *shard_sync_download = ShardSyncDownload {
                             downloads: vec![],
                             status: ShardSyncStatus::StateDownloadScheduling,
@@ -809,7 +808,6 @@ impl StateSync {
                         state_parts_task_scheduler,
                     ) {
                         Ok(()) => {
-                            update_sync_status = true;
                             *shard_sync_download = ShardSyncDownload {
                                 downloads: vec![],
                                 status: ShardSyncStatus::StateDownloadApplying,
@@ -819,7 +817,6 @@ impl StateSync {
                             // Cannot finalize the downloaded state.
                             // The reasonable behavior here is to start from the very beginning.
                             error!(target: "sync", "State sync finalizing error, shard = {}, hash = {}: {:?}", shard_id, sync_hash, e);
-                            update_sync_status = true;
                             *shard_sync_download = init_sync_download.clone();
                             chain.clear_downloaded_parts(shard_id, sync_hash, state_num_parts)?;
                         }
@@ -830,7 +827,6 @@ impl StateSync {
                     if let Some(result) = result {
                         match chain.set_state_finalize(shard_id, sync_hash, result) {
                             Ok(()) => {
-                                update_sync_status = true;
                                 *shard_sync_download = ShardSyncDownload {
                                     downloads: vec![],
                                     status: ShardSyncStatus::StateDownloadComplete,
@@ -840,7 +836,6 @@ impl StateSync {
                                 // Cannot finalize the downloaded state.
                                 // The reasonable behavior here is to start from the very beginning.
                                 error!(target: "sync", "State sync finalizing error, shard = {}, hash = {}: {:?}", shard_id, sync_hash, e);
-                                update_sync_status = true;
                                 *shard_sync_download = init_sync_download.clone();
                                 let shard_state_header =
                                     chain.get_state_header(shard_id, sync_hash)?;
@@ -861,7 +856,6 @@ impl StateSync {
                     let state_num_parts =
                         get_num_state_parts(shard_state_header.state_root_node().memory_usage);
                     chain.clear_downloaded_parts(shard_id, sync_hash, state_num_parts)?;
-                    update_sync_status = true;
                     if split_states {
                         *shard_sync_download = ShardSyncDownload {
                             downloads: vec![],
@@ -883,7 +877,6 @@ impl StateSync {
                         state_split_scheduler,
                     )?;
                     debug!(target: "sync", "State sync split scheduled: me {:?}, shard = {}, hash = {}", me, shard_id, sync_hash);
-                    update_sync_status = true;
                     *shard_sync_download = ShardSyncDownload {
                         downloads: vec![],
                         status: ShardSyncStatus::StateSplitApplying,
@@ -895,7 +888,6 @@ impl StateSync {
                     if let Some(state_roots) = result {
                         chain
                             .build_state_for_split_shards_postprocessing(&sync_hash, state_roots)?;
-                        update_sync_status = true;
                         *shard_sync_download = ShardSyncDownload {
                             downloads: vec![],
                             status: ShardSyncStatus::StateSyncDone,
@@ -939,7 +931,6 @@ impl StateSync {
 
             // Execute syncing for shard `shard_id`
             if need_shard {
-                update_sync_status = true;
                 *shard_sync_download = self.request_shard(
                     me,
                     shard_id,
@@ -950,6 +941,7 @@ impl StateSync {
                     highest_height_peers,
                 )?;
             }
+            update_sync_status |= shard_sync_download.status != old_status;
         }
 
         Ok((update_sync_status, all_done))
```

**Comment by marcelo-gonzalez** [comment]
> Rather than not forgetting to set this variable, can we compare whether the status changed at the end?
 
+1. Yup, that's def better!

**Comment by marcelo-gonzalez** [comment]
ok added `update_sync_status = true` in a couple more places and renamed the varialbe, since actually it looks like the name is quite misleading. i think we really want to return `(true, _)` if any element of the `new_shard_sync` hash map changes at all, since otherwise it will just get dropped. (i.e. this will not run, which is the last chance to keep the modified data):

```rust
...
StateSyncResult::Changed(fetch_block) => {
                        self.client.sync_status = SyncStatus::StateSync(sync_hash, new_shard_sync);
...
```

feels very error prone to have to keep track of whether you changed any element of the hash map like that. makes me wonder why we are even cloning the map and doing that whole thing at all. Like why not just pass `StateSync::run()` a reference to the real one? looks like it has been done this way for a long time, since https://github.com/near/nearcore/pull/1007/. @matklad can you think of any reason that pattern is needed? if no maybe it would make sense to get rid of that in another PR

**Comment by matklad** [comment]
Sorry, didn't realize I am the sole reviewer here, I am not feeling confident enough to review this for correctness, assigning to mm

**Review by mzhangmzz — APPROVED** [review]

**Comment by mzhangmzz** [comment]
LGTM! Unrelated to this PR, but if you have time, please add some comments to the part of the code you spent time understanding, so the effort doesn't get lost since this part of code is complicated and under-documented.

**Comment by marcelo-gonzalez** [comment]
> LGTM! Unrelated to this PR, but if you have time, please add some comments to the part of the code you spent time understanding, so the effort doesn't get lost since this part of code is complicated and under-documented.

added a comment above the function. Still wonder whether this whole thing is even necessary, and why we can't just  pass this function a reference to `client.sync_state`... Seems like the `clone()` is just unnecessary and leads to the complications here, but maybe i'm missing something

**Pull request merged**
