### PR TITLE
wasmtime: upgrade to 9.0.3

### PR DESCRIPTION
**Pull request by nagisa**
This resolves some concerns about execution soundness on x86_64. Not that it matters too much for us, but it saves effort having to explain ourselves for having a vulnerable crate as a dependency.

### CODE REVIEW

**Comment by akhi3030** [comment]
The changes look good to me but I would feel more comfortable if someone more familiar with the space like @Ekleog-NEAR would give the final approval.

**Comment by Ekleog-NEAR** [comment]
I’d rather we wait for #8323 to land before landing this, as I’ve been working for the past few weeks on fixing all the tests (still have a few more to go), it’s finally close to being ready, and such a change would probably conflict with it. However, looks good to me in principle :)

**Comment by nagisa** [comment]
This is back on the table now!

**Review by Ekleog-NEAR — COMMENTED** [review]
LGTM! :)

**Pull request merged**
