### PR TITLE
Deprecate AnnounceAccounts

### PR DESCRIPTION
**Pull request by saketh-are**
AnnounceAccounts is a legacy mechanism supporting Validator AccountId -> PeerId lookups. It was superseded by AccountsData about a year ago and has been awaiting deprecation:

https://github.com/near/nearcore/blob/7c0b58fd02a7ecc401736628cc977f6c8cff5fbf/chain/network/src/peer_manager/network_state/mod.rs#L596-L606

By inspecting the `ACCOUNT_TO_PEER_LOOKUPS` metric for several mainnet validators, I've confirmed that AnnounceAccounts is no longer of use. Additionally, enough release versions have passed since the introduction of AccountsData that we can get rid of AnnounceAccounts entirely at this point (see #8182).

This PR removes all of the client code which has to do with creation and usage of AnnounceAccounts. I plan to send separate PRs removing related fields/types from the network message protocol and deprecating `DBCol::AccountAnnouncements` (as this PR is large enough already).

### CODE REVIEW

**Review by VanBarbascu — APPROVED** [review]

**Review by nagisa — COMMENTED** [review]
> I've confirmed that AccountsData is no longer of use.

Did you mean “`AnnounceAccounts` is no longer of use”?

---

Seems quite nice otherwise!

**Comment by saketh-are** [comment]
> > I've confirmed that AccountsData is no longer of use.
> 
> Did you mean “`AnnounceAccounts` is no longer of use”?

Thanks, yes, updated.

**Review by nagisa — APPROVED** [review]
Restamping

**Pull request merged**
