### PR TITLE
Fix some github security advisories

### PR DESCRIPTION
**Pull request by akhi3030**
Addresses security advisories related to lock_api and nix

### CODE REVIEW

**Review by mina86 — APPROVED** [review]

**Comment by akhi3030** [comment]
@matklad: what do you think about this PR?  I can back out the nix related changes if it makes sense to update `parking_lot`.

**Comment by matklad** [comment]
I do think it makes sense to upgrade parking lot. Note that you'll need to commit upgraded Cargo.lock as well, and looking at the lock can create a bucnh of action items to upgrade transitive deps to avoid duplication (eg, https://github.com/paperclip-rs/paperclip/pull/435)

**Comment by akhi3030** [comment]
Closing based on above comments

**Review by matklad — APPROVED** [review]

**Comment by matklad** [comment]
Filed:

* https://github.com/near/nearcore/issues/6995
* https://github.com/paperclip-rs/paperclip/issues/438

for actually getting rid of old parking_lot

**Pull request closed without merging**
