### PR TITLE
Revert "Update rocksdb to 0.19 (#7357)"

### PR DESCRIPTION
**Pull request by mm-near**
This reverts commit 7e7cac03c9c17fa0bf85a9fe02df7503b3e5d21d.

As we're about to cut the testnet release.

### CODE REVIEW

**Review by nikurt — APPROVED** [review]

**Comment by mina86** [comment]
I’m pretty sure we decided to make the revert on 1.29.0 branch and leave master alone? @marcelo-gonzalez

**Comment by nikurt** [comment]
@mina86 shardnet binary is built from the master branch

**Comment by mina86** [comment]
Commit message mentions testnet though; not shardnet.

**Comment by EdvardD** [comment]
Can we return this now?

**Comment by birchmd** [comment]
@mm-near echoing @EdvardD 's question again: can rocksdb be upgraded to 0.19 again?

It would be nice to upgrade due to an [open security advisory](https://github.com/advisories/GHSA-xpp3-xrff-w6rh) on older versions. That specific issue may not impact nearcore itself, but could matter for other libraries that use rocksdb together with nearcore (due to `librocksdb-sys` being a system library, there cannot be more than one version of rocksdb used in a Rust project).

**Comment by akhi3030** [comment]
@birchmd: thanks for the ping.  I've created https://github.com/near/nearcore/issues/7718 and also started a [zulip discussion](https://near.zulipchat.com/#narrow/stream/313099-pagoda.2Fstorage/topic/Upgrading.20rocksdb.20to.200.2E19).  I hope we can upgrade soon.

**Pull request merged**
