### PR TITLE
chore: replace full generic validation to unsafeFast flag

### PR DESCRIPTION
**Pull request by Mehrbod2002**
fixes: #9080

### CODE REVIEW

**Comment by Mehrbod2002** [comment]
@Longarithm All the full flags should be replaced ? event on main ?

**Comment by Longarithm** [comment]
`near_chain_configs::GenesisValidationMode::Full` is the right thing to do by default, especially on main code path. The goal is to look over all places where caller passes `genesis_validation: GenesisValidationMode` and use this validation mode.

**Comment by Mehrbod2002** [comment]
@Longarithm you mean use UnsafeFast in all modes ? Even when a function pass it as variable ?

**Comment by Longarithm** [comment]
It looks like the opposite of what I've meant. I mean that:
* by default we should use `near_chain_configs::GenesisValidationMode::Full` as we do now. It is the right thing to validate genesis.
* but if in the context a caller passes concrete genesis validation mode, I want to use this mode. For example, in the context of `FlatStorageCommand::run` you can find `let genesis_validation = if neard_cmd.opts.unsafe_fast_startup ...` which has to be used.

**Comment by Ekleog-NEAR** [comment]
@Mehrbod2002 Are you interested in looking into this again? :)

**Comment by Ekleog-NEAR** [comment]
It’s been a month, so I’ll assume you’re no longer interested in looking into this. Closing as a consequence, to clean up the open PR list. Please feel free to let me know / open another PR if that was a misunderstanding on my end! :)

**Pull request closed without merging**
