### PR TITLE
feat: rename `value_return` in gas profile

### PR DESCRIPTION
**Pull request by jakmeier**
This cost never made sense to me. It's cost is defined by
`new_data_receipt_byte` but for some reason it was tracked
as `value_return`.

In  #8044 I introduced `new_data_receipt_byte` as an action cost
but it is actually never used. This change replaces the old
`value_return` cost with `new_data_receipt_byte`.

This is an observable change on the RPC, as the profile now returns
a different key for this cost. But is is not a breaking change because
the profile keys are untyped.

### CODE REVIEW

**Comment by jakmeier** [comment]
@matklad can you please review this? I think you know the most around gas profiles.

**Comment by matklad** [comment]
>but for some reason it was tracked as value_return.

The reason is that's the name of the host function

**Comment by matklad** [comment]
Ie, perhaps it wants to be an Ext cost, not an action cost?

**Comment by jakmeier** [comment]
> The reason is that's the name of the host function

I see, that's a valid reason for the name but I still think we should rename it.

> Ie, perhaps it wants to be an Ext cost, not an action cost?

I feel it kind of makes sense to keep it an action costs. It is associated with promises and it does have a sending and executing part. Oddly, but for good reasons, we burn both of them upfront. So technically, we could have it as a single cost. We would just lose the option to charge local receipts differently from remote receipts. Currently it's the same value but if we ever wanted to include network bandwidth into the gas equation, `data_receipt_creation_per_byte_send_not_sir` would be the first value that I would look at.

**Comment by jakmeier** [comment]
I guess the alternative would be to rename the parameter to `value_return_bytes`. I don't see a strong reason why it would be better or worse. But it feels clearer to me to use the data receipt naming.

**Review by matklad — APPROVED** [review]
>I feel it kind of makes sense to keep it an action costs.

sgtm!

**Pull request merged**
