### PR TITLE
pytest: fix a failure in skip_epoch.py

### PR DESCRIPTION
**Pull request by marcelo-gonzalez**
In skip_epoch.py, there are two periods where a block producer
responsible for some shard is down. The first is when a validator
never went online to begin with, and the second is when we kill one
after the chain has been running for a while. In each case, we wait
for a couple epochs to pass and then check that the balances resulting
from a bunch of transactions are applied correctly, the idea being
that we want to check that some online validator is made responsible
for the offline shard and is able to sync its state.

In the second case, we record the latest block height before killing
the validator and then wait for EPOCH_LENGTH * 3 - 1 blocks, so that
we land at least in epoch T+2. But this may not be a long enough wait
period. If the validator had already produced some blocks in the epoch
in which it's killed, it might not actually drop below the kickout threshold
for that epoch, in which case we won't expect to see that shard's chunks' "height_included"
move up to HEAD until epoch T+3.

So fix it by waiting for that long, and actually make it explicit by
introducing a utils.poll_epochs() function that does basically the same
thing as poll_blocks(), but for epochs instead

### CODE REVIEW

**Comment by marcelo-gonzalez** [comment]
btw, I didn't change the first part of the test to use the poll_epochs() function because I tried it locally and I think it runs into https://github.com/near/nearcore/issues/5750, which complicates it.

Also failing tests are like this one and many others recently: https://nayduck.near.org/#/test/273491

**Comment by mina86** [comment]
You need to run `./scripts/formatting --fix`.

**Review by mina86 — APPROVED** [review]

**Review by bowenwang1996 — COMMENTED** [review]
@marcelo-gonzalez could we add more document on what the test *actually* does?

**Comment by marcelo-gonzalez** [comment]
> @marcelo-gonzalez could we add more document on what the test _actually_ does?

@bowenwang1996 Now that I've looked at it some, I think it would be worth just refactoring the test so that the code itself is a little more clear. There are comments sprinkled throughout the code that explain the idea behind the test, but it's not so easy to follow. Feels more worthwhile to me to make the test code itself clearer than to just stick a big comment at the top of the current test

**Pull request merged**
