### PR TITLE
fix: minor soundness issue

### PR DESCRIPTION
**Pull request by matklad**
These two impls are unsound -- they might lead to undefined behavior in
safe rust. Luckily, we only use `ProfileData` with a non-default feature
enabled, so this isn't a problem in practice.

Doubly lucky, seems like these impls are actually unused?

If, in the future, we actually need a SyncVersion of this, we should use
an array of atomics with Relaxed fetch_adds.

### CODE REVIEW

**Comment by matklad** [comment]
Let's see if this passes CI -- I tried to check locally with various features, but one never knows when there isn't yet another feature combination :)

**Comment by matklad** [comment]
Ok, this fails compilation of tests, so this is going to be slightly trickier to handle...

**Comment by matklad** [comment]
should be better now

**Review by frol — APPROVED** [review]

**Review by bowenwang1996 — APPROVED** [review]

**Comment by frol** [comment]
@matklad please, fmt

**Review by evgenykuzyakov — APPROVED** [review]

**Pull request merged**
