### PR TITLE
re: Fix `routing::archival_node` test

### LINKED ISSUE #5357: `routing::archival_node` is flaky
```sh
cargo test -p integration-tests --test network \
    -- --exact routing::archival_node
```

Sometimes passes, sometimes fails.  For example see [7398](https://buildkite.com/nearprotocol/nearcore/builds/7398) and [7404](https://buildkite.com/nearprotocol/nearcore/builds/7404) where I’ve re-run cargo test which passed the second time around.

### LINKED ISSUE #5389: Random test failure `routing::archival_node`
We have seen a random test failure for `routing::archival_node`

https://buildkite.com/nearprotocol/nearcore/builds/7640#d7e5d254-c79d-443b-9a07-58df975f5130

Plan:
- [ ] Add debug logs to `runner.rs` https://github.com/near/nearcore/pull/5390
- [ ] Add fix https://github.com/near/nearcore/pull/5639

### PR DESCRIPTION
**Pull request by pmnoxx**
Test broke due to 
```
commit 07dadeac0a4db8a1ff448fcf1174e706badf54eb
```

This should fix the issue.

Closes #5389
Closes #5357

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
Are we confident that this test wouldn't be flaky?

**Comment by pmnoxx** [comment]
After fix: ``` INFO nayduck::cargo_test: self.cmd.repeat=300 cmd=["cargo", "test", "-p", "integration-tests", "--tests", "archival_node"] successes=297 failures=3
```

Before fix:: ```
2021-12-07T01:46:30.567030Z  INFO nayduck::cargo_test: self.cmd.repeat=300 cmd=["cargo", "test", "-p", "integration-tests", "--tests", "archival_node"] successes=116 failures=184
```

@bowenwang1996 It's better, but probably still needs more work.

**Comment by pmnoxx** [comment]
@bowenwang1996 The, issue is with buggy implementation of `open_port()`. That's sad, but unrelated to this PR.

**Comment by pmnoxx** [comment]
`PeerManagerActor` crashes, due to it unable to open port, provided by `open_port()`.

**Comment by pmnoxx** [comment]
@bowenwang1996 I think we should ship the fix. This fixes the issue. There is another one related to `open_port`, but that applies to all `integration-tests`.

**Review by bowenwang1996 — APPROVED** [review]

**Pull request merged**
