### PR TITLE
chore: revert near-account-id's MSRV

### PR DESCRIPTION
**Pull request by miraclx**
As it turns out, `cargo-package` normalizes crate manifests before it's eventually published to crates.io. This means we don't have to be locked on to `rustc 1.64` which stabilized workspace inheritance.

~Although, compiling with `--all-features` activates the `arbitrary` dependency which requires `rustc 1.63`.~

~From experimentation, it looks like when fuzzing, both `cargo-fuzz` and `afl.rs` inject the `fuzzing` CFG attribute.~

~Which means, we can introduce the dep only when fuzzing, which should alleviate the pin, and keep us compiling just fine at `rustc 1.61`.~

Reverting back to `rustc 1.63` as the minimum supported rust version to compile with `--all-features` activated.

### CODE REVIEW

**Comment by Ekleog-NEAR** [comment]
Hmm I don’t really understand, what do we think we would gain by lowering the MSRV?

We don’t actually support any rust version other than the one specified by the `rust-version` file in nearcore anyway. So I think exposing the `arbitrary` feature in a consistent-with-the-ecosystem way would be more beneficial than lowering the MSRV from 1.64 when we’re really only supporting 1.69 anyway.

**Comment by miraclx** [comment]
`near-account-id` is a fully complete crate with stability guarantees. Breaking changes should be intentional before being published. The move up from `1.60` to `1.63` would force dependents to upgrade their rust versions as well. And seeing as all the code for the account ID itself compiles just fine on `1.61`, there's no reason to force users to be on `1.63` except when fuzzing.

Unfortunately, it's not possible to have conditional `rust-version` specifications. So I picked the minimum supported rust version to compile the crate as a regular dependency when you do not care about fuzzing.

**Comment by miraclx** [comment]
😅 Sound points, I'll repin this to `1.63` which will be the MSRV to compile with `--all-features` and restore the cfg attrs.

**Review by Ekleog-NEAR — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
