### PR TITLE
store: introduce StoreConfig::test_config constructor

### PR DESCRIPTION
**Pull request by mina86**
The problem some users encountered was that they were running tests in
an environment where resource limits (most notably hard NOFILE limit)
were too low for the default store configuration to work.  This lead
to the tests failing even though they could easily run without ever
approaching the limits.

This change introduces StoreConfig::test_config method which returns
test store configuration with max_open_files lowered to the old 512
default.

With that also rename Store::tmp_opener to test_opener (to indicate
it uses non-default configuration) and perform minor refactoring on
StoreConfig associated constants.

### CODE REVIEW

**Comment by mina86** [comment]
cc @Mic92

**Review by Longarithm — APPROVED** [review]

**Comment by matklad** [comment]
It feels somehow like too much machinery for a simple config (a bunch of const associated functions, a bunch of serde attributes, lazy-static, `'static` lifetime). Can we simplify this? I think the essential bit here is "we want StoreConfig: Default". Can we make the rest to hang off this? It seems we can:

```diff
diff --git a/core/store/benches/store_bench.rs b/core/store/benches/store_bench.rs
index e2d8e22c4..99e80c1bc 100644
--- a/core/store/benches/store_bench.rs
+++ b/core/store/benches/store_bench.rs
@@ -19,7 +19,7 @@ fn benchmark_write_then_read_successful(
     let tmp_dir = tempfile::tempdir().unwrap();
     // Use default StoreConfig rather than Store::test_opener so we’re using the
     // same configuration as in production.
-    let store = Store::opener(tmp_dir.path(), &Default::default()).open();
+    let store = Store::opener(tmp_dir.path(), Default::default()).open();
     let keys = generate_keys(num_keys, key_size);
     write_to_db(&store, &keys, max_value_size, col);
 
diff --git a/core/store/src/config.rs b/core/store/src/config.rs
index 2b5c3831c..3ddb6d55d 100644
--- a/core/store/src/config.rs
+++ b/core/store/src/config.rs
@@ -3,20 +3,12 @@ use near_primitives::version::DbVersion;
 const STORE_PATH: &str = "data";
 
 #[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
+#[serde(default)]
 pub struct StoreConfig {
-    /// Path to the database.  If relative, resolved relative to neard home
-    /// directory.  This is useful if node runs with a separate disk holding the
-    /// database.
-    #[serde(default)]
     pub path: Option<std::path::PathBuf>,
-
-    /// Collect internal storage layer statistics.
-    /// Minor performance impact is expected.
-    #[serde(default)]
     pub enable_statistics: bool,
 
     /// Re-export storage layer statistics as prometheus metrics.
-    #[serde(default = "StoreConfig::default_enable_statistics_export")]
     pub enable_statistics_export: bool,
 
     /// Maximum number of store files being opened simultaneously.
@@ -26,7 +18,6 @@ pub struct StoreConfig {
     /// needs.
     /// Increasing this value up to a value higher than 1024 also requires setting `ulimit -n` in
     /// Linux.
-    #[serde(default = "StoreConfig::default_max_open_files")]
     pub max_open_files: u32,
 
     /// Cache size for DBCol::State column.
@@ -34,56 +25,16 @@ pub struct StoreConfig {
     /// Increasing DBCol::State cache size helps making storage more efficient. On the other hand we
     /// don't want to increase hugely requirements for running a node so currently we use a small
     /// default value for it.
-    #[serde(default = "StoreConfig::default_col_state_cache_size")]
     pub col_state_cache_size: bytesize::ByteSize,
 
     /// Block size used internally in RocksDB.
     /// Default value: 16KiB.
     /// We're still experimented with this parameter and it seems decreasing its value can improve
     /// the performance of the storage
-    #[serde(default = "StoreConfig::default_block_size")]
     pub block_size: bytesize::ByteSize,
 }
 
 impl StoreConfig {
-    /// Returns the default value for the `max_open_files` database limite.
-    ///
-    /// We used to use value of 512 but we were hitting that limit often and
-    /// store had to constantly close and reopen the same set of files.  Running
-    /// state viewer on a dense set of 500 blocks did almost 200k file opens
-    /// (having less than 7K unique files opened, some files were opened 400+
-    /// times).  Using 10k limit for max_open_files led to performance
-    /// improvement of ~11%.
-    const fn default_max_open_files() -> u32 {
-        10_000
-    }
-
-    /// Returns the default [`DBCol::State`] cache size.
-    ///
-    /// We used to have the same cache size for all columns, 32 MiB.  When some
-    /// RocksDB inefficiencies were found [`DBCol::State`] cache size was
-    /// increased up to 512 MiB.  This was done on 13th of Nov 2021 and we
-    /// consider increasing the value.  Tests have shown that increase to 25 GiB
-    /// (we've used this big value to estimate performance improvement headroom)
-    /// having `max_open_files` at 10k improved performance of state viewer by
-    /// 60%.
-    const fn default_col_state_cache_size() -> bytesize::ByteSize {
-        bytesize::ByteSize::mib(512)
-    }
-
-    /// Returns the default value for database block size.
-    ///
-    /// This value was taken from the Openethereum default parameter and we use
-    /// it since then.
-    const fn default_block_size() -> bytesize::ByteSize {
-        bytesize::ByteSize::kib(16)
-    }
-
-    /// Returns the default for `enable_statistics_export` setting.
-    const fn default_enable_statistics_export() -> bool {
-        true
-    }
-
     /// Returns configuration meant for tests.
     ///
     /// Since tests often operate with less data than real node, the test
@@ -108,10 +59,25 @@ impl Default for StoreConfig {
         Self {
             path: None,
             enable_statistics: false,
-            enable_statistics_export: Self::default_enable_statistics_export(),
-            max_open_files: Self::default_max_open_files(),
-            col_state_cache_size: Self::default_col_state_cache_size(),
-            block_size: Self::default_block_size(),
+            enable_statistics_export: true,
+            /// We used to use value of 512 but we were hitting that limit often and
+            /// store had to constantly close and reopen the same set of files.  Running
+            /// state viewer on a dense set of 500 blocks did almost 200k file opens
+            /// (having less than 7K unique files opened, some files were opened 400+
+            /// times).  Using 10k limit for max_open_files led to performance
+            /// improvement of ~11%.
+            max_open_files: 10_000,
+            /// We used to have the same cache size for all columns, 32 MiB.  When some
+            /// RocksDB inefficiencies were found [`DBCol::State`] cache size was
+            /// increased up to 512 MiB.  This was done on 13th of Nov 2021 and we
+            /// consider increasing the value.  Tests have shown that increase to 25 GiB
+            /// (we've used this big value to estimate performance improvement headroom)
+            /// having `max_open_files` at 10k improved performance of state viewer by
+            /// 60%.
+            col_state_cache_size: bytesize::ByteSize::mib(512),
+            /// This value was taken from the Openethereum default parameter and we use
+            /// it since then.
+            block_size: bytesize::ByteSize::kib(16),
         }
     }
 }
@@ -131,7 +97,7 @@ pub fn get_store_path(base_path: &std::path::Path) -> std::path::PathBuf {
 ///     .home(neard_home_dir)
 ///     .open();
 /// ```
-pub struct StoreOpener<'a> {
+pub struct StoreOpener {
     /// Path to the database.
     ///
     /// This is resolved from nearcore home directory and store configuration
@@ -139,15 +105,15 @@ pub struct StoreOpener<'a> {
     path: std::path::PathBuf,
 
     /// Configuration as provided by the user.
-    config: &'a StoreConfig,
+    config: StoreConfig,
 
     /// Whether to open the storeg in read-only mode.
     read_only: bool,
 }
 
-impl<'a> StoreOpener<'a> {
+impl StoreOpener {
     /// Initialises a new opener with given home directory and store config.
-    pub(crate) fn new(home_dir: &std::path::Path, config: &'a StoreConfig) -> Self {
+    pub(crate) fn new(home_dir: &std::path::Path, config: StoreConfig) -> Self {
         let path =
             home_dir.join(config.path.as_deref().unwrap_or(std::path::Path::new(STORE_PATH)));
         Self { path, config, read_only: false }
diff --git a/core/store/src/lib.rs b/core/store/src/lib.rs
index 7e94db3bd..d41a78042 100644
--- a/core/store/src/lib.rs
+++ b/core/store/src/lib.rs
@@ -7,7 +7,6 @@ use std::{fmt, io};
 
 use borsh::{BorshDeserialize, BorshSerialize};
 use byteorder::{LittleEndian, ReadBytesExt, WriteBytesExt};
-use once_cell::sync::Lazy;
 
 pub use columns::DBCol;
 pub use db::{
@@ -56,7 +55,7 @@ pub struct Store {
 
 impl Store {
     /// Initialises a new opener with given home directory and store config.
-    pub fn opener<'a>(home_dir: &std::path::Path, config: &'a StoreConfig) -> StoreOpener<'a> {
+    pub fn opener(home_dir: &std::path::Path, config: StoreConfig) -> StoreOpener {
         StoreOpener::new(home_dir, config)
     }
 
@@ -68,10 +67,9 @@ impl Store {
     ///
     /// Note that the caller must hold the temporary directory returned as first
     /// element of the tuple while the store is open.
-    pub fn test_opener() -> (tempfile::TempDir, StoreOpener<'static>) {
-        static CONFIG: Lazy<StoreConfig> = Lazy::new(StoreConfig::test_config);
+    pub fn test_opener() -> (tempfile::TempDir, StoreOpener) {
         let dir = tempfile::tempdir().unwrap();
-        let opener = Self::opener(dir.path(), &CONFIG);
+        let opener = Self::opener(dir.path(), StoreConfig::test_config());
         (dir, opener)
     }
 
```

**Comment by matklad** [comment]
> And ‘let’s just copy so we don’t need to deal with lifetimes’ sounds like an anti-patern and language defect to me.

Still better than "let's just copy so we don't need to deal with UAFs" :P 

I do see `'static` as an issue -- it's a sign we are fighting the language, and I don't think it's worth it to get in a fight with a language over a mere config struct. 

And `Lazy` in particular always raises red flags to me -- that's singleton, and singletons are often correlated with sloppy code, and we did have real problems from then in https://github.com/near/nearcore/issues/4468.

Not saying that this particular usage is particularly problematic, but it does feel broken-windowy to me.

**Comment by mina86** [comment]
> And `Lazy` in particular always raises red flags to me -- that's singleton, and singletons are often correlated with sloppy code, and we did have real problems from then in #4468.

The issue there wasn’t that it was a singleton.  It was that it was mutable.  Immutable singletons are never an issue.  String literals are a prominent examples of those.

**Pull request merged**
