### PR TITLE
nightly: remove non-expensive tests from expensive set

### PR DESCRIPTION
**Pull request by mina86**

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
I am confused. What happens to the tests that are removed?

**Comment by mina86** [comment]
The tests are not guarded by `expensive_tests` feature and as such they are processed via normal `cargo tests` invocation which is done as part of buildkit pipeline.

**Comment by bowenwang1996** [comment]
@mina86 I see. It seems that we want them to be run in nayduck rather than CI. Could we fix this by moving them to expensive tests?

**Comment by mina86** [comment]
> It seems that we want them to be run in nayduck rather than CI.

Do we? All of those tests take at most a second to run.

**Comment by mina86** [comment]
```
| name                                                                                                                   | run_time |
+------------------------------------------------------------------------------------------------------------------------+----------+
| expensive integration-tests standard_cases runtime::test::test_access_key_reject_non_function_call_runtime             |        0 |
| expensive integration-tests standard_cases runtime::test::test_access_key_reject_non_function_call_runtime             |        0 |
| expensive integration-tests standard_cases runtime::test::test_access_key_smart_contract_reject_contract_id_runtime    |        0 |
| expensive integration-tests standard_cases runtime::test::test_access_key_smart_contract_reject_contract_id_runtime    |        1 |
| expensive integration-tests standard_cases runtime::test::test_access_key_smart_contract_reject_method_name_runtime    |        1 |
| expensive integration-tests standard_cases runtime::test::test_access_key_smart_contract_reject_method_name_runtime    |        0 |
| expensive integration-tests standard_cases runtime::test::test_access_key_smart_contract_runtime                       |        1 |
| expensive integration-tests standard_cases runtime::test::test_access_key_smart_contract_runtime                       |        1 |
| expensive integration-tests standard_cases runtime::test::test_add_access_key_function_call_runtime                    |        0 |
| expensive integration-tests standard_cases runtime::test::test_add_access_key_function_call_runtime                    |        0 |
| expensive integration-tests standard_cases runtime::test::test_add_access_key_with_allowance_runtime                   |        1 |
| expensive integration-tests standard_cases runtime::test::test_add_access_key_with_allowance_runtime                   |        0 |
| expensive integration-tests standard_cases runtime::test::test_add_existing_key_runtime                                |        0 |
| expensive integration-tests standard_cases runtime::test::test_add_existing_key_runtime                                |        0 |
| expensive integration-tests standard_cases runtime::test::test_add_key_runtime                                         |        1 |
| expensive integration-tests standard_cases runtime::test::test_add_key_runtime                                         |        0 |
| expensive integration-tests standard_cases runtime::test::test_async_call_with_logs_runtime                            |        1 |
| expensive integration-tests standard_cases runtime::test::test_async_call_with_logs_runtime                            |        1 |
| expensive integration-tests standard_cases runtime::test::test_create_account_again_runtime                            |        1 |
| expensive integration-tests standard_cases runtime::test::test_create_account_again_runtime                            |        0 |
| expensive integration-tests standard_cases runtime::test::test_create_account_failure_already_exists_runtime           |        0 |
| expensive integration-tests standard_cases runtime::test::test_create_account_failure_already_exists_runtime           |        0 |
| expensive integration-tests standard_cases runtime::test::test_create_account_failure_invalid_name_runtime             |        0 |
| expensive integration-tests standard_cases runtime::test::test_create_account_failure_invalid_name_runtime             |        0 |
| expensive integration-tests standard_cases runtime::test::test_create_account_failure_no_funds_runtime                 |        1 |
| expensive integration-tests standard_cases runtime::test::test_create_account_failure_no_funds_runtime                 |        1 |
| expensive integration-tests standard_cases runtime::test::test_create_account_runtime                                  |        0 |
| expensive integration-tests standard_cases runtime::test::test_create_account_runtime                                  |        0 |
| expensive integration-tests standard_cases runtime::test::test_decrease_stake_runtime                                  |        0 |
| expensive integration-tests standard_cases runtime::test::test_decrease_stake_runtime                                  |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_access_key_runtime                               |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_access_key_runtime                               |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_access_key_with_allowance_runtime                |        1 |
| expensive integration-tests standard_cases runtime::test::test_delete_access_key_with_allowance_runtime                |        1 |
| expensive integration-tests standard_cases runtime::test::test_delete_account_has_enough_money_runtime                 |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_account_has_enough_money_runtime                 |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_account_no_account_runtime                       |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_account_no_account_runtime                       |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_account_signer_is_receiver                       |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_account_signer_is_receiver                       |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_account_while_staking_runtime                    |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_account_while_staking_runtime                    |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_key_last_runtime                                 |        1 |
| expensive integration-tests standard_cases runtime::test::test_delete_key_last_runtime                                 |        1 |
| expensive integration-tests standard_cases runtime::test::test_delete_key_not_owned_runtime                            |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_key_not_owned_runtime                            |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_key_runtime                                      |        0 |
| expensive integration-tests standard_cases runtime::test::test_delete_key_runtime                                      |        0 |
| expensive integration-tests standard_cases runtime::test::test_fail_not_enough_balance_for_storage_runtime             |        1 |
| expensive integration-tests standard_cases runtime::test::test_fail_not_enough_balance_for_storage_runtime             |        0 |
| expensive integration-tests standard_cases runtime::test::test_increase_stake_runtime                                  |        0 |
| expensive integration-tests standard_cases runtime::test::test_increase_stake_runtime                                  |        1 |
| expensive integration-tests standard_cases runtime::test::test_nonce_updated_when_tx_failed_runtime                    |        0 |
| expensive integration-tests standard_cases runtime::test::test_nonce_updated_when_tx_failed_runtime                    |        0 |
| expensive integration-tests standard_cases runtime::test::test_nonce_update_when_deploying_contract_runtime            |        1 |
| expensive integration-tests standard_cases runtime::test::test_nonce_update_when_deploying_contract_runtime            |        0 |
| expensive integration-tests standard_cases runtime::test::test_redeploy_contract_runtime                               |        1 |
| expensive integration-tests standard_cases runtime::test::test_redeploy_contract_runtime                               |        0 |
| expensive integration-tests standard_cases runtime::test::test_refund_on_send_money_to_non_existent_account_runtime    |        0 |
| expensive integration-tests standard_cases runtime::test::test_refund_on_send_money_to_non_existent_account_runtime    |        0 |
| expensive integration-tests standard_cases runtime::test::test_send_money_over_balance_runtime                         |        0 |
| expensive integration-tests standard_cases runtime::test::test_send_money_over_balance_runtime                         |        0 |
| expensive integration-tests standard_cases runtime::test::test_send_money_runtime                                      |        0 |
| expensive integration-tests standard_cases runtime::test::test_send_money_runtime                                      |        0 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_bad_method_name_runtime                  |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_bad_method_name_runtime                  |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_empty_method_name_with_no_tokens_runtime |        0 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_empty_method_name_with_no_tokens_runtime |        0 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_empty_method_name_with_tokens_runtime    |        0 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_empty_method_name_with_tokens_runtime    |        0 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_free_runtime                             |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_free_runtime                             |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_panic_runtime                            |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_panic_runtime                            |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_reward_runtime                           |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_reward_runtime                           |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_self_call_runtime                        |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_self_call_runtime                        |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_simple_runtime                           |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_simple_runtime                           |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_with_args_runtime                        |        1 |
| expensive integration-tests standard_cases runtime::test::test_smart_contract_with_args_runtime                        |        1 |
| expensive integration-tests standard_cases runtime::test::test_swap_key_runtime                                        |        0 |
| expensive integration-tests standard_cases runtime::test::test_swap_key_runtime                                        |        0 |
| expensive integration-tests standard_cases runtime::test::test_transfer_tokens_implicit_account_runtime                |        0 |
| expensive integration-tests standard_cases runtime::test::test_transfer_tokens_implicit_account_runtime                |        0 |
| expensive integration-tests standard_cases runtime::test::test_trying_to_create_implicit_account_runtime               |        0 |
| expensive integration-tests standard_cases runtime::test::test_trying_to_create_implicit_account_runtime               |        0 |
| expensive integration-tests standard_cases runtime::test::test_unstake_while_not_staked_runtime                        |        0 |
| expensive integration-tests standard_cases runtime::test::test_unstake_while_not_staked_runtime                        |        0 |
| expensive integration-tests standard_cases runtime::test::test_upload_contract_runtime                                 |        1 |
| expensive integration-tests standard_cases runtime::test::test_upload_contract_runtime                                 |        1 |
```

**Comment by bowenwang1996** [comment]
> All of those tests take at most a second to run.

I see.

**Review by bowenwang1996 — APPROVED** [review]

**Pull request merged**
