### PR TITLE
chain: set the gc_fork_clean_step default to 100

### PR DESCRIPTION
**Pull request by marcelo-gonzalez**
The current default has shown itself to be quite expensive at times,
sometimes taking ~half a second to go through all 1000. Drop the default to
100 to try and mitigate this.

Note that since most people won't have set this new config option manually,
this will be a real change for most.

### CODE REVIEW

**Comment by nagisa** [comment]
I've little exposure to this code to review quickly. I can try and make some time to familiarize with the relevant portions, but if landing this soon is a concern, you'd be better served by finding somebody else to review this ^^

**Comment by marcelo-gonzalez** [comment]
> 



> I've little exposure to this code to review quickly. I can try and make some time to familiarize with the relevant portions, but if landing this soon is a concern, you'd be better served by finding somebody else to review this ^^

@nagisa No problem, I've actually been discussing this with @mina86 and @mm-near, so they already have context on this and have even tested the value some

**Review by mm-near — APPROVED** [review]

**Review by mina86 — APPROVED** [review]

**Comment by bowenwang1996** [comment]
@marcelo-gonzalez I thought we wanted this change in the 1.26.0 release. Did I miss something?

**Comment by marcelo-gonzalez** [comment]
> @marcelo-gonzalez I thought we wanted this change in the 1.26.0 release. Did I miss something?

yeah, didn't realize at the time that it broke several tests so will include it in an -rc2 after I fix those

**Pull request merged**
