### PR TITLE
cryptohashmap: avoid rehashing `CryptoHash` where it is already used as a key

### PR DESCRIPTION
**Pull request by nagisa**
This pull request adds a new data type to `near-primitives-core`. This data structure is your standard hashmap, with the key set to `CryptoHash`. Since the key is already a hash, it can be used as a key into the hashmap buckets directly, without having to go through another hashing function. I've seen this hashing cause some overhead that was noticeable in profiles.

Unfortunately demonstrating the improvement here is pretty difficult. We don't actually spend *too* much time on hashing the hashes, so this improvement gets somewhat hidden away in the overall run-to-run variance (e.g. the `get_promise_yield_indices` has a variance of >100ms). But when filtering the profiles it is still possible to see a non-trivial improvement on the particular computation-only operations that rely on these `HashMap`s, most notably the `TrieAccountingCache`, which went from, like 12ms of total samples to 8.5ms.

### CODE REVIEW

**Comment by nagisa** [comment]
Pending tests (though they won't be really exhaustive given that most of the new code basically delegates to other well tested code) and CI fixes.

**Review by wacban — COMMENTED** [review]
I like the idea but I do dislike the complexity and developer overhead. 

I see that HashMap has a with_hasher constructor and other ways for replacing the hasher. Can we use that instead of wrapping the HashTable? Would it be any simpler? 

For context, is there any particular HashMap object that causes the trouble is it more of a death by a thousand cuts scenario?

**Comment by nagisa** [comment]
The `Hasher` & `Hash` traits that the usual `HashMap` implementations rely on is not suitable for workloads that would like to not hash anything. While I can see ways I could make an implementation of a `Hasher` that would enable a desired behaviour, having such a thing around in the code base would end up being quite risky (as there is no way to enforce that this hasher is only ever use with `CryptoHash`es.)

**Comment by nagisa** [comment]
All this is to say is that I believe doing this sort of wrapping is the only way we could possibly land something like this. We can still look for a faster hash function, however. My intuition suggests that hashing a strong hash with a weak hash function still retains the unpredictability properties of the strong hash function...

**Comment by nagisa** [comment]
Seems like we've arriving at a conclusion that this ain't worth it.

**Pull request closed without merging**
