### PR TITLE
client: add GetBlockHash request and use it in Rosetta RPC

### PR DESCRIPTION
**Pull request by mina86**
The `/network/status` Rosetta RPC returns, among other things, height
and hash of the genesis block.  Currently, it does it by fetching the
genesis block.  Sadly, in non-archival nodes, genesis block is usually
unavailable which leads to failures in serving the RPC.  To address
this issue, introduce a `GetBlockHash` request which returns only the
hash of a block.  Since height→hash mapping is not garbage collected,
this request will always work even for garbage collected blocks.

### CODE REVIEW

**Comment by mina86** [comment]
Then again, maybe it would be even better to add `GetBlockHash` instead? That’s all Rosetta needs and it wouldn’t introduce dependency on storing all headers in the database.

**Review by frol — APPROVED** [review]

**Comment by frol** [comment]
I believe this approach if fair enough, so we can live with it until nearcore needs to do anything about the fact of storing all the block headers.

**Comment by mina86** [comment]
> I believe this approach if fair enough, so we can live with it until nearcore needs to do anything about the fact of storing all the block headers.

I actually already had a commit with the change just as you commented. ;) I’m gonna push it to this PR. If others have preferences for one or the other variant (`GetBlockHeader` or `GetBlockHash`) I can easily swap between the two.

**Review by bowenwang1996 — APPROVED** [review]
This would work fine as a stop-gap solution, but when #3487 is implemented, we need a different solution.

**Review by khorolets — APPROVED** [review]

**Pull request merged**
