### PR TITLE
refactor: remove obsolete rewards config override

### PR DESCRIPTION
**Pull request by mercepluka**
Removing obsolete rewards config overrides used for enabling inflation in older versions. Now both testnet and mainnet versions are beyond the `ENABLE_INFLATION_PROTOCOL_VERSION` version (36)

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
looks like this change would remove the ability to replay history within the same binary. cc @Ekleog

**Comment by mercepluka** [comment]
Can you please explain this

**Comment by Longarithm** [comment]
@mercepluka One property of blockchain is that it gives an option to replay all chain history since genesis, which means that we must be able to re-process any single existing block and verify that it was recorded correctly. This feature is actually in use.

Here you can see that our mainnet genesis protocol version is 29 https://explorer.near.org/stats. This PR changes behaviour for protocol version 36, which means that with that change we won't be able to replay mainnet blocks for this version correctly, so we can't proceed with that.

However, you can take a look at #8197 - we have a big task to require nearcore binary to support only latest protocol versions, to avoid maintenance of very old versions in newest binary - as your PR proposes.

**Comment by mercepluka** [comment]
@Longarithm thanks for the detailed answer. Is it ok to leave this PR for now and merge it once the limited replayability feature is landed?

**Comment by Longarithm** [comment]
Depends on if you are fine with waiting until it is finished, because I can imagine it taking a long time. cc @Ekleog

**Comment by mercepluka** [comment]
@Longarithm, I discussed this with @mhalambek today and this is not extremely urgent to Calimero. We would prefer if this PR remains opened and just merge once limited replayability is landed

**Comment by Longarithm** [comment]
@mercepluka do you plan to continue working on it in the near future? If not, could you move it to Draft to indicate that it is not under active development for now?

**Comment by Longarithm** [comment]
Closing for now. Feel free to reopen when you continue working on it!

**Pull request closed without merging**
