### PR TITLE
chore: update tokio

### PR DESCRIPTION
**Pull request by iho**
https://github.com/near/nearcore/pull/9524#issuecomment-1759241641
I turned `~1.28` into `1.28` and ran `cargo update -p tokio`  as @frol recommended. 

`cargo deny --all-features check bans` returns two warnings but zero errors. 

image_2023-10-12_20-03-31

I want to point out that we have several errors in the `advisories` section of `cargo-deny` output. I hope the team is well aware of those errors. 

Screenshot 2023-10-13 at 14 49 18
Screenshot 2023-10-13 at 14 49 30
Screenshot 2023-10-13 at 14 50 00
Screenshot 2023-10-13 at 14 50 20

Fixing the issue with `ed25519-dalek` requires an upgrade to crate version 2.0 and changes in codebase of nearcore

### CODE REVIEW

**Review by frol — APPROVED** [review]

**Review by nikurt — COMMENTED** [review]
Looks good, but why not `1.33`?

**Comment by nikurt** [comment]
> I want to point out that we have several errors in the advisories section of cargo-deny output. I hope the team is well aware of those errors.

@iho would be great if you could upgrade those crates. Please let me know if you're considering this.

**Comment by frol** [comment]
@nikurt This change is needed for the dependents that use near-* as crates and currently getting locked version of tokio which creates conflicts sometimes if there is another dependency requiring, e.g. tokio>=1.30.

Whether to update tokio to 1.33 or not is up to nearcore team as it only affects binary deliverables (neard).

@iho I see that Cargo.lock got updated to 1.29.1. My guess is that there is some dependency in the tree that holds it down to <1.30. Is this the case? What do you think? Have you tried to force it to update to 1.33, how did it go?

**Review by nikurt — APPROVED** [review]

**Comment by iho** [comment]
@nikurt I tried to fix errors in advisories in this PR https://github.com/near/nearcore/pull/9667 , but `ed25519-dalek` requires not trivial changes that I can't do by themself because they have breaking changes in API https://github.com/dalek-cryptography/curve25519-dalek/tree/main/ed25519-dalek#breaking-changes-in-200

**Comment by iho** [comment]
@frol I can update to tokio 1.33, but `cargo-deny` complains about two duplicate entries.  Is it okay to add an older version of socket2 to skip the list of `cargo-deny`?
image_2023-10-13_15-33-09
image_2023-10-13_15-37-47

**Comment by frol** [comment]
@nikurt Can you merge this PR? (I can't) It seems that macos builder is offline and all the other tests passed. Looking at the closed PRs, they were merged regardless of macos check status.

**Pull request merged**
