### PR TITLE
feat(forknet): Move neard_runner.py to systemd

### PR DESCRIPTION
**Pull request by VanBarbascu**
Created neard-runner.service that will manage the lifecycle of neard_runner.py. This will increase the reliability by restarting the process when it crashes and managing logs.

To migrate an existing mocknet to the new service:
```
mirror run-cmd --cmd "pkill -f neard_runner"
mirror restart-neard-runner --upload-program
```

The logs for the new services can be queried by:
```
# old logs
journalctl -ru neard-runner
# follow logs
journalctl -fu neard-runner
```

### CODE REVIEW

**Review by nagisa — COMMENTED** [review]
I believe using `systemd-run` to create a transient (if predictably named) service is much more appropriate in this situation.

A couple of major benefits:

1. It does not pollute system with random service files;
2. It is easier to make it work correctly regardless of what argument is passed to `switch_user`;
3. The `systemd-run` tool is intended for exactly these sorts of use-cases where programmatic/unattended operation of services is desired.

**Comment by VanBarbascu** [comment]
> I believe using `systemd-run` to create a transient (if predictably named) service is much more appropriate in this situation.
> 
> A couple of major benefits:
> 
>     1. It does not pollute system with random service files;
> 
>     2. It is easier to make it work correctly regardless of what argument is passed to `switch_user`;
> 
>     3. The `systemd-run` tool is intended for exactly these sorts of use-cases where programmatic/unattended operation of services is desired.

This is not supposed to be a transient unit. It is the orchestrator counterpart. It is supposed to run on all hosts for the whole lifetime of the forknet.

Maybe I misunderstood your suggetion. Can you clarify how to run this?

**Comment by nagisa** [comment]
It is "transient" in so far that it does not survive a machine reboot. However what's added here does not “survive” it either given that the service files here don't get `systemd enable`d.

> Can you clarify how to run this?

Something along the lines of...

```
systemd-run -u neard-runner --uid=$USER --property=StartLimitIntervalSec=500 --property=StartLimitBurst=10 --property=DefaultDependencies=no --property=TimeoutStartSec=300 --property=EnvironmentFile=/etc/neard/neard_runner.conf --property=Restart=always --property=RestartSec=5s -- $COMMAND
```

**Comment by VanBarbascu** [comment]
@nagisa, thanks for the clarification! This is indeed 1000x cleaner.

**Comment by nagisa** [comment]
Note though that this command can only be run if a service with name `neard-runner` does not yet exist. If there is already a transient such service (as started e.g. by a previous `systemd-run` command) then it can be cleaned up as such:

```
systemctl stop neard-runner
systemctl reset-failed neard-runner
```

But otherwise `start`, `stop`, journal commands, etc. work exactly like you would expect from any other service for that specific boot.

**Review by nagisa — APPROVED** [review]

**Pull request merged**
