### PR TITLE
chore(rust): migrate to rust 1.60.0

### PR DESCRIPTION
**Pull request by kakoc**
#6400

### CODE REVIEW

**Review by matklad — APPROVED** [review]

**Comment by matklad** [comment]
cc @jakmeier let's update estimator's Rust version in a separate PR

**Comment by mina86** [comment]
By the way, is there a list of features that got stabilised in each release? I sometimes leave ‘TODO(mina86): Use foo once bar stabilises’ comments and it would be nice to catch those.

**Comment by matklad** [comment]
@mina86 https://github.com/rust-lang/rust/blob/master/RELEASES.md#stabilized-apis

**Comment by jakmeier** [comment]
> cc @jakmeier let's update estimator's Rust version in a separate PR

@matklad Assuming you mean the docker image for qemu based estimation, here you go: https://github.com/near/nearcore/pull/6558

**Pull request merged**
