### PR TITLE
loadtest: use python match statement

### PR DESCRIPTION
**Pull request by jakmeier**
note: this requires python 3.10 or newer to work

### CODE REVIEW

**Review by nikurt — APPROVED** [review]

**Comment by akhi3030** [comment]
You can also consider adding a [version check](https://python.land/check-for-a-minimum-required-python-version) in the code if we don't already have something like this.

**Comment by jakmeier** [comment]
> You can also consider adding a [version check](https://python.land/check-for-a-minimum-required-python-version) in the code if we don't already have something like this.

I tried that by adding such a check at the top of `base.py`. But running locust with python 3.8, I got a syntax error parsing the file before the check could be triggered, so unless I did something wrong the check wouldn't do anything.

**Comment by akhi3030** [comment]
> > You can also consider adding a [version check](https://python.land/check-for-a-minimum-required-python-version) in the code if we don't already have something like this.
> 
> I tried that by adding such a check at the top of `base.py`. But running locust with python 3.8, I got a syntax error parsing the file before the check could be triggered, so unless I did something wrong the check wouldn't do anything.

Weird...

**Review by akashin — APPROVED** [review]
Neat!

**Pull request closed without merging**
