### PR TITLE
client: add {node,validator}_public_key field to /status response; deprecated node_key

### PR DESCRIPTION
**Pull request by mina86**
Currently, response to the /status request returns a `node_key`
field. However, the field does not include node key but rather
validator key.  Deprecated it in favour of two new fields:
`node_public_key` and `validator_public_key`.

Fixes: https://github.com/near/nearcore/issues/7672

### CODE REVIEW

**Comment by mina86** [comment]
This is really more of an RFC since I’m not convinced myself that this is a correct way to do this.

**Comment by akhi3030** [comment]
Tagging some folks from the node team to weight in on the PR then: @nikurt

**Comment by nikurt** [comment]
The change looks good.
Given that we don't know anything about dependencies on the current semantics of `node_key`, let's be prudent and add new fields before removing/repurposing the old one. Something like `node_public_key`, `validator_public_key` should be clear enough.

**Comment by mina86** [comment]
@akhi3030 or @nikurt, can I haz approval? ;)

**Review by nikurt — APPROVED** [review]

**Review by akhi3030 — APPROVED** [review]

**Pull request merged**
