### PR TITLE
feat: EVM internal bench

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
Adding internal benchmarks for EVM cryptozombies contract.

Issue: #3702

To run: `cargo bench -p near-evm-runner --features=nightly_protocol,protocol_feature_evm`

Example result:
```
     Running target/release/deps/bench-14ad756e350fecb2
create_random           time:   [109.43 us 109.67 us 109.94 us]
                        change: [-4.0627% -3.1325% -2.2478%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) low mild
  3 (3.00%) high mild
  3 (3.00%) high severe

deploy_code             time:   [19.817 us 19.874 us 19.942 us]
                        change: [-8.0172% -6.3597% -4.6664%] (p = 0.00 < 0.05)
                        Performance has improved.
```

# Test plan:
- new benches
- CI

### CODE REVIEW

**Comment by evgenykuzyakov** [comment]
@artob @frankbraun Can you take from there?

**Comment by artob** [comment]
@evgenykuzyakov Thanks, will test locally and review. (@frankbraun, if you have a chance, please pitch in as well.)

Should we perhaps start a new evm-precompile branch so that we can merge PRs actively (avoiding extra work for merge conflicts, etc)? I'm hesitant to merge directly to the master branch after review.

**Review by frankbraun — APPROVED** [review]

**Comment by frankbraun** [comment]
This looks good to me as an initial version. I sometimes get "Performance has improved" or "Performance has regressed" on my machine, but that's hopefully something that will subside as we add more tests.

@artob I would rather merge into master, the CI should ensure that's fine (given all checks pass, for course).

**Comment by artob** [comment]
As discussed on the sync call, changed this pull to target the [evm-phase2](https://github.com/near/nearcore/tree/evm-phase2) branch. (Currently synced with master.)

**Review by artob — APPROVED** [review]
LGTM :+1:

**Pull request merged**
