### PR TITLE
feat(build) Added set -eux to all steps of the CI pipeline

### PR DESCRIPTION
**Pull request by chefsale**
The approach of the pre-command hook doesn't work: https://github.com/near/nearcore/pull/4589#issuecomment-888492079

### CODE REVIEW

**Comment by matklad** [comment]
that's not pre-**commit** hook, right? That is ,there's typo in the title?

**Comment by chefsale** [comment]
Wow, good catch. I don't know how did I came up with the precommand name (wuuuut)😄

**Comment by chefsale** [comment]
Oh, no it is actually `precommand`based on the docs: https://buildkite.com/docs/agent/v3/hooks. That's why I forgot in the meantime @matklad

**Review by matklad — APPROVED** [review]

**Comment by chefsale** [comment]
It doesn't seem to work, as it runs in a seperate shell and has no affect on other steps. It seems like we will need to run this in every step. I will update the PR.

**Pull request merged**
