### PR TITLE
fix: Set DBCol::ReceiptIdToShardId in state sync and catchup

### PR DESCRIPTION
**Pull request by tayfunelmas**
This addresses the issue in #11605. This is temporary change, we will follow-up with removing ReceiptIdToShardId as it is not needed except for testing. It allows to re-enable GC in testloop.

For this we fix 2 problems (both manifest itself as testloop failures):
1) Call save_receipt_id_to_shard_id_for_block in 2 new paths in state sync (`set_state_finalize`) and catchup (`block_catch_up_postprocess`). This makes sure that ReceiptIdToShardId is saved whenever OutgoingReceipts are saved.
2) Only decrement refcount of ReceiptIdToShardId if it exists in GC. This is needed because when saving ReceiptIdToShardId we check if the validator cares about the shard, but when garbage collecting, we do not check shard-tracking info.

We will follow-up with another change to remove ReceiptIdToShardId from DB at all, since it is currently not used except for testing.

### CODE REVIEW

**Review by Longarithm — APPROVED** [review]
I thought for a while that we can save some receipts twice, but we are not, because each "apply result" will appear only once, interesting. It was scary because I sometimes saw our DB crashing because of "some key was written twice".

I would still slightly prefer not saving data at all, given we are not using it... but the logic seems correct, so LGTM.

**Comment by wacban** [comment]
> We will follow-up with another change to remove ReceiptIdToShardId from DB at all, since it is currently not used except for testing. 

Why not do that right away?

**Comment by tayfunelmas** [comment]
> > We will follow-up with another change to remove ReceiptIdToShardId from DB at all, since it is currently not used except for testing.
> 
> Why not do that right away?

I just had this PR ready when I discovered we could just delete the column. I will prepare the other PR and if it ends up quick, will scratch this one.

**Comment by tayfunelmas** [comment]
Closing this PR on behalf of https://github.com/near/nearcore/pull/11691.

**Pull request closed without merging**
