### PR TITLE
nightly: disable currently broken tests

### PR DESCRIPTION
**Pull request by mina86**
Those tests are consistently failing. Disable them and add to
the tracking Issue.

Issues: https://github.com/near/nearcore/issues/4618
Issue: https://github.com/near/nearcore/issues/5095

### CODE REVIEW

**Review by bowenwang1996 — APPROVED** [review]
`sanity/repro_2916.py` should not fail. @mzhangmzz could you take a look at this?

**Comment by mzhangmzz** [comment]
I fixed it in https://github.com/near/nearcore/pull/5154. 

I also noticed that the python version that nayduck uses is 3.9. Is that intentional? The reason why I asked is because the python version on my local machine was 3.7 and the test only failed with 3.9 not 3.7.

**Comment by bowenwang1996** [comment]
> I also noticed that the python version that nayduck uses is 3.9. Is that intentional? The reason why I asked is because the python version on my local machine was 3.7 and the test only failed with 3.9 not 3.7.

Interesting question. @mina86 what do you think?

**Comment by mina86** [comment]
> I also noticed that the python version that nayduck uses is 3.9. Is that intentional? The reason why I asked is because the python version on my local machine was 3.7 and the test only failed with 3.9 not 3.7.

Yes, for the most part. All of the code should run on 3.7 but it’s not unreasonable to expect that tests should pass on 3.9. My dev machine runs 3.9 and eventually people will update their Python version as well.

**Pull request merged**
