### PR TITLE
fix: fix nightly param estimator build

### LINKED ISSUE #4509: runtime-param-estimator doesn't build under nightly
https://buildkite.com/nearprotocol/nearcore-nightly-release/builds/451#fbf9530b-88db-4e2a-b9c2-87ec58d49488

### PR DESCRIPTION
**Pull request by matklad**
closes #4509

### CODE REVIEW

**Review by frol — APPROVED** [review]
I have zero context about evm support, so I can only confirm that the change itself is legit.

**Review by bowenwang1996 — APPROVED** [review]
I think this change makes sense, but not so sure about removing the evm feature completely. Let's wait for the Aurora team to comment on #4515

**Comment by matklad** [comment]
Actually, seems just the second commit is necessary and sufficient.

**Review by chefsale — APPROVED** [review]
:shipit: :shipit: :shipit: As the evm stuff got removed.

**Pull request merged**
