### PR TITLE
Refactor move css to common file

### PR DESCRIPTION
**Pull request by Rajiv620019**
I moved CSS to a separate file for the following files
```chain/jsonrpc/res/last_blocks.html```
```chain/jsonrpc/res/epoch_info.html```
```chain/jsonrpc/res/chain_n_chunk_info.html```
```chain/jsonrpc/res/sync.html```
```chain/jsonrpc/res/validator.html```

Issue id #7995

### CODE REVIEW

**Comment by akhi3030** [comment]
Thank you. very much for the change @Rajiv620019!

@pugachAG: the change looks good enough to me, I just wanted to have another set of eyes on it please.

**Comment by Rajiv620019** [comment]
Yeah sure thanks, I hope it gets merged.

**Review by pugachAG — APPROVED** [review]

**Comment by jakmeier** [comment]
Hi @Rajiv620019 could it be that this PR broke the debug page? I no longer get the CSS.

Screenshot from 2023-09-06 19-10-15

You can test this locally by running a localnet. The easiest way to do that is with nearup: https://github.com/near/nearup

If you compile nearcore locally like this: `cargo build --profile quick-release -p neard`

Then you can start a localnet using your binary like this: `nearup run localnet --binary-path target/quick-release/ --num-nodes 4 --num-shards 4`

**Comment by Rajiv620019** [comment]
Hey @jakmeier  definitely will fix it. While following the docs from the https://github.com/near/nearup 
When I run ```pip3 install --user nearup```
I'm getting this warning: 
"WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv"

Am I on the right track?

**Comment by pugachAG** [comment]
@Rajiv620019 @jakmeier I've published a PR to fix that: https://github.com/near/nearcore/pull/9497

**Comment by jakmeier** [comment]
@Rajiv620019 it looks like it was already fixed :)

But if you still want to try and run a localnet, yes you are on the right track. The pip warning is a python thing and not really related to nearup. It can usually be ignored and things are mostly fine in my experience.

But you can also enter a virtual env as recommended, and then install the package, which should get rid of the warning.

**Pull request merged**
