### PR TITLE
Fix for skip_epoch nayduck test

### PR DESCRIPTION
**Pull request by mm-near**
Fixed handling of the flat storage, when state sync has to download the genesis state for a single shard.

### CODE REVIEW

**Comment by mm-near** [comment]
Fixes #8413 8406

**Review by jakmeier — COMMENTED** [review]
This looks like a reasonable change to me. But I think @Longarithm should take a look as well, I don't remember the details of all storage creation state transition perfectly well.

**Comment by Longarithm** [comment]
Oof, I didn't realize before that in such case we sync to **pre-genesis state** which is empty.
But how does the node know about genesis state then? It should be written to disk somewhere during calling `Runtime::apply_genesis_state` and I think it happens only around `NightshadeRuntime` creation, which is already created during state sync.
So I even have doubts that the current code works for Trie. Did I get it correctly?

**Comment by mm-near** [comment]
@Longarithm - PTAL

**Review by Longarithm — APPROVED** [review]

**Pull request merged**
