### PR TITLE
Nayduck - broken tests cleanup

### PR DESCRIPTION
**Pull request by mm-near**
Taking care of 2 tests (as the goal is to get nayduck to green):
- massive state sync - it depends on the flat storage feature that is being worked on
- chunks recovered from others - the fix is also being worked on

### CODE REVIEW

**Comment by mm-near** [comment]
We should re-add these tests when #8322 is fixed (for massive state sync) and #8211 for partial chunks

**Review by Longarithm — CHANGES_REQUESTED** [review]
I think that rpc_finality.py makes sense. We probably should have e2e test checking that **final** account balance is different from **non-final** balance. Though implementation needs to be fixed:

* in our assertions all balances are the same and it doesn't make sense. I would expect smth like this, not sure what we expect from doomslug:
```
self.assertEqual(int(acc_no_finality['result']['amount']), acc0_balance - token_transfer)
self.assertEqual(int(acc_nfg_finality['result']['amount']), acc0_balance)
```
* we need to check that `acc0_balance` just decreases and `acc1_balance` just increases (?) - given that we were reworking our refund processing logic, exact balances may change here
* why we sleep for 1 second instead of checking that some liveness query to `node[2]` timeouts?

Let's maybe file separate issue to fix this test and comment it for now?

**Comment by mm-near** [comment]
you motivated me to fix it: #8411 ;-)

**Review by Longarithm — APPROVED** [review]

**Review by nikurt — COMMENTED** [review]
LGTM

**Pull request merged**
