### PR TITLE
fix: bump protocol version for ed25519 verify

### PR DESCRIPTION
**Pull request by jakmeier**
The protocol bump to 58 will be backported to release 1.31, the
new feature to verify ed25519 through a host function therefore needs
to be pushed to version 59.

### CODE REVIEW

**Comment by jakmeier** [comment]
I got a bit confused around the bump in #8360 and approved #8098 to be merged without a bump because I thought we already had one for the next release. But if I understand this right now, we need to put new features to version 59.

**Comment by jakmeier** [comment]
This is currently blocked on 
```
[2023-01-26 09:18:16] INFO: Got protocol 57 in mainnet release 1.30.0.
[2023-01-26 09:18:16] INFO: Got protocol 57 in testnet release 1.30.0-rc.6.
[2023-01-26 09:18:16] INFO: Got protocol 59 on master branch.
Traceback (most recent call last):
  File "tests/sanity/upgradable.py", line 194, in <module>
   main()
  File "tests/sanity/upgradable.py", line 189, in main
    test_protocol_versions()
  File "tests/sanity/upgradable.py", line 66, in test_protocol_versions
    assert ok, ('If changed, protocol version of a new release can increase by '
AssertionError: If changed, protocol version of a new release can increase by at most one.
🚨 Error: The command exited with status 1
```

Will need to come back once the testnet release with the bump is out.

**Comment by marcelo-gonzalez** [comment]
> This is currently blocked on
> 
> ```
> [2023-01-26 09:18:16] INFO: Got protocol 57 in mainnet release 1.30.0.
> [2023-01-26 09:18:16] INFO: Got protocol 57 in testnet release 1.30.0-rc.6.
> [2023-01-26 09:18:16] INFO: Got protocol 59 on master branch.
> Traceback (most recent call last):
>   File "tests/sanity/upgradable.py", line 194, in <module>
>    main()
>   File "tests/sanity/upgradable.py", line 189, in main
>     test_protocol_versions()
>   File "tests/sanity/upgradable.py", line 66, in test_protocol_versions
>     assert ok, ('If changed, protocol version of a new release can increase by '
> AssertionError: If changed, protocol version of a new release can increase by at most one.
> 🚨 Error: The command exited with status 1
> ```
> 
> Will need to come back once the testnet release with the bump is out.

Ah I had only prepared the new 1.31 branch on my fork but hadn't published it to nearcore yet. Although hmm `https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/latest_deploy` is still pointing to `1.30.0-rc.6` even though `1.30.1-rc.2` has already been published

**Review by marcelo-gonzalez — APPROVED** [review]

**Comment by jakmeier** [comment]
@nikurt hasn't 1.31.0-rc.3 with protocol version 58 been released on testnet? Somehow I am still seeing this error:

```
[2023-02-06 13:06:51] INFO: Got protocol 57 in mainnet release 1.30.0.
[2023-02-06 13:06:51] INFO: Got protocol 57 in testnet release 1.30.0-rc.6.
[2023-02-06 13:06:51] INFO: Got protocol 59 on master branch.
Traceback (most recent call last):
  File "tests/sanity/upgradable.py", line 194, in <module>
   main()
  File "tests/sanity/upgradable.py", line 189, in main
    test_protocol_versions()
  File "tests/sanity/upgradable.py", line 66, in test_protocol_versions
    assert ok, ('If changed, protocol version of a new release can increase by '
AssertionError: If changed, protocol version of a new release can increase by at most one.
🚨 Error: The command exited with status 1
```

https://buildkite.com/nearprotocol/nearcore/builds/24721#018626d3-0b87-4e75-adb8-6d4625a7ec22/95-680

**Comment by nikurt** [comment]
Yes, protocol version 58 was released:

```
% curl https://rpc.testnet.near.org/status -s | jq -r '[.version.build , .protocol_version]'
[
  "1.31.0-rc.4",
  58
]
```

**Comment by jakmeier** [comment]
@nikurt Ok I see, then it was released but somehow `upgradable.py` does not know it. The test looks at `https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/testnet/latest_deploy` to figure out what the latest release on testnet is and that still returns `Got protocol 57 in testnet release 1.30.0-rc.6.`. Both on buildkite and when I rerun locally.

Do you know how to updated that?

**Comment by nikurt** [comment]
> Do you know how to update that?

Reached out to @anshal-savla about that.

**Review by pompon0 — APPROVED** [review]

**Pull request merged**
