### PR TITLE
re:  Remove dead code from `scripts/test_nearlib.sh`

### LINKED ISSUE #5168: Potential dead code in the pipeline.yml?
This pipeline looks suspect to me:

https://github.com/near/nearcore/blob/5f9c98fd000566dfb024607acb4c95dcd914e90a/.buildkite/pipeline.yml#L67-L79

`nightly-2020-05-15 ` is very, very old, and definitely can't compile `nearcore`. Looking at the `test_nearlib.sh`, it looks like something not terribly reproducible, and chunks of the file are commented away. 

It seems like this is just a bit of bitrotted code. Do we understand what value is created by this test?

### PR DESCRIPTION
**Pull request by pmnoxx**
We have some dead code, that's not used in `scripts/test_nearlib.sh`.

from `.buildkite/pipeline.yml`:
```
      rustup default nightly-2020-05-15
      rustup target add wasm32-unknown-unknown
```

from`scripts/test_nearlib.sh`.

```
export RUST_BACKTRACE=full
# ./scripts/start_unittest.py --local &
export NEAR_PID=$!
trap 'pkill -15 -P $NEAR_PID' 0

../scripts/waitonserver.sh
```

Closes #5168

### CODE REVIEW

**Comment by pmnoxx** [comment]
I'm checking whenever `yarn test` still works.

I'll disable it after CI runs.

**Review by mina86 — APPROVED** [review]

**Comment by pmnoxx** [comment]
Fails due to https://github.com/near/nearcore/pull/5822

**Comment by pmnoxx** [comment]
I confirmed, that those 2 lines aren't used.

**Review by matklad — APPROVED** [review]

**Comment by pmnoxx** [comment]
```
@chefsale: /.buildkite/
```
@chefsale Can you take a look?

**Comment by pmnoxx** [comment]
```
@chefsale @mhalambek: .buildkite/
```
@chefsale @mhalambek Can you take a look?

**Comment by bowenwang1996** [comment]
@chefsale @mhalambek could you review this PR?

**Comment by pmnoxx** [comment]
```
@chefsale @mhalambek: .buildkite/
```
@chefsale @mhalambek Can you take a look?

**Review by rtsai123 — APPROVED** [review]

**Pull request merged**
