### PR TITLE
refactor(pytest): Update sanity/transactions.py test to pass according to dropped routing in handle_query ViewClient method

### PR DESCRIPTION
**Pull request by khorolets**
In merged PR #3944 I've dropped routing for the `Query` handler in ViewClient (@frol and @bowenwang1996 discussed it and approved this change).

After that test `pytest/tests/sanity/transactions.py` started failing. @frol and I investigated it and found out that the fails related to the attempts to test transactions between shards, all the test relies on the querying jsonrpc `query` method to get accounts from different shards and check their balances, but since routing is not present there anymore it's impossible to do it.

In this PR I've made the smallest change introducing only one shard and all the accounts on that shard so the test is not failing anymore, but I'm not sure if it not brakes the main idea of the test.

@bowenwang1996 @SkidanovAlex could you assist in refactoring this test so it could still be useful by checking what it supposed to be checking, please?

### CODE REVIEW

**Comment by khorolets** [comment]
@mikhailOK I think you might want to follow this, I see you are fixing some tests maybe you have some knowledge to help here?

**Review by bowenwang1996 — COMMENTED** [review]
The number of shards should not change. You can add an observer node that tracks all shards and do rpc query from it. I can do this if needed

**Comment by khorolets** [comment]
> The number of shards should not change. You can add an observer node that tracks all shards and do rpc query from it. I can do this if needed

Would be very helpful as I don't know what to do :(

**Review by frol — APPROVED** [review]

**Comment by bowenwang1996** [comment]
30 runs all pass http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1348

**Review by bowenwang1996 — APPROVED** [review]

**Pull request merged**
