### PR TITLE
chore: Add metrics that shows the current height of approvals

### LINKED ISSUE #7846: Add metric that shows the current height of approvals
We should export the current 'approval height' that given node is sending (currently this data is available only on the Validator debug page)

### PR DESCRIPTION
**Pull request by kostekIV**
fixes #7846
I have labelled this as chore, but I am not sure if it is an appropriate label.

### CODE REVIEW

**Comment by nikurt** [comment]
Thank you @kostekIV for picking up that issue!
Do you know why shouldn't we export `largest_final_height`? Would it be the same as `last_final_block_height` (in `info.rs`)?
I'd prefer to also export `largest_final_height` for completeness.

The code in the PR is fine.
My only suggestion is to replace assignments with setter methods. That way, we'll never forget to update the metrics when the values are changed.

**Comment by kostekIV** [comment]
So I have ended up adding `TrackableBlockHeightValue` which guards values and sets appropriate gauge on every change to the inner value. It may be overkill tho. Added also `largest_final_height`. Should I also mention somewhere new metrics?

**Review by nikurt — APPROVED** [review]
Thank you, looks good!

**Comment by nikurt** [comment]
The setters interface looks good.
> mention new metrics

Please add a line to non-protocol changes in `CHANGELOG.md`, and then I'll press the "merge" the PR.

**Pull request merged**
