### PR TITLE
feat(zero storage) Set storage costs to zero

### PR DESCRIPTION
**Pull request by mhalambek**
Set storage costs to zero for all protocol versions, this way, this change will not pollute existing tools
while supporting future protocol upgrades of nearcore.

### CODE REVIEW

**Comment by mhalambek** [comment]
This would address issues mentioned in https://github.com/near/nearcore/issues/8140
Until we figure out a better way of handling this kinds of chain specific runtime parameter checks

**Comment by bowenwang1996** [comment]
What is the status of this PR?

**Comment by akhi3030** [comment]
@jakmeier: based on the previous conversations, would you be the right person to help review this PR?

**Review by jakmeier — APPROVED** [review]
look good to me but I think someone from the node team should take a look as well

**Comment by akhi3030** [comment]
- Adding the `T-Node` label 
- Pinging @gmilescu and @posvyatokum to see if they can help figure out who from the node team can do a review.

**Comment by chefsale** [comment]
Ping on review of this and landing. @mhalambek @bowenwang1996 @akhi3030 @gmilescu @posvyatokum

**Review by nikurt — APPROVED** [review]
Looks good. I assume this feature doesn't get enabled for mainnet or testnet.

**Comment by mhalambek** [comment]
> Looks good. I assume this feature doesn't get enabled for mainnet or testnet.

You need to compile manually and pass the flag, it does not affect mainnet or testnet.
Could you merge this one then.

**Comment by akhi3030** [comment]
Thank you @jakmeier and @nikurt for your reviews.  I'll apply the merge label.

**Comment by akhi3030** [comment]
I think this branch needs to be rebased [or the master merged in].  The bot is unable to make progress.

**Pull request merged**
