### PR TITLE
test: Remove old runtime config tests

### PR DESCRIPTION
**Pull request by jakmeier**
Now that the new runtime config format has been merged, we can get rid
of the old JSON files that were kept to ensure the new format remains
compatible.

Use insta snapshot testing to verifythat the JSON representation is not
changed unexpectedly. This also replaces the hash comparison that needed
to be updated manually after every change.

### CODE REVIEW

**Comment by matklad** [comment]
Nice, one thing I worried about with diffs is that we don't see actual config anywhere, but now I realise that snapsots are that! 

This also makes me thing that maybe we should write diffs in the *opposite* direction? That is, we have a full, *current* configuration, and diffs specify past configs? Probably isn't worth it to implement, but a fun idea non the less!

**Review by matklad — APPROVED** [review]
LGTM, but there are some warnings

**Comment by jakmeier** [comment]
> This also makes me thing that maybe we should write diffs in the _opposite_ direction? That is, we have a full, _current_ configuration, and diffs specify past configs? Probably isn't worth it to implement, but a fun idea non the less!

Interesting thought indeed :) I wish I did it that way initially but now it's not really worth it to change.

**Comment by jakmeier** [comment]
@matklad Please check again for my latest commit. I previously didn't think about nightly tests, those actually need separate snapshots. This is because now we are checking *effective* JSONs, after applying default values and other logic hidden in code. Before we were only checking the input files, which were the same for stable and nightly.

The change in what we test was intentional. And I think the new approach is strictly better. Now we check what we really care for, which is more strict in some cases like the difference between nightly/stable. And in other cases, like changing a comment in the source file, we are now less strict and would not break tests.

But it is worth pointing out that we have different effective configurations for the same protocol version in stable vs nightly. That seemed suspect to me at first but now I think that's actually right. We _do_ make changes to the runtime configuration structure that also touches older versions. (With the necessary care to ensure behaviour is equivalent.)

If you disagree, please veto. Otherwise I will merge this as it is.

**Review by matklad — APPROVED** [review]

**Comment by jakmeier** [comment]
I see, yes, not testing at all on nightly makes much more sense here.

**Pull request merged**
