### PR TITLE
Use IO operations in actual cost computations.

### PR DESCRIPTION
**Pull request by olonho**

### CODE REVIEW

**Comment by olonho** [comment]
New costs 
```
RuntimeConfig {
    storage_amount_per_byte: 90900000000000000000,
    transaction_costs: RuntimeFeesConfig {
        action_receipt_creation_config: Fee {
            send_sir: 171119625000,
            send_not_sir: 171119625000,
            execution: 171119625000,
        },
        data_receipt_creation_config: DataReceiptCreationConfig {
            base_cost: Fee {
                send_sir: 50131672828937,
                send_not_sir: 50131672828937,
                execution: 50131672828937,
            },
            cost_per_byte: Fee {
                send_sir: 14423164,
                send_not_sir: 14423164,
                execution: 14423164,
            },
        },
        action_creation_config: ActionCreationConfig {
            create_account_cost: Fee {
                send_sir: 39563250000,
                send_not_sir: 39563250000,
                execution: 39563250000,
            },
            deploy_contract_cost: Fee {
                send_sir: 53485187500,
                send_not_sir: 53485187500,
                execution: 53485187500,
            },
            deploy_contract_cost_per_byte: Fee {
                send_sir: 6766384,
                send_not_sir: 6766384,
                execution: 6766384,
            },
            function_call_cost: Fee {
                send_sir: 252159250000,
                send_not_sir: 252159250000,
                execution: 252159250000,
            },
            function_call_cost_per_byte: Fee {
                send_sir: 28284,
                send_not_sir: 28284,
                execution: 28284,
            },
            transfer_cost: Fee {
                send_sir: 35414312500,
                send_not_sir: 35414312500,
                execution: 35414312500,
            },
            stake_cost: Fee {
                send_sir: 62222000000,
                send_not_sir: 62222000000,
                execution: 62222000000,
            },
            add_key_cost: AccessKeyCreationConfig {
                full_access_cost: Fee {
                    send_sir: 36425687500,
                    send_not_sir: 36425687500,
                    execution: 36425687500,
                },
                function_call_cost: Fee {
                    send_sir: 39283437500,
                    send_not_sir: 39283437500,
                    execution: 39283437500,
                },
                function_call_cost_per_byte: Fee {
                    send_sir: 8292375,
                    send_not_sir: 8292375,
                    execution: 8292375,
                },
            },
            delete_key_cost: Fee {
                send_sir: 20098000000,
                send_not_sir: 20098000000,
                execution: 20098000000,
            },
            delete_account_cost: Fee {
                send_sir: 133446375000,
                send_not_sir: 133446375000,
                execution: 133446375000,
            },
        },
        storage_usage_config: StorageUsageConfig {
            num_bytes_account: 100,
            num_extra_bytes_record: 40,
        },
        burnt_gas_reward: Ratio {
            numer: 3,
            denom: 10,
        },
        pessimistic_gas_price_inflation_ratio: Ratio {
            numer: 103,
            denom: 100,
        },
    },
    wasm_config: VMConfig {
        ext_costs: ExtCostsConfig {
            base: 84957084,
            contract_compile_base: 52453075000,
            contract_compile_bytes: 385248335,
            read_memory_base: 248389912,
            read_memory_byte: 1267000,
            write_memory_base: 315607937,
            write_memory_byte: 907819,
            read_register_base: 215901400,
            read_register_byte: 32287,
            write_register_base: 338647700,
            write_register_byte: 1267087,
            utf8_decoding_base: 426204450,
            utf8_decoding_byte: 102031338,
            utf16_decoding_base: 568447087,
            utf16_decoding_byte: 57031762,
            sha256_base: 907602412,
            sha256_byte: 8011628,
            keccak256_base: 1336808262,
            keccak256_byte: 7088969,
            keccak512_base: 1328104637,
            keccak512_byte: 12150327,
            log_base: 568447087,
            log_byte: 4368762,
            storage_write_base: 22419989500,
            storage_write_key_byte: 26868159,
            storage_write_value_byte: 13378974,
            storage_write_evicted_byte: 33493165,
            storage_read_base: 22822318750,
            storage_read_key_byte: 10858142,
            storage_read_value_byte: 4595621241,
            storage_remove_base: 18641964500,
            storage_remove_key_byte: 12995906,
            storage_remove_ret_value_byte: 6240673795,
            storage_has_key_base: 22053963000,
            storage_has_key_byte: 10660285,
            storage_iter_create_prefix_base: 0,
            storage_iter_create_prefix_byte: 0,
            storage_iter_create_range_base: 0,
            storage_iter_create_from_byte: 0,
            storage_iter_create_to_byte: 0,
            storage_iter_next_base: 0,
            storage_iter_next_key_byte: 0,
            storage_iter_next_value_byte: 0,
            touching_trie_node: 6520662500,
            promise_and_base: 5141701043,
            promise_and_per_promise: 42710136,
            promise_return: 4506499920,
            validator_stake_base: 303944908800,
            validator_total_stake_base: 303944908800,
        },
        grow_mem_cost: 1,
        regular_op_cost: 1165011,
        limit_config: VMLimitConfig {
            max_gas_burnt: 200000000000000,
            max_gas_burnt_view: 200000000000000,
            max_stack_height: 16384,
            initial_memory_pages: 1024,
            max_memory_pages: 2048,
            registers_memory_limit: 1073741824,
            max_register_size: 104857600,
            max_number_registers: 100,
            max_number_logs: 100,
            max_total_log_length: 16384,
            max_total_prepaid_gas: 300000000000000,
            max_actions_per_receipt: 100,
            max_number_bytes_method_names: 2000,
            max_length_method_name: 256,
            max_arguments_length: 4194304,
            max_length_returned_data: 4194304,
            max_contract_size: 4194304,
            max_length_storage_key: 4194304,
            max_length_storage_value: 4194304,
            max_promises_per_function_call_action: 1024,
            max_number_input_data_dependencies: 128,
        },
    },
    account_creation_config: AccountCreationConfig {
        min_allowed_top_level_account_length: 0,
        registrar_account_id: "registrar",
    },
}
```

**Comment by evgenykuzyakov** [comment]
We'll need to disable cache and increase the number of base accounts to get proper config.

Also dependency:
```
data_receipt_creation_config: DataReceiptCreationConfig {
            base_cost: Fee {
                send_sir: 50131672828937,
                send_not_sir: 50131672828937,
                execution: 50131672828937,
            },
```
Looks a bit off. Why it requires 100Tgas for this action?

**Comment by olonho** [comment]
Same tree, but not taking IO into account:
```
RuntimeConfig {
    storage_amount_per_byte: 90900000000000000000,
    transaction_costs: RuntimeFeesConfig {
        action_receipt_creation_config: Fee {
            send_sir: 166752437500,
            send_not_sir: 166752437500,
            execution: 166752437500,
        },
        data_receipt_creation_config: DataReceiptCreationConfig {
            base_cost: Fee {
                send_sir: 285571501250,
                send_not_sir: 285571501250,
                execution: 285571501250,
            },
            cost_per_byte: Fee {
                send_sir: 13675998,
                send_not_sir: 13675998,
                execution: 13675998,
            },
        },
        action_creation_config: ActionCreationConfig {
            create_account_cost: Fee {
                send_sir: 25404687500,
                send_not_sir: 25404687500,
                execution: 25404687500,
            },
            deploy_contract_cost: Fee {
                send_sir: 42459500000,
                send_not_sir: 42459500000,
                execution: 42459500000,
            },
            deploy_contract_cost_per_byte: Fee {
                send_sir: 6740321,
                send_not_sir: 6740321,
                execution: 6740321,
            },
            function_call_cost: Fee {
                send_sir: 252371437500,
                send_not_sir: 252371437500,
                execution: 252371437500,
            },
            function_call_cost_per_byte: Fee {
                send_sir: 27969,
                send_not_sir: 27969,
                execution: 27969,
            },
            transfer_cost: Fee {
                send_sir: 25558437500,
                send_not_sir: 25558437500,
                execution: 25558437500,
            },
            stake_cost: Fee {
                send_sir: 58631187500,
                send_not_sir: 58631187500,
                execution: 58631187500,
            },
            add_key_cost: AccessKeyCreationConfig {
                full_access_cost: Fee {
                    send_sir: 30311750000,
                    send_not_sir: 30311750000,
                    execution: 30311750000,
                },
                function_call_cost: Fee {
                    send_sir: 33521875000,
                    send_not_sir: 33521875000,
                    execution: 33521875000,
                },
                function_call_cost_per_byte: Fee {
                    send_sir: 8329018,
                    send_not_sir: 8329018,
                    execution: 8329018,
                },
            },
            delete_key_cost: Fee {
                send_sir: 12515500000,
                send_not_sir: 12515500000,
                execution: 12515500000,
            },
            delete_account_cost: Fee {
                send_sir: 119057625000,
                send_not_sir: 119057625000,
                execution: 119057625000,
            },
        },
        storage_usage_config: StorageUsageConfig {
            num_bytes_account: 100,
            num_extra_bytes_record: 40,
        },
        burnt_gas_reward: Ratio {
            numer: 3,
            denom: 10,
        },
        pessimistic_gas_price_inflation_ratio: Ratio {
            numer: 103,
            denom: 100,
        },
    },
    wasm_config: VMConfig {
        ext_costs: ExtCostsConfig {
            base: 84969734,
            contract_compile_base: 52412400000,
            contract_compile_bytes: 385267671,
            read_memory_base: 249527062,
            read_memory_byte: 1266946,
            write_memory_base: 317102887,
            write_memory_byte: 907631,
            read_register_base: 217424550,
            read_register_byte: 32421,
            write_register_base: 339922625,
            write_register_byte: 1267032,
            utf8_decoding_base: 427794212,
            utf8_decoding_byte: 102033119,
            utf16_decoding_base: 569729062,
            utf16_decoding_byte: 57053312,
            sha256_base: 908684800,
            sha256_byte: 8012205,
            keccak256_base: 1337606075,
            keccak256_byte: 7089495,
            keccak512_base: 1328943087,
            keccak512_byte: 12164600,
            log_base: 569729062,
            log_byte: 4368937,
            storage_write_base: 20809168000,
            storage_write_key_byte: 23631040,
            storage_write_value_byte: 10475340,
            storage_write_evicted_byte: 21159277,
            storage_read_base: 22360430125,
            storage_read_key_byte: 10854859,
            storage_read_value_byte: 26024292,
            storage_remove_base: 18644176500,
            storage_remove_key_byte: 12958778,
            storage_remove_ret_value_byte: 36512316,
            storage_has_key_base: 20565532125,
            storage_has_key_byte: 10716533,
            storage_iter_create_prefix_base: 0,
            storage_iter_create_prefix_byte: 0,
            storage_iter_create_range_base: 0,
            storage_iter_create_from_byte: 0,
            storage_iter_create_to_byte: 0,
            storage_iter_next_base: 0,
            storage_iter_next_key_byte: 0,
            storage_iter_next_value_byte: 0,
            touching_trie_node: 6388694321,
            promise_and_base: 461436033,
            promise_and_per_promise: 2032322,
            promise_return: 150651467,
            validator_stake_base: 303944908800,
            validator_total_stake_base: 303944908800,
        },
        grow_mem_cost: 1,
        regular_op_cost: 1158754,
        limit_config: VMLimitConfig {
            max_gas_burnt: 200000000000000,
            max_gas_burnt_view: 200000000000000,
            max_stack_height: 16384,
            initial_memory_pages: 1024,
            max_memory_pages: 2048,
            registers_memory_limit: 1073741824,
            max_register_size: 104857600,
            max_number_registers: 100,
            max_number_logs: 100,
            max_total_log_length: 16384,
            max_total_prepaid_gas: 300000000000000,
            max_actions_per_receipt: 100,
            max_number_bytes_method_names: 2000,
            max_length_method_name: 256,
            max_arguments_length: 4194304,
            max_length_returned_data: 4194304,
            max_contract_size: 4194304,
            max_length_storage_key: 4194304,
            max_length_storage_value: 4194304,
            max_promises_per_function_call_action: 1024,
            max_number_input_data_dependencies: 128,
        },
    },
    account_creation_config: AccountCreationConfig {
        min_allowed_top_level_account_length: 0,
        registrar_account_id: "registrar",
    },
}```

**Comment by olonho** [comment]
Cost comparison:

```
storage_amount_per_byte: first=90900000000000000000 second=90900000000000000000 second/first=1.00
action_receipt_creation_config: send_sir: first=166752437500 second=171119625000 second/first=1.03
action_receipt_creation_config: send_not_sir: first=166752437500 second=171119625000 second/first=1.03
action_receipt_creation_config: execution: first=166752437500 second=171119625000 second/first=1.03
base_cost: send_sir: first=285571501250 second=50131672828937 second/first=175.55
base_cost: send_not_sir: first=285571501250 second=50131672828937 second/first=175.55
base_cost: execution: first=285571501250 second=50131672828937 second/first=175.55
cost_per_byte: send_sir: first=13675998 second=14423164 second/first=1.05
cost_per_byte: send_not_sir: first=13675998 second=14423164 second/first=1.05
cost_per_byte: execution: first=13675998 second=14423164 second/first=1.05
create_account_cost: send_sir: first=25404687500 second=39563250000 second/first=1.56
create_account_cost: send_not_sir: first=25404687500 second=39563250000 second/first=1.56
create_account_cost: execution: first=25404687500 second=39563250000 second/first=1.56
deploy_contract_cost: send_sir: first=42459500000 second=53485187500 second/first=1.26
deploy_contract_cost: send_not_sir: first=42459500000 second=53485187500 second/first=1.26
deploy_contract_cost: execution: first=42459500000 second=53485187500 second/first=1.26
deploy_contract_cost_per_byte: send_sir: first=6740321 second=6766384 second/first=1.00
deploy_contract_cost_per_byte: send_not_sir: first=6740321 second=6766384 second/first=1.00
deploy_contract_cost_per_byte: execution: first=6740321 second=6766384 second/first=1.00
function_call_cost: send_sir: first=33521875000 second=39283437500 second/first=1.17
function_call_cost: send_not_sir: first=33521875000 second=39283437500 second/first=1.17
function_call_cost: execution: first=33521875000 second=39283437500 second/first=1.17
function_call_cost_per_byte: send_sir: first=8329018 second=8292375 second/first=1.00
function_call_cost_per_byte: send_not_sir: first=8329018 second=8292375 second/first=1.00
function_call_cost_per_byte: execution: first=8329018 second=8292375 second/first=1.00
transfer_cost: send_sir: first=25558437500 second=35414312500 second/first=1.39
transfer_cost: send_not_sir: first=25558437500 second=35414312500 second/first=1.39
transfer_cost: execution: first=25558437500 second=35414312500 second/first=1.39
stake_cost: send_sir: first=58631187500 second=62222000000 second/first=1.06
stake_cost: send_not_sir: first=58631187500 second=62222000000 second/first=1.06
stake_cost: execution: first=58631187500 second=62222000000 second/first=1.06
full_access_cost: send_sir: first=30311750000 second=36425687500 second/first=1.20
full_access_cost: send_not_sir: first=30311750000 second=36425687500 second/first=1.20
full_access_cost: execution: first=30311750000 second=36425687500 second/first=1.20
delete_key_cost: send_sir: first=12515500000 second=20098000000 second/first=1.61
delete_key_cost: send_not_sir: first=12515500000 second=20098000000 second/first=1.61
delete_key_cost: execution: first=12515500000 second=20098000000 second/first=1.61
delete_account_cost: send_sir: first=119057625000 second=133446375000 second/first=1.12
delete_account_cost: send_not_sir: first=119057625000 second=133446375000 second/first=1.12
delete_account_cost: execution: first=119057625000 second=133446375000 second/first=1.12
storage_usage_config: num_bytes_account: first=100 second=100 second/first=1.00
storage_usage_config: num_extra_bytes_record: first=40 second=40 second/first=1.00
burnt_gas_reward: numer: first=3 second=3 second/first=1.00
burnt_gas_reward: denom: first=10 second=10 second/first=1.00
pessimistic_gas_price_inflation_ratio: numer: first=103 second=103 second/first=1.00
pessimistic_gas_price_inflation_ratio: denom: first=100 second=100 second/first=1.00
ext_costs: base: first=84969734 second=84957084 second/first=1.00
ext_costs: contract_compile_base: first=52412400000 second=52453075000 second/first=1.00
ext_costs: contract_compile_bytes: first=385267671 second=385248335 second/first=1.00
ext_costs: read_memory_base: first=249527062 second=248389912 second/first=1.00
ext_costs: read_memory_byte: first=1266946 second=1267000 second/first=1.00
ext_costs: write_memory_base: first=317102887 second=315607937 second/first=1.00
ext_costs: write_memory_byte: first=907631 second=907819 second/first=1.00
ext_costs: read_register_base: first=217424550 second=215901400 second/first=0.99
ext_costs: read_register_byte: first=32421 second=32287 second/first=1.00
ext_costs: write_register_base: first=339922625 second=338647700 second/first=1.00
ext_costs: write_register_byte: first=1267032 second=1267087 second/first=1.00
ext_costs: utf8_decoding_base: first=427794212 second=426204450 second/first=1.00
ext_costs: utf8_decoding_byte: first=102033119 second=102031338 second/first=1.00
ext_costs: utf16_decoding_base: first=569729062 second=568447087 second/first=1.00
ext_costs: utf16_decoding_byte: first=57053312 second=57031762 second/first=1.00
ext_costs: sha256_base: first=908684800 second=907602412 second/first=1.00
ext_costs: sha256_byte: first=8012205 second=8011628 second/first=1.00
ext_costs: keccak256_base: first=1337606075 second=1336808262 second/first=1.00
ext_costs: keccak256_byte: first=7089495 second=7088969 second/first=1.00
ext_costs: keccak512_base: first=1328943087 second=1328104637 second/first=1.00
ext_costs: keccak512_byte: first=12164600 second=12150327 second/first=1.00
ext_costs: log_base: first=569729062 second=568447087 second/first=1.00
ext_costs: log_byte: first=4368937 second=4368762 second/first=1.00
ext_costs: storage_write_base: first=20809168000 second=22419989500 second/first=1.08
ext_costs: storage_write_key_byte: first=23631040 second=26868159 second/first=1.14
ext_costs: storage_write_value_byte: first=10475340 second=13378974 second/first=1.28
ext_costs: storage_write_evicted_byte: first=21159277 second=33493165 second/first=1.58
ext_costs: storage_read_base: first=22360430125 second=22822318750 second/first=1.02
ext_costs: storage_read_key_byte: first=10854859 second=10858142 second/first=1.00
ext_costs: storage_read_value_byte: first=26024292 second=4595621241 second/first=176.59
ext_costs: storage_remove_base: first=18644176500 second=18641964500 second/first=1.00
ext_costs: storage_remove_key_byte: first=12958778 second=12995906 second/first=1.00
ext_costs: storage_remove_ret_value_byte: first=36512316 second=6240673795 second/first=170.92
ext_costs: storage_has_key_base: first=20565532125 second=22053963000 second/first=1.07
ext_costs: storage_has_key_byte: first=10716533 second=10660285 second/first=0.99
ext_costs: storage_iter_create_prefix_base: first=0 second=0 second/first=n/a
ext_costs: storage_iter_create_prefix_byte: first=0 second=0 second/first=n/a
ext_costs: storage_iter_create_range_base: first=0 second=0 second/first=n/a
ext_costs: storage_iter_create_from_byte: first=0 second=0 second/first=n/a
ext_costs: storage_iter_create_to_byte: first=0 second=0 second/first=n/a
ext_costs: storage_iter_next_base: first=0 second=0 second/first=n/a
ext_costs: storage_iter_next_key_byte: first=0 second=0 second/first=n/a
ext_costs: storage_iter_next_value_byte: first=0 second=0 second/first=n/a
ext_costs: touching_trie_node: first=6388694321 second=6520662500 second/first=1.02
ext_costs: promise_and_base: first=461436033 second=5141701043 second/first=11.14
ext_costs: promise_and_per_promise: first=2032322 second=42710136 second/first=21.02
ext_costs: promise_return: first=150651467 second=4506499920 second/first=29.91
ext_costs: validator_stake_base: first=303944908800 second=303944908800 second/first=1.00
ext_costs: validator_total_stake_base: first=303944908800 second=303944908800 second/first=1.00
ext_costs: grow_mem_cost: first=1 second=1 second/first=1.00
ext_costs: regular_op_cost: first=1158754 second=1165011 second/first=1.01
limit_config: max_gas_burnt: first=200000000000000 second=200000000000000 second/first=1.00
limit_config: max_gas_burnt_view: first=200000000000000 second=200000000000000 second/first=1.00
limit_config: max_stack_height: first=16384 second=16384 second/first=1.00
limit_config: initial_memory_pages: first=1024 second=1024 second/first=1.00
limit_config: max_memory_pages: first=2048 second=2048 second/first=1.00
limit_config: registers_memory_limit: first=1073741824 second=1073741824 second/first=1.00
limit_config: max_register_size: first=104857600 second=104857600 second/first=1.00
limit_config: max_number_registers: first=100 second=100 second/first=1.00
limit_config: max_number_logs: first=100 second=100 second/first=1.00
limit_config: max_total_log_length: first=16384 second=16384 second/first=1.00
limit_config: max_total_prepaid_gas: first=300000000000000 second=300000000000000 second/first=1.00
limit_config: max_actions_per_receipt: first=100 second=100 second/first=1.00
limit_config: max_number_bytes_method_names: first=2000 second=2000 second/first=1.00
limit_config: max_length_method_name: first=256 second=256 second/first=1.00
limit_config: max_arguments_length: first=4194304 second=4194304 second/first=1.00
limit_config: max_length_returned_data: first=4194304 second=4194304 second/first=1.00
limit_config: max_contract_size: first=4194304 second=4194304 second/first=1.00
limit_config: max_length_storage_key: first=4194304 second=4194304 second/first=1.00
limit_config: max_length_storage_value: first=4194304 second=4194304 second/first=1.00
limit_config: max_promises_per_function_call_action: first=1024 second=1024 second/first=1.00
limit_config: max_number_input_data_dependencies: first=128 second=128 second/first=1.00
account_creation_config: min_allowed_top_level_account_length: first=0 second=0 second/first=n/a

```

All costs change in meaningful way, with an exception of those:

```
base_cost: send_sir: first=285571501250 second=50131672828937 second/first=175.55
base_cost: send_not_sir: first=285571501250 second=50131672828937 second/first=175.55
base_cost: execution: first=285571501250 second=50131672828937 second/first=175.55
ext_costs: promise_and_base: first=461436033 second=5141701043 second/first=11.14
ext_costs: promise_and_per_promise: first=2032322 second=42710136 second/first=21.02
ext_costs: promise_return: first=150651467 second=4506499920 second/first=29.91
ext_costs: storage_read_value_byte: first=26024292 second=4595621241 second/first=176.59
ext_costs: storage_remove_ret_value_byte: first=36512316 second=6240673795 second/first=170.92
ext_costs: promise_and_base: first=461436033 second=5141701043 second/first=11.14
ext_costs: promise_and_per_promise: first=2032322 second=42710136 second/first=21.02
ext_costs: promise_return: first=150651467 second=4506499920 second/first=29.91
```
@evgenykuzyakov @bowenwang1996 what do you think of reasons for that?

**Comment by evgenykuzyakov** [comment]
Take a look at https://github.com/near/nearcore/pull/3505#issuecomment-742823232

**Pull request closed without merging**
