### PR TITLE
test(stateless_validation) - Added tests with missing blocks

### PR DESCRIPTION
**Pull request by wacban**
Enhanced the `run_chunk_validation_test` test helper with ability to drop blocks with given probability and added a few tests that have both missing chunks and missing blocks.

### CODE REVIEW

**Comment by Longarithm** [comment]
Did / can we check that if we disable some logic responsible for handling missing blocks, something fails?
This can also be an expected outcome of some test.

**Comment by wacban** [comment]
> Did / can we check that if we disable some logic responsible for handling missing blocks, something fails? This can also be an expected outcome of some test.

Is there any particular logic that you think would be worth checking here? I'll try to come up with something and share results here but any ideas are welcome.

**Comment by Longarithm** [comment]
I didn't have specific ideas in mind, I just wanted to verify that new tests actually cause more code lines to be tested.

When I think about it, skipping particular blocks only checks that consensus is able to skip blocks. It becomes more challenging for nearcore when blocks are sent to arbitrary subset of receivers (though it should be > 2/3 of block producers most of the time), or sent with arbitrary delays - this is what can be tested in testloop.
In such case I'm still not sure how to check that chain actually had troubles and overcame them. Maybe check that 
* some client has blocks which didn't end up in canonical chain
* some state witness / endorsement cache has leftovers related to such block?..

**Comment by wacban** [comment]
I tried making the following pieces of logic faulty in such a way that it is only visible when there are missing blocks and I confirmed that the test fails:
* Set the block ordinal to `block.height - prev_block.height + prev_block.ordinal` in block production.
* Set the `last_ds_final_block` to prev_hash in block production. 
 
I also adjusted the logic to send chunk endorsements only to the next block producer and I checked that there are no chunks in blocks immediately after a missed block. `NUM_NEXT_BLOCK_PRODUCERS_TO_SEND_CHUNK_ENDORSEMENT = 1`

**Review by Longarithm — APPROVED** [review]
Nice!

**Review by pugachAG — APPROVED** [review]

**Pull request merged**
