### PR TITLE
feat(build): Added CARGO_PROFILE_RELEASE_DEBUG=true to nightly and pe…

### PR DESCRIPTION
**Pull request by chefsale**
…rf releases

### CODE REVIEW

**Comment by matklad** [comment]
LGTM. Note that `debug = true` implies full debug info, which weighs a lot. *If* this is a concern, `debug = 1` (include only line number info) might be an interesting middleground.

**Comment by chefsale** [comment]
cc: @frol and @bowenwang1996  on the debug=1 or debug=true, which makes more sense to you guys?

**Comment by chefsale** [comment]
cc: @frol and @bowenwang1996 on the debug=true or debug=1, whatever works for you?

**Review by bowenwang1996 — COMMENTED** [review]
Probably better to go with `debug=true` since @pmnoxx also needs it

**Comment by frol** [comment]
@chefsale I had just checked the release binary that was produced by the latest CI and it appears to be 29M in size, which means that it does not have the debug symbols: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/Linux/master/774632825d69f1928b0e7707ebcda42fc1673951/neard

image

**Comment by chefsale** [comment]
That is expected, this is the normal stable release without debug, the one with debug is under perf release folder: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/Linux/master/774632825d69f1928b0e7707ebcda42fc1673951/perf/neard with size of 440MB.

**Comment by frol** [comment]
@chefsale Ouch, I misread the PR. Sorry for the false alarm

**Pull request merged**
