### PR TITLE
nit: always show full output in run_clippy.sh

### PR DESCRIPTION
**Pull request by wacban**
I like to see the output of clippy when it's working. Passing --no-capture to enable that.

### CODE REVIEW

**Review by nagisa — APPROVED** [review]

**Comment by nagisa** [comment]
Ah… its unfortunate but you won’t be able to modify the scripts easily T_T

**Comment by wacban** [comment]
> Ah… its unfortunate but you won’t be able to modify the scripts easily T_T

@nagisa How do I modify the scripts hardily? :)

**Comment by nagisa** [comment]
Um... I’m going to exclude this PR from being considered from this job with my buildkite superpowers when I’m around the Mac.

**Comment by nagisa** [comment]
Try rebasing the branch? :)

**Review by nikurt — APPROVED** [review]

**Comment by wacban** [comment]
@nagisa This PR passes the checks in the PR stage but fails when in merge queue. Any advice?

**Comment by nagisa** [comment]
Looks like we’ll have to disable the check outright, if momentarily, for the merge… which is probably something we shouldn’t do on a weekday :)

**Pull request merged**
