### PR TITLE
test-utils: remove kind of pointless encode_int function

### PR DESCRIPTION
**Pull request by mina86**
The function is used in only one place and really it’s more readable
to just use i32::to_le_bytes.

### CODE REVIEW

**Review by jakmeier — APPROVED** [review]

**Comment by mina86** [comment]
@jakmeier, could you add S-automerge label as well?

**Comment by jakmeier** [comment]
> @jakmeier, could you add S-automerge label as well?

Oh yeah, sure. 

How does that work today for you as external contributor? Can you only manually merge your PR after I approved it, or not at all? Does it reset the approval after you rebase and/or push other commits?

**Comment by mina86** [comment]
I cannot merge PRs and also cannot change labels hence why I need someone to either merge or add the label.

And approvals aren’t reset after I get an approval so technically I could sneak in a change between when you apply S-automerge label and the merge actually happens.

**Comment by jakmeier** [comment]
Good to know, thanks @mina86 .

**Pull request merged**
