### PR TITLE
Adds process_block_test to be used in tests

### PR DESCRIPTION
**Pull request by mzhangmzz**
to reduce code repetition. Also helps me in https://github.com/near/nearcore/pull/5224 where I changed the signature of process_block

### CODE REVIEW

**Review by yordanmadzhunkov — APPROVED** [review]
Cool

**Review by matklad — APPROVED** [review]
LGTM! 

Although, as an alternative, I suggest the following:

* move chain tests from `chain/tests` to `chain/src/tests`, a-la https://github.com/near/nearcore/issues/5149, which should reduce our overall compile time
* after that, we'll be able to mark `fn process_block_test` as `#[test]`, and also make it `pub(crate)` rather than `pub`.

**Comment by mzhangmzz** [comment]
> LGTM!
> 
> Although, as an alternative, I suggest the following:
> 
> * move chain tests from `chain/tests` to `chain/src/tests`, a-la #5149, which should reduce our overall compile time
> * after that, we'll be able to mark `fn process_block_test` as `#[test]`, and also make it `pub(crate)` rather than `pub`.

@matklad I did your suggestion but only moved simple_chain.rs and challenges.rs, which are the tests that this PR touched, to chain/src/tests. I didn't move the rest of the tests because some of them look rather complicated and I'm not sure if I should leave them as integration tests. 

I read your post here about how to organize tests https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html and I think there are many other places in the code that don't follow this rule right now. It should take a separate PR to fix them all. I'll create an issue to track that.

**Comment by matklad** [comment]
>look rather complicated and I'm not sure if I should leave them as integration tests.

I don't think test complexity should define whether the test goes to `tests/` or `src/tests` -- cargo's integration/unit terminology is just confusing. (in general, if I were a king of the world, I'd just ban both terms and asked people to use "software engineering at google"'s terminology of test size (one thread/one process/one machine/one distributed system)). It's rather "test in the same compilation unit" vs "tests in a separate compilation unit", with the difference between the two being access to `pub(crate)` and `#[cfg(test)]` APIs.

**Pull request merged**
