### PR TITLE
Improve ‘publishability’ of crates

### PR DESCRIPTION
**Pull request by mina86**
To be able to publish a crate all its dependencies must be versioned.
Make sure that this is the case for all packages listed in the
`runtime/publish.sh` script.

Note that this does not fix the issue completely and there are still
other problems stopping the crates from being published.  Most
notably, some of the dependencies not being published yet.

Issue: https://github.com/near/nearcore/issues/4379

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
I am confused by this change. I think we want to have `near-primitives-core` instead of `near-primitives` because the dependency is smaller, not the other way around

**Comment by mina86** [comment]
Yes, but if a crate already depends on `near-primitives` there’s no point in *also* depending on `near-primitives-core`.  The former re-exports everything the latter offers.  This commit does not add any new dependencies.  It only removes `near-primitives-core` where it’s redundant and makes sure that all dependencies have version specified (which is required to be able to publish a crate).

If you prefer I kept both dependencies I can alter this commit to only add the version where it’s needed.

**Comment by mina86** [comment]
Though now that I see https://github.com/near/nearcore/pull/4378 perhaps it’s best to wait with this commit.

**Comment by bowenwang1996** [comment]
> Yes, but if a crate already depends on near-primitives there’s no point in also depending on near-primitives-core. The former re-exports everything the latter offers. This commit does not add any new dependencies. It only removes near-primitives-core where it’s redundant and makes sure that all dependencies have version specified (which is required to be able to publish a crate).

Yes but the current dependency in vm logic is a mistake that is being fixed

**Pull request closed without merging**
