### PR TITLE
runtime: prefer reporting GasLimitExceeded

### PR DESCRIPTION
**Pull request by mina86**
If during execution of a contract both prepaid gas and max burnt gas
limits were exceeded, the `GasCounter` would report `GasExceeded`
error.  This was purely based on which condition was checked first
and entirely accidental based on how the code was written.

Unfortunately, that’s exactly the opposite preference to what we did
in old code which preferred reporting `GasLimitExceeded` instead.

Change the code to match the old behaviour and thus avoid protocol
changes.

### CODE REVIEW

**Comment by mina86** [comment]
This is meant to be on top of <https://github.com/near/nearcore/pull/5184>.  Only last commit here consists of the changes described in PR.

To be honest I don’t fully comprehend the accounting for burnt, used and promises gas but all the tests are passing with this change.

**Comment by EgorKulikov** [comment]
Isn't this a protocol change?

**Comment by mina86** [comment]
Here’s comparison of results of the `test_deduct_too_much` test on
various versions of the code:

| test        | 1.21.0           | Pre #5121        | HEAD (post #5121) | This PR v1       |
|-------------|------------------|------------------|-------------------|------------------|
| 5, 7, false | GasLimitExceeded | GasExceeded      | GasExceeded       | GasLimitExceeded |
| 5, 7, true  | GasLimitExceeded | GasExceeded      | GasLimitExceeded  | GasLimitExceeded |
| 5, 5, false | GasLimitExceeded | GasExceeded      | GasExceeded       | GasLimitExceeded |
| 5, 5, true  | GasLimitExceeded | GasExceeded      | GasLimitExceeded  | GasLimitExceeded |
| 7, 5, false | GasLimitExceeded | GasExceeded      | GasExceeded       | GasExceeded      |
| 7, 5, true  | GasLimitExceeded | GasExceeded      | GasLimitExceeded  | GasLimitExceeded |
| 5, 8, false | GasLimitExceeded | GasLimitExceeded | GasLimitExceeded  | GasLimitExceeded |
| 5, 8, true  | GasLimitExceeded | GasLimitExceeded | GasLimitExceeded  | GasLimitExceeded |
| 8, 5, false | GasExceeded      | GasExceeded      | GasExceeded       | GasExceeded      |
| 8, 5, true  | OK               | OK               | OK                | OK               |

With this change the (max_gas_burnt=7, prepaid_gas=5, is_view=false)
test produces a different result compared to what we had in 1.21.0.
In this test, we’re burning and using 8 gas which is above both
limits.

Changing the method to prefer reporting GasLimitExceeded brings all
the tests to the state they were at 1.21.0.

**Comment by matklad** [comment]
This is not a protocol change, as we don't record which particular error occurred: https://github.com/near/nearcore/blob/b4531a00f4b77bfcce7126c29c9744d65762fdf4/core/primitives/src/transaction.rs#L299.

This is an unexpected behavior change which we missed in #5121 though, so it's still something we need to fix.

**Review by matklad — APPROVED** [review]
Thanks for fixing this!

**Review by bowenwang1996 — APPROVED** [review]

**Pull request merged**
