### PR TITLE
Mieubrisse/sandbox docker image

### PR DESCRIPTION
**Pull request by mieubrisse**

### CODE REVIEW

**Comment by ChaoticTempest** [comment]
Thanks for the PR and this looks good to me for the most part, but I wonder if we need the nightly flag too for sandbox builds. Would you happen to know @ailisp? Additionally, we should add a ticket (if there isn't one already) to consolidate all the Dockerfiles since the number of Dockerfiles can snowball for each feature or each combinatorial set of flags/features

**Review by chefsale — APPROVED** [review]

**Comment by mieubrisse** [comment]
Hey @chefsale @ailisp I've updated the branch with latest, but don't have permission to merge even though checks are passing. Would you mind merging this?

**Comment by mieubrisse** [comment]
Heyo @chefsale @ailisp , wanted to ping on this since it gets out-of-date fast!

**Comment by ailisp** [comment]
@mieubrisse going to merge. thank you!

**Pull request merged**
