### PR TITLE
refactor: Use structured Fee parameter value

### PR DESCRIPTION
**Pull request by akashin**
This PR codifies the already-existing structure of Fee parameters making parameter config easier to read and parameters easier to parse.

It has the same downside as https://github.com/near/nearcore/pull/8426 in the diff configs that need to specify the old values in the other fields of the composite Fee value. I'll try to improve this in this PR by allowing some of the values to be Optional, but for now sending it as is to make sure that the general change makes sense.

### CODE REVIEW

**Review by jakmeier — APPROVED** [review]
I really like this change!

If you have ideas how to make unchanged fields optional, feel free to add it. But honestly I think
```yaml
action_deploy_contract_per_byte: {
  old: {
    send_sir: 6_812_999,
    send_not_sir: 6_812_999,
    execution: 6_812_999,
  },
  new: {
    send_sir: 6_812_999,
    send_not_sir: 6_812_999,
    execution: 64_572_944,
  },
}
```
is a bit more verbose but it is still easy for a user to see what has actually changed.

In the alternative
```yaml
action_deploy_contract_per_byte: {
  old: {
    execution: 6_812_999,
  },
  new: {
    execution: 64_572_944,
  },
}
```
one could even argue some interesting context is missing.

Both work fine IMO.
I would just try to keep it consistent with the gas weights structure. Either we say any change must always be for a full Parameter (1 Fee = 1 Parameter, 1 Weighted Gas = 1 Parameter) and therefore all its inner structure must be defined in the change.
Or we allow structured diffs and deal with the added complexity for weights and for fees.

**Review by jakmeier — CHANGES_REQUESTED** [review]
Ah before you merge this, please wait for https://github.com/near/nearcore/pull/8098 to get in, or else I have to ask the external contributor to rebase and update snapshots manually again ^^

**Review by jakmeier — APPROVED** [review]
Ready to merge now, the other PR is in.

**Comment by akashin** [comment]
> ...
> Both work fine IMO. I would just try to keep it consistent with the gas weights structure. Either we say any change must always be for a full Parameter (1 Fee = 1 Parameter, 1 Weighted Gas = 1 Parameter) and therefore all its inner structure must be defined in the change. Or we allow structured diffs and deal with the added complexity for weights and for fees.

Ok, I will keep the diffs as is for now and will experiment with sparse diffs on top of PR that introduces weights.

**Pull request merged**
