### PR TITLE
chore: drop stale tests

### PR DESCRIPTION
**Pull request by miraclx**
Since introducing the strictly typed `AccountId`, the following issues are non-existent:

- https://github.com/near/nearcore/issues/2790
- https://github.com/near/nearcore/issues/2791
- https://github.com/near/nearcore/issues/2792
- https://github.com/near/nearcore/issues/2793

In the case of https://github.com/near/nearcore/issues/2789, as pointed out in https://github.com/near/nearcore/issues/2789#issuecomment-845706819, we have `integration-tests` replacing this unit test.

https://github.com/near/nearcore/blob/2677f00918b7425beafce562d4fdff67692a3a3f/integration-tests/src/tests/nearcore/rpc_nodes.rs#L309-L345

And finally, https://github.com/near/nearcore/issues/2800 seems to work properly.

### CODE REVIEW

**Review by khorolets — APPROVED** [review]
Perfect PR! 👍

**Comment by khorolets** [comment]
@miraclx I don't have any preferences about the location, so I'd trust your decision.

**Comment by miraclx** [comment]
Understood. I'll pull it out. It's been ignored for far too long, making it an insignificant check. The integration test we already have should suffice.

**Comment by frol** [comment]
@miraclx I just wanted to share a perspective that it could be better to switch the tests to use raw JSON inputs, and test the potential validation errors as well

**Pull request merged**
