### PR TITLE
Switch all script to use /usr/bin/env bash as /bin/bash is not portable

### PR DESCRIPTION
**Pull request by chefsale**
cc: @pmnoxx @matklad

### CODE REVIEW

**Review by matklad — APPROVED** [review]
That's a lot of bash scripts!

**Comment by matklad** [comment]
JFYI, in rust-analyzer we avoided bash scritps and instead did all task automation in Rust, [using this trick](https://github.com/matklad/cargo-xtask).

**Comment by chefsale** [comment]
> JFYI, in rust-analyzer we avoided bash scritps and instead did all task automation in Rust, [using this trick](https://github.com/matklad/cargo-xtask).

That would be a bit more work :)

**Review by bowenwang1996 — APPROVED** [review]

**Comment by chefsale** [comment]
cc: @ailisp @frol

**Review by pmnoxx — APPROVED** [review]

**Comment by ailisp** [comment]
Looks good! I read somewhere, some os has env only in /bin/env, but should be good for most commonly seen OSs :D

**Comment by willemneal** [comment]
Given our reliance on Bash, perhaps we should add the following to CI to see what it says about the scripts: https://github.com/koalaman/shellcheck

**Review by willemneal — APPROVED** [review]

**Comment by chefsale** [comment]
@willemneal this is cool, i will look into integrating this 🥇

**Pull request merged**
