### PR TITLE
optimize wasmparser for tests

### PR DESCRIPTION
**Pull request by Ekleog-NEAR**
The runtime of the whole test suite gets down by ~2.5% with this change. Integration tests and near-vm-runner get a ~3.5% speedup.

CI times will be confirmed to not have too much change by it running on this PR.

See also #9606.

### CODE REVIEW

**Comment by nagisa** [comment]
I don’t agree with using `opt-level=3` here in general. It can make using a debugger an experience full of frustration. I wouldn’t mind `opt-level = 1` though.

**Comment by Ekleog-NEAR** [comment]
> CI times naturally can’t change much as the CI uses the quick-release profile on GHA and to the best of my knowledge full release profile on buildkite.

Oh interesting. It might make sense to change this? I quickly looked into CI times (the non-integration-tests), and noticed that more than 50% of the time is spent compiling. Maybe if we just compiled in debug mode it’d be significantly faster, plus we could then shard tests across multiple runners to get them to run faster?

> It can make using a debugger an experience full of frustration.

Hmm… Doesn’t `opt-level = 3` at the crate level still leaves all the wasmparser function calls clear in the debugger? I’m thinking that it’d be enough to know which wasmparser (top-level) function gets called, and if something is needed further than that it’s still possible to temporarily rebuild with `opt-level = 1` to debug the internals of wasmparser.

Unless there’s something specifically with wasmparser that makes it work less well than with this setup?

**Comment by nagisa** [comment]
> Hmm… Doesn’t opt-level = 3 at the crate level still leaves all the wasmparser function calls clear in the debugger? I’m thinking that it’d be enough to know which wasmparser (top-level) function gets called, and if something is needed further than that it’s still possible to temporarily rebuild with opt-level = 1 to debug the internals of wasmparser.

What I’m saying is that it isn’t obvious that `opt-level` for a specific dependency is being activated vs debug info being generally wonky, as sometimes is still the case (unfortunately!) I guess a more important question is what is the use-case? If you want programs that run quickly – you can use a more optimized profile in the first place.

> Maybe if we just compiled in debug mode it’d be significantly faster, plus we could then shard tests across multiple runners to get them to run faster?

I’d say that reductions in CI turnaround times have a diminishing value after a certain point, and that there are lower-hanging-fruit kind of solutions (e.g. use a faster runner, such as `ubuntu-22.04-16core`) if the CI speed is unsatisfactory.

We of course can prebuild (and even cross-compile!) tests and then shard them (`nextest` has native support for it with `archive`!), but this is orthogonal to the optimization level. We could do that even now.

Unfortunately, our test suite has a problem of a long tail (some of the integration tests running for multiple minutes at a time,) rather than that of a throughput, and thus sharding is of a limited benefit. This isssue would be better mitigated with higher concurrency (e.g. `--test-threads 32`) on the hardware we already use, rather than throwing more of it at the problem, if only to give a better chance for those long tail tests to start sooner.

Once they do start, though, they better go as fast as they can possibly go, to make the long tail shorter by at least a bit.

**Comment by nagisa** [comment]
(As for the build speeds, I would argue that integrating something like `sccache` and reusing build artifacts across builds is probably going to give greater long-term payoff than toggling optimization levels for individual dependencies)

**Comment by Ekleog-NEAR** [comment]
> I guess a more important question is what is the use-case?

The use case is: "I want a local `cargo nextest run` to complete quickly, while still allowing me to debug what goes wrong when it’s in my code." I actually don’t really care about build time for anything that’s not my code, because that happens only once each time I rebase on master at most (or add/remove a dep), whereas `cargo nextest run` does often happen quite a lot of times.

So in a way, yes, just toggling opt-level for literally all the dependencies would probably make sense, but I’d still not want to enable it for all the non-dependencies. I don’t know if there’s a way to actually do that, though? (I’d rather avoid listing explicitly all the local crates twice, because otherwise debugging would become a mess if we were to add a new crate)

Actually another change I have in mind is really unifying features, so that I need to build only once each rebase, and not once for `cargo nextest run` and another time for `cargo nextest run -p near-vm-runner` :)

Thank you for your other thoughts!

**Comment by Ekleog-NEAR** [comment]
Actually I should have checked the docs before writing this, I can do what I’m trying to do with `[profile.dev.package."*"]`. I’ll try to see how benchmarks go and submit a PR accordingly :)

**Comment by Longarithm** [comment]
Unassigning myself because I have much less context here.

**Pull request closed without merging**
