### PR TITLE
introduce all the necessary features for reusing contract data memories

### PR DESCRIPTION
**Pull request by Ekleog-NEAR**
With this, all that’s missing should be the contract data memory queue, and checking that the `Arc::into_inner` actually works properly at least most of the time. I’m… not that hopeful about this second precondition, but let’s see what happens with a bit of testing.

Part of #11033

### CODE REVIEW

**Comment by Ekleog-NEAR** [comment]
The untested code lines should become tested once the actual implementation using these new helper functions will land :)

**Review by nagisa — COMMENTED** [review]
My bad, had this reviewed last week but forgot to submit the review T_T

**Review by nagisa — APPROVED** [review]

**Comment by Ekleog-NEAR** [comment]
No worries and thanks for the review! I haven't managed to finish the subsequent PR anyway. Once the next one is closer to completion, I'll handle your comments and land this one :)

**Comment by Ekleog-NEAR** [comment]
Closing, as per the results written down in #11033: it turns out the "optimization" is actually slower than the baseline, so there’s no longer any reason to land this code

**Pull request closed without merging**
