### PR TITLE
feat(COP): Stabilize reduction of block producer seats in testnet

### PR DESCRIPTION
**Pull request by nikurt**
Tested in mocknet: https://nearinc.grafana.net/goto/vA9p9-nSg?orgId=1

### CODE REVIEW

**Comment by nagisa** [comment]
(I could review it as well, if there were links to background information suggesting that it is indeed the correct time to stabilize this feature – links to discussion, documents, NEPs, etc.)

**Comment by nikurt** [comment]
Thanks @nagisa , I completely missed that this needs an NEP. Working on it.

**Comment by nikurt** [comment]
NEPs#514

**Review by nagisa — APPROVED** [review]
Alright, I’m going to mark this as approved given the NEP. I really appreciate you writing it down, it was a great learning experience reading through it.

**Pull request merged**
