### PR TITLE
chore: reformat Cargo.toml lists with many elements in one line

### PR DESCRIPTION
**Pull request by marcelo-gonzalez**
this will make them easier to edit and the git diffs will be nicer.
Done with a python script that basically says:

  if len(list) > 1:
     reformat(list)

Issue: https://github.com/near/nearcore/issues/5328

### CODE REVIEW

**Review by mina86 — APPROVED** [review]
I think we want the lines reformatted even if there are only two elements.  The point is to have cleaner diffs when elements are added or removed.  Having list on a single line when there’s only one element is a reasonable compromise for the files not ending up too verbose.

**Review by khorolets — APPROVED** [review]

**Comment by marcelo-gonzalez** [comment]
> I think we want the lines reformatted even if there are only two elements. The point is to have cleaner diffs when elements are added or removed. Having list on a single line when there’s only one element is a reasonable compromise for the files not ending up too verbose.

Fair enough. I initially chose > 2 because it seemed fine to leave stuff like:

```
default = ["borsh", "serde"]
```

but I'll update it shortly, maybe manually omitting some like that one

**Review by bowenwang1996 — APPROVED** [review]
Thanks!

**Review by pmnoxx — APPROVED** [review]
lgtm

**Review by matklad — APPROVED** [review]

**Review by nikurt — APPROVED** [review]

**Pull request merged**
