### PR TITLE
fix(genesis-init): respect genesis.use_production_config when computing genesis state

### PR DESCRIPTION
**Pull request by marcelo-gonzalez**
`near_store::genesis::initialize_genesis_state()` uses the shard layout found in the genesis config when computing the initial state roots. This works fine as long as the `use_production_config` parameter is `false`. But when it's `true`, this shard layout is not necessarily the same as the one we'll get in the first epoch of the chain. So with the resharding in protocol version 64, that means that if we try to start a mocknet test forked from a 4-shard mainnet with starting protocol version 64, we hit [this assert](https://github.com/near/nearcore/blob/fb500f5b976669e2e481f1d8e3bee49dced022ec/core/primitives/src/block.rs#L102) because `initialize_genesis_state()` computed its state roots based on the 4 shards specified in the genesis config, but the `shard_ids` slice we're comparing it to is [taken from](https://github.com/near/nearcore/blob/fb500f5b976669e2e481f1d8e3bee49dced022ec/chain/chain/src/chain.rs#L398) the 5 shards we get with `use_production_config=true`

So this PR extracts an `initialize_sharded_genesis_state()` function from `initialize_genesis_state()` that takes an `EpochConfig`, which will be called with the correct config in `nearcore::start_with_config_and_synchronization()`. Then in that function, we refer to that `EpochConfig`'s shard layout and `num_block_producer_seats_per_shard` instead of the genesis config's. We do this instead of just changing `initialize_genesis_state()` because that function is called in many tests, and it would be a bit of a pain to update every caller

closes https://github.com/near/nearcore/issues/9996

### CODE REVIEW

**Comment by marcelo-gonzalez** [comment]
@wacban as far as testing, I did a couple things. One was just to start a mocknet with protocol version 64 and check that it runs fine. Also, I tried starting a mocknet with protocol version 63 with 2 nodes, one running master and one running from this PR, to check that the genesis state roots match.

also, as i wrote in the pr message, I extracted a different function to avoid having to update all the callers, but if you are not a fan of that I can be convinced to just do the work of updating the callers :)

**Comment by wacban** [comment]
@marcelo-gonzalez Can you tell me where is it used? If it's only for mocknet or forknet I'll rubber stamp, if it's prod I'll have a proper look tomorrow.

**Comment by marcelo-gonzalez** [comment]
> @marcelo-gonzalez Can you tell me where is it used? If it's only for mocknet or forknet I'll rubber stamp, if it's prod I'll have a proper look tomorrow.

well I think it's most often used on mocknet, but it is actually also part of neard itself. So for example if you were to start a testnet node with an empty data dir with this change, it would get triggered. So probably best to have a proper look I think

**Comment by marcelo-gonzalez** [comment]
> LGTM
> 
> I slightly dislike that we pass two versions of the same information but I can't think of a better way to do it so you have my approval.

@wacban yea I totally agree, and I also couldnt think of a better way :(. I've noticed that this pattern of passing two versions of the same information also shows up elsewhere. for example look at where we create a new `NightshadeRuntime` from the `config.json`. In the `NearConfig` struct, there is a `config` field that contains the parsed json file, but there are also other fields, like `client_config`, that are built from that one. So the fields in `client_config` are taken from fields in `config`, and in `NightshadeRuntime::from_config()` notice how we refer to `config` [in some places](https://github.com/near/nearcore/blob/8caa46b7573957ddf4250a2bcb3fd0548d0c6510/nearcore/src/config.rs#L646) and `client_config` [in others](https://github.com/near/nearcore/blob/8caa46b7573957ddf4250a2bcb3fd0548d0c6510/nearcore/src/config.rs#L643). this is not great and should maybe be fixed...

**Pull request merged**
