### PR TITLE
fix(rpc): structured errors

### LINKED ISSUE #2536: Update RPC error schema
According to https://github.com/nearprotocol/nearcore/issues/2518#issuecomment-619452654, when we query a transaction and it doesn't exist, we do not return a structured error, which causes problems in downstream applications. We need to update the rpc error schema to make the errors structured.

### LINKED ISSUE #2976: nearcore doesn't return structured errors for most use cases of API
Structured errors work (https://github.com/nearprotocol/nearcore/issues/1839) is not complete and it's hard to know what to expect.

Example of error from nearcore:

```
    response.error {
      code: -32000,
      message: 'Server error',
      data: 'Other Error: block DtdfWgnt3QDEjoeARUK25vg8qh31kc3Lrg6qREsoJsST is ahead of head block 34eT8dRWfDPhZBiRGYvkHDj65ThaXCBTrnM4LQjn2Zab \n' +
        ' Cause: Unknown \n' +
        ' Backtrace:    0: failure::backtrace::Backtrace::new\n' +
        '   1: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle\n' +
        '   2: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll\n' +
        '   3: tokio::runtime::task::raw::poll\n' +
        '   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n' +
        '   5: actix_rt::runtime::Runtime::block_on\n' +
        '   6: near::main\n' +
        '   7: std::rt::lang_start_internal::{{closure}}::{{closure}}\n' +
        '             at rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/rt.rs:52\n' +
        '      std::sys_common::backtrace::__rust_begin_short_backtrace\n' +
        '             at rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/sys_common/backtrace.rs:130\n' +
        '   8: main\n' +
        '   9: __libc_start_main\n' +
        '  10: _start\n'
    }
```

Note that even actual error message `Other Error: block DtdfWgnt3QDEjoeARUK25vg8qh31kc3Lrg6qREsoJsST is ahead of head block 34eT8dRWfDPhZBiRGYvkHDj65ThaXCBTrnM4LQjn2Zab` doesn't go into proper place in `message`.

This effectively makes current error message strings part of API, which is very suboptimal.

Here's how we have to handle errors because of this:

*near-api-js*

```
src/account.ts
120:                if (!error.message.match(/Transaction \w+ doesn't exist/)) {
205:            if (e.message.includes('does not exist while viewing')) {
```

```
src/wallet-account.ts
193:                if (e.message.includes('does not have enough balance')) {
```

*near-wallet*

```
src/actions/account.js
78:            if (error.message.indexOf('does not exist while viewing') !== -1) {
```

```
src/reducers/allAccounts.js
16:        if (payload.message.match('does not exist')) {
```

Note that we also handle errors explicitly only in few cases (degrading user experience) because we want to avoid depending on error messages in this way. This problem also degrades quality of every app built on NEAR, as everybody has same problem.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Make rpc return structured errors instead of string and update the rpc error schema accordingly. Errors returned by rpc are now of the form
```
{type: <error_type>, content: <error_content>}
```
where content may contain inner errors.
 
Fixes #2976.
Fixes #2536 

Test plan
---------
Nightly tests and near-api-js tests

### CODE REVIEW

**Comment by frol** [comment]
@nearmax When we talked yesterday, I had not been fully in the context of the rpctypegen. I had reviewed the code and it appears to be that we do not return the execution outcome as binary representation; we parse it on the RPC side, so the errors are then serialized to JSON and RPC exposes it in that way, as you can see here:

https://explorer.testnet.near.org/transactions/4ArpKFcz9f1qNjGWeNevXZy7PioxyC8gRMiK9oNGArTa

```js
$ http post https://rpc.testnet.near.org/ jsonrpc=2.0 method=tx params:='["4ArpKFcz9f1qNjGWeNevXZy7PioxyC8gRMiK9oNGArTa", "valentine_sokol.testnet"]' id=dontcare

{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "receipts_outcome": [
            {
                "block_hash": "DRieqmTCWVUrpXKwGTu1wtr5ekYZEjb6hJeVBCFuDVwE",
                "id": "DdJ8Akhw75nGEaXmoeTTpo4BKLXsXSUs7sa2TRAyWYvC",
                "outcome": {
                    "executor_id": "valentine_sokol.testnet",
                    "gas_burnt": 5793172812440,
                    "logs": [],
                    "receipt_ids": [
                        "Bme4z27tuA4DSNeDtbRHiT4dBAL1iec3rHxM8QLMHuHF"
                    ],
                    "status": {
                        "Failure": {
                            "ActionError": {
                                "index": 0,
                                "kind": {
                                    "FunctionCallError": {
                                        "HostError": {
                                            "GuestPanic": {
                                                "panic_msg": "Attempt to call transfer on tokens belonging to another account."
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "tokens_burnt": "5793172812440000000000"
                },
                "proof": [
                    {
                        "direction": "Left",
                        "hash": "2VeM66pVEZYoQ4bti5mURp9d92Z2mVD4qJP4sBK1J4po"
                    }
                ]
            },
            {
                "block_hash": "8sFjv3cn4HK6XnW2dwqo5hxaULz4ETg2Ye6KFy32G3Wd",
                "id": "Bme4z27tuA4DSNeDtbRHiT4dBAL1iec3rHxM8QLMHuHF",
                "outcome": {
                    "executor_id": "valentine_sokol.testnet",
                    "gas_burnt": 0,
                    "logs": [],
                    "receipt_ids": [],
                    "status": {
                        "SuccessValue": ""
                    },
                    "tokens_burnt": "0"
                },
                "proof": []
            }
        ],
        "status": {
            "Failure": {
                "ActionError": {
                    "index": 0,
                    "kind": {
                        "FunctionCallError": {
                            "HostError": {
                                "GuestPanic": {
                                    "panic_msg": "Attempt to call transfer on tokens belonging to another account."
                                }
                            }
                        }
                    }
                }
            }
        },
        "transaction": {
            "actions": [
                {
                    "FunctionCall": {
                        "args": "eyJvd25lcl9pZCI6InZhbGVudGluZV9zb2tvbC50ZXN0bmV0IiwibmV3X293bmVyX2lkIjoidmFsZW50aW5lcGhvbmUudGVzdG5ldCIsInRva2VuX2lkIjozfQ==",
                        "deposit": "0",
                        "gas": 30000000000000,
                        "method_name": "transfer_and_update"
                    }
                }
            ],
            "hash": "4ArpKFcz9f1qNjGWeNevXZy7PioxyC8gRMiK9oNGArTa",
            "nonce": 8,
            "public_key": "ed25519:C4Jo4RL9S6qu3oHQMoU74CDmzUxtF7YZb95fsQHFE1pf",
            "receiver_id": "valentine_sokol.testnet",
            "signature": "ed25519:49y8Tz733B1rBDPmSXfLxatBgwbLvsf2SPcycxAVYH8neJaQbziZr4VRXrCVrmKECxCnWwbp296k7TuErPpAHUkA",
            "signer_id": "valentine_sokol.testnet"
        },
        "transaction_outcome": {
            "block_hash": "DRieqmTCWVUrpXKwGTu1wtr5ekYZEjb6hJeVBCFuDVwE",
            "id": "4ArpKFcz9f1qNjGWeNevXZy7PioxyC8gRMiK9oNGArTa",
            "outcome": {
                "executor_id": "valentine_sokol.testnet",
                "gas_burnt": 2428166952740,
                "logs": [],
                "receipt_ids": [
                    "DdJ8Akhw75nGEaXmoeTTpo4BKLXsXSUs7sa2TRAyWYvC"
                ],
                "status": {
                    "SuccessReceiptId": "DdJ8Akhw75nGEaXmoeTTpo4BKLXsXSUs7sa2TRAyWYvC"
                },
                "tokens_burnt": "2428166952740000000000"
            },
            "proof": [
                {
                    "direction": "Right",
                    "hash": "Ab2EpAh1DfZJqLUGxojc6s4WQupy47RFrtEmWWqgDHSD"
                }
            ]
        }
    }
}
```

rpctypegen on the near-api-js side is just a helper that maps this default serde enum representation into TypeScript types. It seems to be unnecessarily complex both on the nearcore and near-api-js side.

The benefit of rpctypegen is that it generates static TypeScript classes for near-api-js, so the devs can see and match the errors on the type level on near-api-js side, and what is probably more important is that it exposes an exhaustive list of all possible errors.

@vgrichina Do I recall correctly that you were asking to make the errors just objects with "type" field that would be a simple string value like "FUNCTION_CALL_ERROR"?

My vision is to drop rpctypegen and transform the error structure into tagged representation:

Before:

```json
        "status": {
            "Failure": {
                "ActionError": {
                    "index": 0,
                    "kind": {
                        "FunctionCallError": {
                            "HostError": {
                                "GuestPanic": {
                                    "panic_msg": "Attempt to call transfer on tokens belonging to another account."
                                }
                            }
                        }
                    }
                }
            }
        },
```

After:

```json
        "status": {
            "kind": "FAILURE",
            "details": {
                "kind": "ACTION_ERROR",
                "cause": {
                    "index": 0,
                    "kind": "FUNCTION_CALL_ERROR",
                    "cause": {
                      "kind": "HOST_ERROR",
                      "cause": {
                        "kind": "GUEST_PANIC",
                        "details": {
                           "panic_msg": "Attempt to call transfer on tokens belonging to another account."
                        }
                    }
                }
            }
        },
```

NOTE: I prefer to use "kind" over "type" as "type" is commonly a keyword which makes things a bit ugly to work with. Alternatively, we may use "status_type", "error_type" field names.

I believe this structure will be much easier to deal with on JS side. However, it is a breaking change for the API. Well, this whole PR is a breaking change to all the errors returned from JSON RPC (old string error messages will be replaced with structured errors, and the weirdly-structured transaction/execution-outcome errors will get aligned with the style).

**We are blocked to merge this PR until AppLayer gets necessary handlers inside near-api-js (I think we should be able to handle old and new style of errors on near-api-js side).** @vgrichina @mikedotexe @janedegtiareva @mattlockyer WDYT?

**Comment by bowenwang1996** [comment]
@vgrichina are you going to make the necessary change for near-api-js?

**Comment by vgrichina** [comment]
@frol @bowenwang1996 I think this was discussed before in Slack, but generally anything we do right now needs backwards compatibility. 

So change like this should only activate when near-api-js (or whatever client library) sends corresponding API version. If it is older client library – it should be getting old style errors.
Given timing of work on errors app layer (including third-parties) already had to start to rely on regexping error messages to check for error reasons and it'll be painful if it gets broken.

**Comment by vgrichina** [comment]
Personally I'd just prefer following response structure for errors:

```json
{
   "errorCode": "ActionError.FunctionCallError.HostError.GuestPanic",
   "errorDetails":  {
       "panic_msg": "Attempt to call transfer on tokens belonging to another account."
    }
}
```

This is also roughly how this will get collapsed on near-api-js side anyway. Does anybody want to deal with above nested structure client-side? Don't think so – best we can expect is that people:
- use error code prefix to determine the "class" of error and act accordingly in UI
- use error code as message ID to display localized message in UI, passing `errorDetails` as template parameters

Makes sense to me to design for actual use case from my POV. Don't understand where desire to have nested structure comes from. Just checking for specific error going to be super clunky in most languages, something like:

```js
if (status.Failure && status.Failure.ActionError && status.Failure.ActionError.FunctionCallError &&  status.Failure.ActionError.FunctionCallError.HostError && status.Failure.ActionError.FunctionCallError.HostError.GuestPanic) {
    // now we know that this was GuestPanic
}
```

to be fair in many languages (even modern JS if you say use Babel) you can do chained optionals and then you have something like:

```js
if (status?.Failure?.ActionError?.FunctionCallError?.HostError?.GuestPanic) {
    // now we know that this was GuestPanic
}
```

Note that this works only for current structured error serialization. 

I we go with @frol's proposal:

```json
        "status": {
            "kind": "FAILURE",
            "details": {
                "kind": "ACTION_ERROR",
                "cause": {
                    "index": 0,
                    "kind": "FUNCTION_CALL_ERROR",
                    "cause": {
                      "kind": "HOST_ERROR",
                      "cause": {
                        "kind": "GUEST_PANIC",
                        "details": {
                           "panic_msg": "Attempt to call transfer on tokens belonging to another account."
                        }
                    }
                }
            }
        },
```

then this structure is outright completely unusable without transforming it first. You will have to use it like:

```js
if (status.kind == "FAILURE" && status.details?.kind == "ACTION_ERROR" && status.details?.cause?.kind == "FUNCTION_CALL_ERROR" //.... don't even wanna do remaining ones as it's already pretty bad even with optional chaining
```

**Comment by evgenykuzyakov** [comment]
@vgrichina Is it possible to flatten it on JS side with some method, so it's easier to process later?

**Comment by vgrichina** [comment]
> Is it possible to flatten it on JS side with some method, so it's easier to process later?

@evgenykuzyakov That is exactly what I'm going to do in near-api-js and most likely all other client libraries will have to do as well. The question is – why keep impractical format in the first place? (given we already have to break API compatibility).

**Comment by bowenwang1996** [comment]
One concern is that if we flatten it in nearcore then some information is just lost or becomes hard to retrieve. Maybe some people care about the details in the middle (not just the lowest level detail)

**Comment by evgenykuzyakov** [comment]
> The question is – why keep impractical format in the first place? (given we already have to break API compatibility).

Some errors have positional arguments, e.g.`account_id`. We may eventually want to link them to explorer

**Comment by vgrichina** [comment]
> > The question is – why keep impractical format in the first place? (given we already have to break API compatibility).
> 
> Some errors have named arguments, e.g.`account_id`. We may eventually want to link them to explorer

```
{
   "errorCode": "ActionError.FunctionCallError.HostError.GuestPanic",
   "errorDetails":  {
       "panic_msg": "Attempt to call transfer on tokens belonging to another account."
    }
}
```

`panic_msg` in the proposed flat format here is also name argument like `account_id`.

**Comment by vgrichina** [comment]
> One concern is that if we flatten it in nearcore then some information is just lost or becomes hard to retrieve. Maybe some people care about the details in the middle (not just the lowest level detail)

Can you give specific examples? Otherwise it looks like pretty common case of https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

**Comment by vgrichina** [comment]
Created separate issue to track API versioning support https://github.com/nearprotocol/nearcore/issues/3395

**Comment by frol** [comment]
This PR is not going to be rebased, we choose to move in smaller steps, and the initial iteration of laying out the framework we are applying to error handling throughout the project is merged (#3805). Next steps are:

1. Apply the framework to the rest of the view-client (#3518) and jsonrpc (#3517) handlers 
2. Expose the exhaustive list of possible errors via JSON RPC (#2976)
3. (icebox) Apply the framework to the whole nearcore codebase (#3851)

**Pull request closed without merging**
