### PR TITLE
drop buildkite pipeline

### PR DESCRIPTION
**Pull request by Ekleog-NEAR**
We have now fully migrated off buildkite, so let’s remove the old pipeline from the repository :)

### CODE REVIEW

**Comment by Ekleog-NEAR** [comment]
Considering we’re no longer using buildkite, I’m removing the `check_pytests.py` script. It might be possible to port it to github actions, but we’re also looking towards moving the tests from github actions to a `Justfile`, which would make them easier to run locally.

All in all, I don’t think this script pulls its weight currently. Maybe it will again once our setup will have stabilized. But with today’s movement, I think the risk it mitigates (a python test that would not be run in CI) is not likely enough to warrant the maintenance costs. (Since the beginning of the year, we added a total of 12 pytests, if I count correctly)

**Comment by wacban** [comment]
> Considering we’re no longer using buildkite, I’m removing the check_pytests.py script. 

I see why we no longer need to check buildkite but it seems valuable to check that all tests are included in nayduck. Perhaps we can just limit the scope of this script to that job and add exceptions for any scripts that should be run not in nayduck but as separate jobs?

**Comment by Ekleog-NEAR** [comment]
Hmm… what if we were to split python tests into two folders, one of tests that should all be run by nayduck, and for the like 3 files that are being run by the CI? Would it be hard to do so? (I have basically never touched our pytest infra yet)

**Comment by wacban** [comment]
Sure that sounds good. @andrei-near is the expert I also have little context on how it actually works.

**Comment by nagisa** [comment]
I suggest splitting up this PR into two parts – the uncontraversial part that matches the PR title, and the other part can stand its own ground against any scrutiny :)

**Review by wacban — APPROVED** [review]
approving to unblock you as it's not that critical, we can continue discussion offline

**Comment by nagisa** [comment]
> adjusting `check_pytests`

is what I was advocating for. If we do end up landing this removal though we should at least file an issue to follow up on restoring it. But from my reading it should be fairly straightforward to remove the buildkite checks for the time being, here’s how I would suggest to approach it for now:

1. Delete `read_pipeline_tests` function;
2. Replace `missing.difference_update(read_pipeline_tests(BUILDKITE_PIPELINE_FILE))` with a hardcoded (for now) list of tests that are covered by GHA.

wdyt?

**Review by andrei-near — APPROVED** [review]

**Comment by wacban** [comment]
The purpose of the check is to make sure that the test author doesn't forget to get it included in nayduck. It's quite easy to miss for both the author and the reviewer.

**Comment by Ekleog-NEAR** [comment]
I’ve just pushed an updated version of `check_scripts.py` that does as you say, considering the opinions on the matter :)
Will land soon-ish if no one objects, based on the previous approving reviews-with-comments :)

**Review by nagisa — APPROVED** [review]

**Pull request merged**
