### PR TITLE
feat: tracing logs in estimator

### PR DESCRIPTION
**Pull request by jakmeier**
Allow to select tracing levels and targets with the `RUST_LOG` environment variable when the estimator is running without the `--tracing-span-tree` flag.

### CODE REVIEW

**Comment by matklad** [comment]
Why do we need to check for `--debug` flag though? Seems fine to just do this unconditionally?

**Comment by jakmeier** [comment]
> Why do we need to check for `--debug` flag though? Seems fine to just do this unconditionally?

I was thinking about interactions with `tracing_span_tree`, so we can enable them individually or combined. But no strong opinion, if you think it is fine, I can also enable this unconditionally.

**Comment by matklad** [comment]
Hm, would it work to enable them combined? I think the two would conflict. In this sense, I'd probably expcet 

```
if span_tree {
  enable-span-tree
} else {
  enable-normal-logs
}
```

**Comment by jakmeier** [comment]
Yeah that makes sense!

**Review by matklad — APPROVED** [review]

**Pull request merged**
