### PR TITLE
Use Rational32 instead of Rational

### PR DESCRIPTION
**Pull request by mzhangmzz**
Rational is a machine-dependent type. While we'll probably only ever compile for 64-bit arches, our code should not be machine dependent.

### CODE REVIEW

**Review by nikurt — APPROVED** [review]
The only thing missing in this PR is an explanation of the reason for this change.
I assume `Rational` uses `i32` to represent the values. Why is it no longer enough?

**Comment by matklad** [comment]
`Rational` uses `isize`, which is probelmatic for two reasosn:

* the name is wrong (it should be `RationalIsize`, so that no assumptions are neccsary)
* that's machine-dependent type. While we'll probably only ever compile for 64-bit arches, machine dependenc semantics is wrong here.

**Review by matklad — APPROVED** [review]

**Comment by mzhangmzz** [comment]
Changed from Rational64 to Rational32

**Comment by matklad** [comment]
wait wait wait, @mzhangmzz , are we *sure* that that changing this to `Rational32` is OK? 

So previously this was using usize, which, on x86, is the same as i64, so change to `Rational64` is trivially a non-behavioral change. 

Change to `Rational32` *would* be potentially behavioral change. We could still do that, but it requires carefully studying all call-sites to check if it would preserve the protocol.

**Pull request merged**
