### PR TITLE
test(evm): Add Balancer test localnode, betanet on nightly

### PR DESCRIPTION
**Pull request by ailisp**
All tests passed when run locally (it could be also volatile and i haven't run many times). When run on nayduck, localnet passed, betanet sometimes passed (volatile) and failed on different reasons.

Test Plan
------------
To run on nayduck, run (after install nayduck.py dependencies with pip3):
```
cd nightly
python3 nayduck.py --test_file evm.txt 
```
These tests are also included in nightly suite and after this pr merge, is running on every commit on master.

Example runs:
localnet pass: https://nayduckdiag.blob.core.windows.net/logs/68573_v2_stdout
betanet pass: https://nayduckdiag.blob.core.windows.net/logs/68572_v2_stdout
betanet fail: https://nayduckdiag.blob.core.windows.net/logs/68574_v2_stdout

Note, when view a run on nayduck, view major of test logs in stdout, not stderr.

### CODE REVIEW

**Comment by artob** [comment]
LGTM generally. Did you mean to target this at the `master` branch instead of `evm-phase2`? If so, probably should request a review also from @evgenykuzyakov and/or @nearmax.

**Review by artob — COMMENTED** [review]
LGTM generally. Did you mean to target this at the `master` branch instead of `evm-phase2`? If so, probably should request a review also from @evgenykuzyakov and/or @nearmax.

**Comment by ailisp** [comment]
> LGTM generally. Did you mean to target this at the `master` branch instead of `evm-phase2`? If so, probably should request a review also from @evgenykuzyakov and/or @nearmax.

Yeah is meant to target master, since it's all scripts, quite orthogonal to evm changes

**Review by artob — APPROVED** [review]
LGTM :+1:

**Comment by artob** [comment]
@evgenykuzyakov Please take a look when you have a chance. Getting this going would increase confidence in not having broken anything in the EVM that's been merged to `master`.

**Review by evgenykuzyakov — APPROVED** [review]

**Pull request merged**
