### PR TITLE
routing: remove offloading of unreachable components to DB

### PR DESCRIPTION
**Pull request by saketh-are**
This behavior was intended as a performance optimization for the specific case in which we lose and regain connectivity to a large component of nodes. Such a thing should not occur except in the case of malicious behavior.

There seems to be some problem with the implementation. We observe [traces of Graph::update](https://nearinc.grafana.net/explore?schemaVersion=1&panes=%7B%221j5%22%3A%7B%22datasource%22%3A%22grafanacloud-traces%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22tempo%22%2C%22uid%22%3A%22grafanacloud-traces%22%7D%2C%22queryType%22%3A%22traceqlSearch%22%2C%22limit%22%3A1000%2C%22tableType%22%3A%22spans%22%2C%22query%22%3A%22%22%2C%22filters%22%3A%5B%7B%22id%22%3A%22b341b756%22%2C%22operator%22%3A%22%3D%22%2C%22scope%22%3A%22span%22%2C%22value%22%3A%5B%5D%2C%22valueType%22%3A%22string%22%7D%2C%7B%22id%22%3A%22span-name%22%2C%22tag%22%3A%22name%22%2C%22operator%22%3A%22%3D%22%2C%22scope%22%3A%22span%22%2C%22value%22%3A%5B%22Store%3A%3Acommit%22%5D%2C%22valueType%22%3A%22string%22%7D%2C%7B%22id%22%3A%22min-duration%22%2C%22tag%22%3A%22duration%22%2C%22operator%22%3A%22%3E%22%2C%22valueType%22%3A%22duration%22%2C%22value%22%3A%2250ms%22%7D%2C%7B%22id%22%3A%22service-name%22%2C%22tag%22%3A%22service.name%22%2C%22operator%22%3A%22%3D%22%2C%22scope%22%3A%22resource%22%2C%22value%22%3A%5B%22neard%3Aed25519%3A4XcKemsduTYReCTvWYppWBbeduQKFcyFTCygzBq8Ucdo%22%5D%2C%22valueType%22%3A%22string%22%7D%5D%2C%22spss%22%3A3000%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-6h%22%2C%22to%22%3A%22now%22%7D%7D%2C%22z7x%22%3A%7B%22datasource%22%3A%22grafanacloud-traces%22%2C%22queries%22%3A%5B%7B%22query%22%3A%22c6409ed42ee8b1e2909fb6a8df5303f6%22%2C%22queryType%22%3A%22traceql%22%2C%22refId%22%3A%22A%22%2C%22limit%22%3A20%2C%22tableType%22%3A%22traces%22%2C%22datasource%22%3A%7B%22type%22%3A%22tempo%22%2C%22uid%22%3A%22grafanacloud-traces%22%7D%7D%5D%2C%22range%22%3A%7B%22from%22%3A%221712751432916%22%2C%22to%22%3A%221712773032916%22%7D%2C%22panelsState%22%3A%7B%22trace%22%3A%7B%22spanId%22%3A%2236d308fc410f4dc3%22%7D%7D%7D%7D&orgId=1) in which >2s is spent on pop_component after which >2s is spent on push_component. 

It is not clear what, if anything, we are gaining from this optimization, and the whole routing implementation is planned for deprecation anyway. Rather than spend time digging into this, we should just delete it.

---

There is a comment and a test suggesting that there is some benefit of this feature during node startup because we can avoid broadcasting edges which were previously known. Given that only the unreachable edges are stored to DB however, this feature did not actually solve that problem.

### CODE REVIEW

**Review by bowenwang1996 — APPROVED** [review]
@saketh-are did we test on a node with this change?

**Comment by saketh-are** [comment]
It's been running on `ci-d5c55b5a-mainnet-rpc-europe-west4-01-0ec5189f` for the past ~6 hours. As expected we no longer see any long-running `Store:commit`: https://nearinc.grafana.net/goto/l3hMvH-SR?orgId=1

**Comment by bowenwang1996** [comment]
@saketh-are should we merge this PR then?

**Comment by nagisa** [comment]
Thanks for taking a point to look at this on such a short notice @saketh-are!

**Pull request merged**
