### PR TITLE
re: Migrate `log` to `tracing` for some crates

### PR DESCRIPTION
**Pull request by pmnoxx**
Migrate `log` to `tracing`.

Is there any reason to use both `log` for some creates, `tracing` for others?

I'll prepare changes for all other crates later.

### CODE REVIEW

**Comment by matklad** [comment]
>Is there any reason to use both log for some creates, tracing for others?

Nope, we should just use tracing everywhere

**Review by matklad — APPROVED** [review]

**Comment by pmnoxx** [comment]
@mm-near Can you take a look?

**Comment by pmnoxx** [comment]
```
@bowenwang1996 @mm-near @mzhangmzz: /chain/ /runtime/
@chefsale @khorolets: /chain/client/src/view_client.rs
```
@bowenwang1996 @chefsale @khorolets @mm-near @mzhangmzz Can you take a look?

**Review by EgorKulikov — APPROVED** [review]

**Review by mm-near — APPROVED** [review]

**Review by mzhangmzz — APPROVED** [review]

**Review by bowenwang1996 — APPROVED** [review]
let's do it for all crates. There is no reason for keeping `log`. #4346

**Comment by pmnoxx** [comment]
```
@chefsale @khorolets: chain/client/src/view_client.rs
```
@chefsale @khorolets Can you take a look?

**Comment by pmnoxx** [comment]
```
@chefsale @khorolets: chain/client/src/view_client.rs
```
@chefsale @khorolets Can you take a look?

**Pull request closed without merging**
