### PR TITLE
doc: style tie-breaker for `&pat` vs `*val`

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by nagisa** [comment]
I know I personally will have a terribly hard time adhering to a rule like this. I tend to not spend a millisecond thinking where the deref should end up and use various forms, including those specified here, as well as methods like `copied` interchangeably, based on what makes most sense at a specific point in time.

Same for adding references, `ref` in the pattern and `&`+match-ergonomics are still quite interchangeable for me.

**Comment by matklad** [comment]
The way I see it, *because* I don't want to spend time picking between like 10 different ways to do this, I like to have rule-of-thumb which says "just use this approximately 100% of the time". Eg, I forgot how to use `ref` and `ref mut` because I just never use them, and that seems valuable -- less meaningless distinctions to pay attention to. 

But I can also agree on "let's not have any rule here", if normalization for normalization's sake isn't seen as beneficial.

**Review by nagisa — APPROVED** [review]
Having re-read this I think “prefer doing it as early as possible” is a reasonable rule of thumb.

**Review by mina86 — APPROVED** [review]
Should we describe a rule of thumb for what is ‘small’ and what is ‘big’?  i32 is 4 bytes, CryptoHashs is 32. What about types between that range? My rule of thumb is to clasify 2×sizeof(pointer) and smaller as small.

**Pull request merged**
