### PR TITLE
store: prefer enum_map::EnumMap to strum’s count and iterator

### PR DESCRIPTION
**Pull request by mina86**
RocksDB and TestDB both create vectors which are meant to map from
column to some value.  The issue is that the way they are created
assumes that variants in DBCol are all listed in order of their
values, the values are all unique and there are no holes.  In other
words, removing or rearranging variants of DBCol causes things to
break.

Solve that by using enum_map::EnumMap which creates fixed-size
constant-access arrays (same as a Vec approach) but allow the map to
be indexed by the enum value itself which avoids all of the above
issues.

Furthermore, introduce RocksDB::cf_handle method which consolidates
all bunch of unsafe blocks into a single unsafe block in that method.
Having a single unsafe block makes it easier to reason about the
safety guarantees.

### CODE REVIEW

**Review by matklad — COMMENTED** [review]
+1 on the general idea, -0 on the implementation. 

I don't think it's worth it to add a small utility crate which we didn't have in Cargo.lock to just save a bit of syntax. I would prefer replacing every `[col]` with `[col as usize]`, removing enum_map, but otherwise keeping the impl as it is in this PR.

**Comment by mina86** [comment]
> I don't think it's worth it to add a small utility crate which we didn't have in Cargo.lock to just save a bit of syntax.

The syntax isn’t really a concern in this PR.  The concern is that if you rearrange or remove variants in DBCol things will break.

**Comment by matklad** [comment]
And the 

```
        let cfs = DBCol::iter()
            .map(|col| db.cf_handle(&col_name(col)).unwrap() as *const ColumnFamily)
            .collect();
-> 

            let handle = db.cf_handle(&col_name(col));
            let name: &str = (&col).into();
            assert!(handle.is_some(), "Missing cf handle for {name}");
            cfs[col] = handle.unwrap() as *const ColumnFamily;
```

change prevents that. But enum-map isn't needed to make this change, it'll work with the old code just fine.

**Comment by mina86** [comment]
There still is an issue of DBCol::COUNT having wrong value if a variant is removed. There are other places in the code (namely core/store/src/columns.rs and chain/chain/src/store_validator.rs) which assume the value is correct (I plan to address those places perhaps by using DBCol::LENGTH provided by enum_map).

**Comment by matklad** [comment]
Indeed missed that, thanks!

:thinking: I still don't feel great about adding a one-off utility crate, *especially* the one which adds a bunch of macros. Having both `DBCol::COUNT` and `DBCol::LENGHT` is inelegant. 

Perhaps we should just add `pub sturct DbMap<V>` so there's just one place in the code where we care about this? Or maybe just

```
#[test]
fn test_no_gaps() {
    // It's a shame that strum adds a bunch of traits instead of
    // just generating a static array, which would allow to test 
    // this at compile time
    for (i, col) in DBCol::iter().enumerate() {
        assert_eq!(col as usize, i)
    }
}
```

To sum up my overall reasoning: 

* we *should* avoid awkward, non-natural code. Approaches like `get_variants_sorted` which add a specific work-around instead of solving the problem fundamentally I feeel add to tech debt overall
* but utility crates, esp macro utility crates, are a liability.

Don't want to block on this though, approving!

**Review by matklad — APPROVED** [review]

**Comment by mina86** [comment]
> Having both DBCol::COUNT and DBCol::LENGHT is inelegant.

Yes.  I hope to get rid of the former.

Note that both DoMap as well as testing that `as usize` equals enumeration position means that we can never remove deprecated columns from the enum.  We have three of them and now that we started removing old db migration code we have an opportunity to slowly clean up the enum.

> but utility crates, esp macro utility crates, are a liability.

That’s true of any code.  We have a problem, we can either solve with with a crate or invent something internally.  Either way, it’s piece of code which may include bugs.  If EnumMap was part of standard library or we had it already implemented in our code, it would be objectively the best solution to this problem.  To me it seems the best option to have that external dependency than implementing hacks around assumptions that we’re making.

**Pull request merged**
