### PR TITLE
doc: Fix broken link to validator's instructions

### PR DESCRIPTION
**Pull request by haaawk**
Previous address (https://docs.nearprotocol.com/docs/validator/staking-overview) returns 404.

### CODE REVIEW

**Review by janewang — APPROVED** [review]

**Comment by janewang** [comment]
Here's the staking page on docs: https://docs.near.org/docs/develop/node/validator/staking-and-delegation

**Comment by haaawk** [comment]
> Here's the staking page on docs: https://docs.near.org/docs/develop/node/validator/staking-and-delegation

Thanks @janewang! Is the page on docs more appropriate or should there be links to both docs and wiki?

**Comment by janewang** [comment]
@haaawk Please link to the docs which has the latest and greatest info on validators nodes. 

For example, this wiki page is very outdated (https://wiki.near.org/validators-and-staking/validators/hardware) and should be linked to the docs (https://docs.near.org/docs/develop/node/validator/hardware)

**Comment by haaawk** [comment]
I've updated the link.

**Pull request merged**
