### PR TITLE
feat(congestion): Added argument parsing to the congestion model

### PR DESCRIPTION
**Pull request by wacban**
Added the --shards, --rounds, --workflow, and --strategy arguments. workflow and strategy support "all" as a valid value, are case insensitive and strip spaces.

### CODE REVIEW

**Comment by wacban** [comment]
cc @jakmeier I couldn't add you as a reviewer, I have no clue why. Please have a look.

**Review by jakmeier — APPROVED** [review]
Looks good to me!
I might add clap auto help texts with the `value_parser` feature later. But that's optional cute cosmetics we can add separately, if at all.

**Comment by jakmeier** [comment]
> cc @jakmeier I couldn't add you as a reviewer, I have no clue why. Please have a look.

I suppose there is something about only accounts in the org can be reviewers. :shrug: Let's see if we can fix that.

In the meantime, @Longarithm as the automatically assigned reviewre, can you give the green arrow on my behalf please? :pray:

**Comment by wacban** [comment]
@jakmeier I realized that now the new strategies and workflows need to be added in two places which is suboptimal. Please let me know if you want me to come up with something better, if not I'll keep it as is because it'll only bother the two of us and we both know about it now ;)

**Comment by jakmeier** [comment]
> @jakmeier I realized that now the new strategies and workflows need to be added in two places which is suboptimal. Please let me know if you want me to come up with something better, if not I'll keep it as is because it'll only bother the two of us and we both know about it now ;)

Yeah I noticed that as well but I don't care ;P

**Review by shreyan-gupta — APPROVED** [review]
rubber stamping

**Review by akhi3030 — APPROVED** [review]

**Pull request merged**
