### PR TITLE
feat: handle `RpcError` properly

### LINKED ISSUE #11792: Consider returning http errors for certain rpc errors
Currently when a rpc request is processed, we [never return a http error](https://github.com/near/nearcore/blob/6f321bdd0f2f568a90d764296469aee27a9f8208/chain/jsonrpc/src/lib.rs#L293). However, this makes it confusing to rpc operators, who may see very low "error rate" in their monitoring when there may actually be a nontrivial amount of requests that return a timeout error with a 200 response code. We may want to consider returning a `HttpError` in that function for certain rpc errors like timeout. Of course there are legitimate errors such as "account not found" that make sense to be included in a response body with a 200.

### PR DESCRIPTION
**Pull request by frolvanya**
This PR fixes a small issue that was introduced in #11806

Internal error - 500 status code
Handler error - 408 if it's a `TIMEOUT_ERROR`, otherwise 200
Request validation error - 400 status code

closes #11792

### CODE REVIEW

**Comment by frolvanya** [comment]
@race-of-sloths please, include my PR in the Race

**Comment by race-of-sloths** [comment]
@frolvanya Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Are you going to win race-of-sloths this month? If so, you should speed up! Run, Sloth, run!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/frolvanya?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/frolvanya?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/frolvanya)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/frolvanya)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Review by frol — APPROVED** [review]
@race-of-sloths score 2

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@frol, thank you for scoring this pull request in the Race of Sloths!

**Comment by tayfunelmas** [comment]
You may need to go over Nayduck tests to make sure the new RPC errors are handled correctly (eg. timeout error is checked correctly). Thanks.

**Comment by frolvanya** [comment]
> You may need to go over Nayduck tests to make sure the new RPC errors are handled correctly (eg. timeout error is checked correctly). Thanks.

Okay, I'll add some tests today

**Comment by frolvanya** [comment]
@tayfunelmas Is it ok to extend `nearcore/chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs` instead of Nayduck?

**Comment by tayfunelmas** [comment]
> Okay, I'll add some tests today

Note that, I did not mean to add new tests (can be done later) but to check if the existing Nayduck tests still pass after this change, because the current tests assume even the errors will be responded with 200 and they check the fields of the response to see if it is an error or not.

**Comment by tayfunelmas** [comment]
> @tayfunelmas Is it ok to extend `nearcore/chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs` instead of Nayduck?
> 
> P.S: Already did it and now code coverage is 75%. During this week I'm planning to split jsonrpc into a trait and a structure. After this I should be able to use https://crates.io/crates/mockall to create a mock of `JsonRpcHandler::process` function that would return an internal error for me. At least for now, that's the only way how I see adding a test case for the internal error

Yes, it should work. Thank you for adding the test.

**Comment by akashin** [comment]
FYI, I believe our Python load testing infrastructure is also affected with the new error codes. If I understand correctly, after https://github.com/near/nearcore/pull/11806 we started returning code 500 instead of 200 for queries about account existence, e.g:

```json
{
  "jsonrpc": "2.0",
  "id": "dontcare",
  "method": "query",
  "params": {
    "request_type": "view_account",
    "finality": "final",
    "account_id": "ft_0.node0"
  }
}
```

Our [Python code](https://github.com/near/nearcore/blob/f29029ae27e3b53a009f46185a66048125bf73a5/pytest/lib/cluster.py#L331) for checking accounts was relying on this RPC returning 200 and now started throwing exceptions [here](https://github.com/near/nearcore/blob/f29029ae27e3b53a009f46185a66048125bf73a5/pytest/lib/cluster.py#L263):

```python
[2024-07-23 13:27:46,687] spire/ERROR/root: Uncaught exception in event handler:
Traceback (most recent call last):
  File "/home/akashin/.pyenv/versions/3.11.9/envs/near-3.11/lib/python3.11/site-packages/locust/event.py", line 47, in fire
    handler(**kwargs)
  File "/home/akashin/repos/work/nearcore/pytest/tests/loadtest/locust/common/ft.py", line 235, in on_locust_init
    ft_contract.install(node, funding_account)
  File "/home/akashin/repos/work/nearcore/pytest/tests/loadtest/locust/common/ft.py", line 33, in install
    existed = node.prepare_account(self.account, parent,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akashin/repos/work/nearcore/pytest/tests/loadtest/locust/common/base.py", line 452, in prepare_account
    exists = self.account_exists(account.key.account_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akashin/repos/work/nearcore/pytest/tests/loadtest/locust/common/base.py", line 445, in account_exists
    return "error" not in self.node.get_account(account_id, do_assert=False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akashin/repos/work/nearcore/pytest/lib/cluster.py", line 346, in get_account
    res = self.json_rpc('query', query, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akashin/repos/work/nearcore/pytest/lib/cluster.py", line 263, in json_rpc
    r.raise_for_status()
  File "/home/akashin/.pyenv/versions/3.11.9/envs/near-3.11/lib/python3.11/site-packages/geventhttpclient/requests.py", line 43, in raise_for_status
    raise useragent.BadStatusCode(self.url, code=self.status_code)
geventhttpclient.useragent.BadStatusCode: URL http://127.0.0.1:3030: code=500
```

It's possible to fix the error handling in Python, but I suspect it will be a non-trivial amount of work as we will need to review each user of `json_rpc` method.
Given the other comment from @tayfunelmas , this likely affects more clients, hence I'm wondering if changing the error code here brings more benefits than harm?

**Comment by frolvanya** [comment]
Since now throwing bad status codes can be considered as a normal operation, I think that we can remove `.raise_for_status()` completely or write a new utility that would allow only 200, 400, 408 and 500 status codes. However, this fix feels odd. @akashin What is your opinion on that?

> hence I'm wondering if changing the error code here brings more benefits than harm?

I believe that if we will find a way to fix all tests with little to no effort, then it's worth it

**Comment by frolvanya** [comment]
> FYI, I believe our Python load testing infrastructure is also affected with the new error codes. If I understand correctly, after #11806 we started returning code 500 instead of 200 for queries about account existence, e.g:

And this was a bad way to do it. In this PR we return 200 for errors like "unknown account"
The only `handler` error that return non-200 status code is a TIMEOUT_ERROR

**Comment by akashin** [comment]
> > FYI, I believe our Python load testing infrastructure is also affected with the new error codes. If I understand correctly, after #11806 we started returning code 500 instead of 200 for queries about account existence, e.g:
> 
> And this was a bad way to do it. In this PR we return 200 for errors like "unknown account" The only `handler` error that return non-200 status code is a TIMEOUT_ERROR

Sounds good, in this case I'll wait for this PR to land and then work to fix any other problems that pop up in our Python libraries.

**Review by khorolets — APPROVED** [review]
LGTM! Thanks!

**Review by tayfunelmas — APPROVED** [review]

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 2!
You have received 20 Sloth points for this contribution

**Pull request merged**
