### PR TITLE
[ft-benchmark] add signal from .sh to .py script

### PR DESCRIPTION
**Pull request by MCJOHN974**
With this changes `ft-benchmark.sh` will send `SIGTERM` to all live instances of `ft-benchmark-data-sender.py` and `ft-benchmark-data-sender` will send collected data to db and finish correctly.

### CODE REVIEW

**Comment by MCJOHN974** [comment]
I think this protobuf backward compatibility wasn't triggered by my changes and we can ignore them until we will merge to master

**Review by akashin — APPROVED** [review]
LGTM, but let's keep discussing the base PR

**Comment by MCJOHN974** [comment]
@akashin do you think it is still actual and we should merge it? If we plan to run benchmark once a day for a couple of hours we don't really need this I think

**Comment by akashin** [comment]
> @akashin do you think it is still actual and we should merge it? If we plan to run benchmark once a day for a couple of hours we don't really need this I think

We will have 2 use-cases:
1. Automated runs once a day
2. Manual one-off runs at a specified commit by engineers evaluating performance of their change

Do you think this is needed for 2?

**Comment by akashin** [comment]
> > > @akashin do you think it is still actual and we should merge it? If we plan to run benchmark once a day for a couple of hours we don't really need this I think
> > 
> > 
> > We will have 2 use-cases:
> > 
> > 1. Automated runs once a day
> > 2. Manual one-off runs at a specified commit by engineers evaluating performance of their change
> > 
> > Do you think this is needed for 2?
> 
> I think we will need some mechanism for cases when manual runs intersect with scheduled run or between themselves. But for such case "just shutdown previous run and send data which already collected" probably will be not best strategy. I don't want occasionally stop your experiment after 5 minutes run.
> 
> Simply creating new node & locust instances will be best option but will require some terraform magic, because it is probably impossible within one machine.
> 
> Probably good balance will be to "add to running queue" your run, once you triggered it.

I don't think we should ever have multiple benchmarks running on a single machine - so I don't think we need to actively design the code to work in these cases. It should be reasonable to expect that the person who runs the benchmark follow this rule.

**Comment by MCJOHN974** [comment]
> > > > @akashin do you think it is still actual and we should merge it? If we plan to run benchmark once a day for a couple of hours we don't really need this I think
> > > 
> > > 
> > > We will have 2 use-cases:
> > > 
> > > 1. Automated runs once a day
> > > 2. Manual one-off runs at a specified commit by engineers evaluating performance of their change
> > > 
> > > Do you think this is needed for 2?
> > 
> > 
> > I think we will need some mechanism for cases when manual runs intersect with scheduled run or between themselves. But for such case "just shutdown previous run and send data which already collected" probably will be not best strategy. I don't want occasionally stop your experiment after 5 minutes run.
> > Simply creating new node & locust instances will be best option but will require some terraform magic, because it is probably impossible within one machine.
> > Probably good balance will be to "add to running queue" your run, once you triggered it.
> 
> I don't think we should ever have multiple benchmarks running on a single machine - so I don't think we need to actively design the code to work in these cases. It should be reasonable to expect that the person who runs the benchmark follow this rule.

Than should we procceed with "running queue" option?

**Comment by akashin** [comment]
> > > > > @akashin do you think it is still actual and we should merge it? If we plan to run benchmark once a day for a couple of hours we don't really need this I think
> > > > 
> > > > 
> > > > We will have 2 use-cases:
> > > > 
> > > > 1. Automated runs once a day
> > > > 2. Manual one-off runs at a specified commit by engineers evaluating performance of their change
> > > > 
> > > > Do you think this is needed for 2?
> > > 
> > > 
> > > I think we will need some mechanism for cases when manual runs intersect with scheduled run or between themselves. But for such case "just shutdown previous run and send data which already collected" probably will be not best strategy. I don't want occasionally stop your experiment after 5 minutes run.
> > > Simply creating new node & locust instances will be best option but will require some terraform magic, because it is probably impossible within one machine.
> > > Probably good balance will be to "add to running queue" your run, once you triggered it.
> > 
> > 
> > I don't think we should ever have multiple benchmarks running on a single machine - so I don't think we need to actively design the code to work in these cases. It should be reasonable to expect that the person who runs the benchmark follow this rule.
> 
> Than should we procceed with "running queue" option?

I think let's just raise an error if there is already a benchmark running. Then the user can do the queuing externally if needed.

**Comment by MCJOHN974** [comment]
Closing because we changed strategy for cases overlapping runs

**Pull request closed without merging**
