### PR TITLE
build fuzzers on each commit

### PR DESCRIPTION
**Pull request by Ekleog-NEAR**
One of the last three remaining steps to close the issue https://github.com/near/nayduck/issues/37

### CODE REVIEW

**Review by andrei-near — APPROVED** [review]

**Comment by Ekleog-NEAR** [comment]
Hmm does buildkite have something equivalent to ondemand github actions, like what we do in https://github.com/near/nearcore/blob/master/.github/workflows/ondemand_fuzzer_binaries.yml ? If not, even though we could make commit-by-commit builds into buildkite, for consistency with the ondemand builds upon release I think it still makes sense to have this on github actions.

Anyway, landing for now, we can add this further improvement as a missing task on https://github.com/near/nayduck/issues/37 to not miss it :)

**Comment by Ekleog-NEAR** [comment]
Oh, right, we need a codeowner review too. @nagisa ? :)

**Review by nagisa — APPROVED** [review]

**Comment by nagisa** [comment]
This ain't making anything worse, so LGTM.

**Comment by Ekleog-NEAR** [comment]
@near-bulldozer You there?

**Pull request merged**
