### PR TITLE
Create node_team_issue.md

### PR DESCRIPTION
**Pull request by gmilescu**
Create an issue template for the Node team, that will automatically assign a "Node" label to the issue being created and will map the issue to "Node Team Project"

### CODE REVIEW

**Review by nikurt — APPROVED** [review]
Looks good.
Should the description explain which types of issues are appropriate for the Node team?

**Comment by nagisa** [comment]
I would argue that people external to the project aren’t necessarily expected to know for which team a specific issue is appropriate. On the other hand, people part of this project should already have permissions to apply labels and likely should be applying more than just the Node label for most issues they file anyway, so they’ll have to interact with that part of the UI anyway, so this does not actually simplify the workflow much for them.

(Not that I’m objecting to landing this, just that I’m trying to figure out the underlying motivation behind this change)

**Comment by gmilescu** [comment]
@nagisa Applying a label and associating a project is the most frequent repetitive operation I do with Github issues, at leat for Node. I know that the templates are not relevant for people in the community, and they will likely use a black tempalte instead.

Do you believe this template might create confusion?

**Comment by nagisa** [comment]
Perhaps less likely to cause confusion than just have to make read through and pick out from one more option when filing an issue against nearcore, so it is just moving the repetition from one place to another. No big deal either way.

That said, I did not notice this template is assigning both a project and a label. I can see how this chore could get old really fast :)

I wonder if [a GHA workflow that modifies team labels](https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues) based on the projects, or perhaps vice-versa, would work? That way the chore would be improved to just one repetitive step as well, while at the same time being potentially easily extensible to other teams and workflows too.

**Comment by gmilescu** [comment]
I'm looking into the GHA workflow option, and will come back in a few days with a clear picture about how much it helps.

**Pull request closed without merging**
