### PR TITLE
Revert "Versioning for ValidatorStake"

### PR DESCRIPTION
**Pull request by chefsale**
Reverts near/nearcore#4115

Betanet paniced with:
```
thread 'main' panicked at 'Failed to start Epoch Manager: IOErr(Unexpected length of input)', neard/src/runtime/mod.rs:213:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::expect
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/result.rs:933
   4: neard::runtime::NightshadeRuntime::new
             at /var/lib/buildkite-agent/builds/buildkite-i-061b8629bdbc51511-1/nearprotocol/nearcore-nightly-release/neard/src/runtime/mod.rs:192
   5: neard::start_with_config
             at /var/lib/buildkite-agent/builds/buildkite-i-061b8629bdbc51511-1/nearprotocol/nearcore-nightly-release/neard/src/lib.rs:240
   6: neard::main::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-i-061b8629bdbc51511-1/nearprotocol/nearcore-nightly-release/neard/src/main.rs:247
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79
   8: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:634
   9: tokio::coop::with_budget::{{closure}}
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:121
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:265
  11: std::thread::local::LocalKey<T>::with
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:241
  12: tokio::coop::with_budget
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:114
  13: tokio::coop::budget
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:98
  14: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:634
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/macros/scoped_tls.rs:61
  16: tokio::task::local::LocalSet::with
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:548
  17: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:624
  18: tokio::task::local::LocalSet::run_until::{{closure}}
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:498
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/future.rs:121
  21: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:184
  22: tokio::coop::with_budget::{{closure}}
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:121
  23: std::thread::local::LocalKey<T>::try_with
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:265
  24: std::thread::local::LocalKey<T>::with
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:241
  25: tokio::coop::with_budget
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:114
  26: tokio::coop::budget
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:98
  27: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:184
  28: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:266
  29: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/macros/scoped_tls.rs:61
  30: tokio::runtime::basic_scheduler::enter
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:266
  31: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:176
  32: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:405
  33: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:136
  34: tokio::runtime::Runtime::block_on
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/mod.rs:450
  35: tokio::task::local::LocalSet::block_on
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:459
  36: actix_rt::runtime::Runtime::block_on
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.1.0/src/runtime.rs:85
  37: actix_rt::system::SystemRunner::block_on
             at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.1.0/src/system.rs:186
  38: neard::main
             at /var/lib/buildkite-agent/builds/buildkite-i-061b8629bdbc51511-1/nearprotocol/nearcore-nightly-release/neard/src/main.rs:246
  39: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2021-03-30 14:37:31.178 ERROR tailer - show_logs: Unable to read logs. Please try again.
```

### CODE REVIEW

**Review by birchmd — APPROVED** [review]
Is betanet run with nightly features?

**Comment by chefsale** [comment]
Yes, betanet is running nightly. I assume I can go ahead and revert? @birchmd

**Comment by birchmd** [comment]
Yes, fine to revert.

I was just thinking about why it failed and how I could reproduce for myself so I can submit a revised PR. `IOErr(Unexpected length of input)` looks like a borsh serialization error.

**Comment by chefsale** [comment]
I think you can just build the binary with nightly and connect to betanet. It should be able to reproduce the error, as all the betanet nodes died at the same time.

**Comment by chefsale** [comment]
If you need help with reproducing it, happy to help.

**Pull request merged**
