### PR TITLE
re: Fix Clion false error in `near_network.rs`

### PR DESCRIPTION
**Pull request by pmnoxx**
Clion Rust plugin for Intellij gives a false error. Let's fix it. Maybe we should inform the rust clion plugin team?

```
mismatches types [E308]
expected `&HandshakeAutoDes`, for `&mut &[u8]`.
```

This issue is not too important to fix. I reported the issue to `intelij-rust`, and this PR can be helpful in fixing the issue in the plugin.

### CODE REVIEW

**Review by mm-near — APPROVED** [review]

**Review by matklad — APPROVED** [review]
LGTM!

Couple of unrelated notes:

* `oldest_supported_version: version,` feels buggy, it should be `oldest_supported_version: PEER_MIN_ALLOWED_PROTOCOL_VERSION` perhaps?
* `HandshakeAutoDes` and its fields should not be `pub(crate)`
* `HandshakeAutoDes` fields should be named exactly as `Handshake` fields
* in https://github.com/near/nearcore/blob/518685af6a67838e27bf727fd2a677830133f7ad/chain/network/src/peer/peer_actor.rs#L233 `39` feels suspect. Should that be `PEER_MIN_ALLOWED_PROTOCOL_VERSION`
* `PEER_MIN_ALLOWED_PROTOCOL_VERSION <= version && version <= PROTOCOL_VERSION` feels a bit odd as it is asymmetric (`a` can connect to `b` but not `b` to `a`). Might make sense to leave a brief comment explaining how that works

**Comment by matklad** [comment]
> Maybe we should inform the rust clion plugin team?

Yes, please open an issue at https://github.com/intellij-rust/intellij-rust

**Comment by pmnoxx** [comment]
> * `oldest_supported_version: version,` feels buggy, it should be `oldest_supported_version: PEER_MIN_ALLOWED_PROTOCOL_VERSION` perhaps?

This is the `PEER_MIN_ALLOWED_PROTOCOL_VERSION` from the other peer. We want to know the state of this constant from the other peer.

**Comment by pmnoxx** [comment]
@matklad I fixed the inconsistency issue in https://github.com/near/nearcore/pull/6107

**Pull request merged**
