### PR TITLE
[Snyk] Upgrade @types/react from 18.0.25 to 18.2.25

### PR DESCRIPTION
**Pull request by ecp88**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade @types/react from 18.0.25 to 18.2.25.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **39 versions** ahead of your current version.
- The recommended version was released **22 days ago**, on 2023-10-04.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>@types/react</b></summary>
    <ul>
      <li>
        <b>18.2.25</b> - 2023-10-04
      </li>
      <li>
        <b>18.2.24</b> - 2023-10-01
      </li>
      <li>
        <b>18.2.23</b> - 2023-09-26
      </li>
      <li>
        <b>18.2.22</b> - 2023-09-18
      </li>
      <li>
        <b>18.2.21</b> - 2023-08-22
      </li>
      <li>
        <b>18.2.20</b> - 2023-08-09
      </li>
      <li>
        <b>18.2.19</b> - 2023-08-08
      </li>
      <li>
        <b>18.2.18</b> - 2023-07-31
      </li>
      <li>
        <b>18.2.17</b> - 2023-07-26
      </li>
      <li>
        <b>18.2.16</b> - 2023-07-24
      </li>
      <li>
        <b>18.2.15</b> - 2023-07-13
      </li>
      <li>
        <b>18.2.14</b> - 2023-06-23
      </li>
      <li>
        <b>18.2.13</b> - 2023-06-19
      </li>
      <li>
        <b>18.2.12</b> - 2023-06-12
      </li>
      <li>
        <b>18.2.11</b> - 2023-06-10
      </li>
      <li>
        <b>18.2.10</b> - 2023-06-10
      </li>
      <li>
        <b>18.2.9</b> - 2023-06-07
      </li>
      <li>
        <b>18.2.8</b> - 2023-06-01
      </li>
      <li>
        <b>18.2.7</b> - 2023-05-24
      </li>
      <li>
        <b>18.2.6</b> - 2023-05-06
      </li>
      <li>
        <b>18.2.5</b> - 2023-05-04
      </li>
      <li>
        <b>18.2.4</b> - 2023-05-04
      </li>
      <li>
        <b>18.2.3</b> - 2023-05-04
      </li>
      <li>
        <b>18.2.2</b> - 2023-05-03
      </li>
      <li>
        <b>18.2.1</b> - 2023-05-03
      </li>
      <li>
        <b>18.2.0</b> - 2023-04-25
      </li>
      <li>
        <b>18.0.38</b> - 2023-04-21
      </li>
      <li>
        <b>18.0.37</b> - 2023-04-17
      </li>
      <li>
        <b>18.0.36</b> - 2023-04-17
      </li>
      <li>
        <b>18.0.35</b> - 2023-04-12
      </li>
      <li>
        <b>18.0.34</b> - 2023-04-10
      </li>
      <li>
        <b>18.0.33</b> - 2023-04-03
      </li>
      <li>
        <b>18.0.32</b> - 2023-04-02
      </li>
      <li>
        <b>18.0.31</b> - 2023-03-28
      </li>
      <li>
        <b>18.0.30</b> - 2023-03-27
      </li>
      <li>
        <b>18.0.29</b> - 2023-03-24
      </li>
      <li>
        <b>18.0.28</b> - 2023-02-11
      </li>
      <li>
        <b>18.0.27</b> - 2023-01-18
      </li>
      <li>
        <b>18.0.26</b> - 2022-12-02
      </li>
      <li>
        <b>18.0.25</b> - 2022-11-04
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/DefinitelyTyped/DefinitelyTyped/releases">@types/react GitHub release notes</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/ecp88/project/98480bdc-d80b-4fd1-89d7-c4c56a706763?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/ecp88/project/98480bdc-d80b-4fd1-89d7-c4c56a706763/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/ecp88/project/98480bdc-d80b-4fd1-89d7-c4c56a706763/settings/integration?pkg&#x3D;@types/react&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by nagisa** [comment]
These would be much more useful with a link to a differential like dependabot has. Q: why are we using this bot over dependabot?

**Comment by Ekleog-NEAR** [comment]
It came with [snyk](https://snyk.io), which security team is experimenting with and also has code analysis capabilities. (It does seem to be somewhat stronger than what I’d expect from a linter for python code)

Considering it doesn’t have rust support and I’m not sure when if ever they plan on going with it I’m not sure whether we’ll keep using it past the planned evaluation end time ~1-2 weeks ahead, but in the meantime I guess it’s a reasonable-ish alternative to dependabot :)

Also, with eg. https://github.com/near/nearcore/pull/10007, it did seem to have clearer vulnerability explanation than I’ve seen with dependabot yet.

**Review by Ekleog-NEAR — APPROVED** [review]

**Comment by akhi3030** [comment]
@Ekleog-NEAR: I do find it a bit creepy that this bot is using the identity of a real user instead to create the PRs.  Does it just pick a user at random?  Can we not have a user for the bot?

**Comment by Ekleog-NEAR** [comment]
We’ve discussed this with snyk as soon as we saw this; it’s based on a miscommunication between pagoda and them; should be fixed as soon as they reconfigure the system :)

**Comment by akhi3030** [comment]
Great, thanks for the explanaion!

**Pull request merged**
