### PR TITLE
Add metrics which show size of individual trie columns in the recorded storage proof

### PR DESCRIPTION
**Pull request by jancionear**
Fixes [#11537](https://github.com/near/nearcore/issues/11537)

The new metric allows to see how much of the recorded storage proof belongs to each trie column.

Here's an example visualisation on a localnet node with ft.py workload at ~500 TPS:

image

Refs [zulip discussion](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/Large.20number.20of.20delayed.20receipts.20in.20statelessnet/near/443831650)

### CODE REVIEW

**Comment by jancionear** [comment]
I was worried that collecting the column sizes can take a long time, but I see that it takes under 0.5ms under heavy load, so it should be fine.

**Review by Longarithm — CHANGES_REQUESTED** [review]
That's nice, but I think you can reuse existing `MemTrieIterator::seek_prefix` logic, or `seek_nibble_slice`, something like that. If it's not clear what it does - then we should make trie iterator API more understandable :)

Also, we should be able to reuse `memory_usage` field. It is just an approximation, but should be good enough for our needs.

**Comment by walnut-the-cat** [comment]
@bowenwang1996 , if there are other information you would like to know, feel free to share here :)

**Comment by bowenwang1996** [comment]
@jancionear I also want to see the breakdown between key values and intermediate trie nodes

**Comment by jancionear** [comment]
> @jancionear I also want to see the breakdown between key values and intermediate trie nodes

Can do :+1:

I'll go back to this PR after I'm done with the new gas costs. It doesn't have to be done before release, we can also deploy it later on a canary node to get the metrics.

**Comment by bowenwang1996** [comment]
@jancionear any updates on this?

**Comment by jancionear** [comment]
> @jancionear any updates on this?

No, I was busy with the traffic generation program. I'll update the PR this week.
I deprioritized this PR a bit because we can always deploy this branch on one RPC node to get some metrics.

**Comment by jancionear** [comment]
> That's nice, but I think you can reuse existing `MemTrieIterator::seek_prefix` logic, or `seek_nibble_slice`, something like that. If it's not clear what it does - then we should make trie iterator API more understandable :)

I tried to reuse the iterator logic, but it's hard to do it.
I could create a `DiskTrieIterator`, but for that I need a `Trie`. I can create a `Trie` from the recorded data, but that'd require copying all the data, which is slow. I could implement `TrieStorage` for the recorded data and pass it to `Trie::new`, but it expects `Arc<dyn TrieStorage>`, so I can't pass a reference there. I could try to move the data out of the `TrieRecorder` into an `Arc`, use it in an Iterator and then move it back, but it's hacky and requires the function to be `&mut self`.

Do you see a good way of reusing the existing Trie code? Everything I try feels really hacky, to the point where I prefer duplicating the code.

> Also, we should be able to reuse `memory_usage` field. It is just an approximation, but should be good enough for our needs.

`Arc<[u8]>` has a `.len()` method which is really cheap, we don't need to use `RawTrieNodeWithSize::memory_usage`

**Review by Longarithm — APPROVED** [review]
Discussed offline - we don't currently support full iteration over trie with skips anywhere else. And we need them, because recorded storage obviously doesn't cover the whole tree.

**Comment by jancionear** [comment]
We'll merge the PR as is. Reusing the code requires a lot of additional complexity, to the point where it doesn't feel worth it. I feel like having simpler code is worth it, even if we have to duplicate a 50-line function.

> @jancionear I also want to see the breakdown between key values and intermediate trie nodes

I'll add that in a follow-up PR.

**Pull request merged**
