### PR TITLE
refactor: keep bench and release profile in sync to avoid surprises

### PR DESCRIPTION
**Pull request by matklad**
Cargo's smaller profiles, like `test` and `bench`, work in a rather
curious fashion. When you run `cargo test`, `cargo test --release` or
`cargo bench`, the tset/bench profiles apply only to a subset of code
being compiled. Most things are compiled with dev/release profile
instead.

To avoid surprises where things compile differently, it's advisable to
keep bench in sync with release.

cc https://github.com/near/nearcore/pull/4507

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
@matklad but we do want lto to be enabled. The fact that it is not enabled by default was because we did not want to increase compilation time during development. In production it should be enabled through an environment variable

**Comment by matklad** [comment]
Exactly: `cargo test --release` / `cargo build --release` is something you do during development, I don't think we use `bench` profile in production? 

https://github.com/near/nearcore/issues/4678 is an example of a problem which is caused by the mismatch.

**Comment by matklad** [comment]
Interesting bits of profile triva:

* the `cogen-units = 1` option in the `bench` profile doesn't actually affect most of the code, only the test crate itself (so, bench profile doesn't actually match production profile).
* the `lto` does get enabled globally (surprised to me, to be honest: I'd expected lto in bench to be a no-op without LTO in the release profile as well)

**Comment by mina86** [comment]
LTO would be kinda useless if it didn’t enable it transitively through all dependencies.

#4678 is about params estimator which wouldn’t be affected by the `bench` profile, no? I don’t see how this commit solves the cited issue.

**Comment by matklad** [comment]
>LTO would be kinda useless if it didn’t enable it transitively through all dependencies.

That's more or less true for every other thing which is controlled by profile: it is not too useful to compile the tests themselves with codegen-units=1, and yet compile everything else with default value. Yet this is exactly how bench/test profiles work, they don't affect dependencies. This is not a useful behavior: bench&test profiles are a design mistake in cargo, which can't be removed due to backwrads compatibility sadly :(

The difference for LTO is that it simply *can't* be enabled for subset of the crates. I originally thought that Cargo only ltos if all involved profile tell it to lto, but apparently it's not the case. For example, if you specify lto in release, then `cargo test --release` won't lto. 

> I don’t see how this commit solves / affects the cited issue.

the problem there is that we try to run the same code in the estimator (via `cargo run`) and in an isolated fashion (ve `cargo test`), and get different results. That is confusing. That is, the problem is not that something is broken, but that, when you start investigating things, you get confused because behavior of `--release` cargo flag differs between `cargo test` and `cargo run`

**Comment by matklad** [comment]
`cargo test --release` uses `bench`, and that's what used in #4678

**Comment by mina86** [comment]
My only worry here is that benchmarks should probably run code which is close to production code. Maybe instead we should add `lto = true` to runtime-params-estimator instead? Either way it looks sensible to me.

**Review by bowenwang1996 — APPROVED** [review]

**Comment by matklad** [comment]
>Maybe instead we should add lto = true to runtime-params-estimator instead?

Yeah, that's what I do separately, as a part of more general "make it easy to run the 'real' run of the estimator" -- estimatro has a bunch of toggles, lto's just one of them.

**Pull request merged**
