### PR TITLE
fix(mirror): fix a crash in the mirror traffic generator

### PR DESCRIPTION
**Pull request by marcelo-gonzalez**
In queue_block(), we lock the TxTracker struct and add some data to it related to the current block's worth of transactions we're queuing. This includes references to transactions that will be queued to the tx_block_queue passed to that function. But we actually add these to the tx_block_queue only after we release the lock on the TxTracker, so another thread that's waiting for that lock might start looking through it and trying to find the transactions whose references were added to the TxTracker in queue_block(), but before these blocks get added to the tx_block_queue. This leads to a possible crash in get_tx() if we try to look up one of these transactions:

```
thread 'actix-rt|system:0|arbiter:0' panicked at tools/mirror/src/chain_tracker.rs:366:14:
called `Result::unwrap()` on an `Err` value: 100
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: near_mirror::chain_tracker::TxTracker::get_tx
   4: near_mirror::chain_tracker::TxTracker::try_set_nonces
```

We can fix it by keeping the lock on the TxTracker until after we queue this new batch of transactions onto the tx_block_queue. This is a more involved change than it would seem, because we can't hold the lock across await points, and so we need to add some logic to do the async operations before we take the lock. In the end we get logic here that is closer to what it looked like before https://github.com/near/nearcore/pull/11916. In the future it would make things simpler to move the tx_block_queue back into the TxTracker, but for now this should work

### CODE REVIEW

**Comment by VanBarbascu** [comment]
Did you get a chance to test this on the forknet?

**Comment by VanBarbascu** [comment]
Coming back to [my previous request](https://github.com/near/nearcore/pull/11916#issuecomment-2331245947).  This change would be a lot more readable if we would have a small schema of how the data flows between the mainnet and forknet chain and how the threads arbitrate the data.

**Comment by marcelo-gonzalez** [comment]
> Did you get a chance to test this on the forknet?

Yup, I think it's quite well tested

**Comment by marcelo-gonzalez** [comment]
> Coming back to [my previous request](https://github.com/near/nearcore/pull/11916#issuecomment-2331245947). This change would be a lot more readable if we would have a small diagram of how the data flows between the mainnet and forknet chain and how the threads arbitrate the data.

Yeah indeed! I just do not have time for this at the moment but it would be nice one day

**Comment by VanBarbascu** [comment]
> > Did you get a chance to test this on the forknet?
> 
> Yup, I think it's quite well tested

Great to hear! 
Please include detailed steps and result.

**Comment by VanBarbascu** [comment]
> > Coming back to [my previous request](https://github.com/near/nearcore/pull/11916#issuecomment-2331245947). This change would be a lot more readable if we would have a small diagram of how the data flows between the mainnet and forknet chain and how the threads arbitrate the data.
> 
> Yeah indeed! I just do not have time for this at the moment but it would be nice one day

I would push back on that approach. In the long run we all suffer from lack of documentation. It is easier to do it now while it is still fresh in your mind.

**Comment by marcelo-gonzalez** [comment]
> > > Did you get a chance to test this on the forknet?
> > 
> > 
> > Yup, I think it's quite well tested
> 
> Great to hear! Please include detailed steps and result.

Basically just run it on forknet where it was crashing before, and it wont crash after leaving it running for a while. You can also try testing with `pytest/tools/mirror/offline_test.py`, although it's currently a bit broken, and you'll need this diff

```diff
diff --git a/pytest/tools/mirror/mirror_utils.py b/pytest/tools/mirror/mirror_utils.py
index 8b74468bc..5f5441184 100644
--- a/pytest/tools/mirror/mirror_utils.py
+++ b/pytest/tools/mirror/mirror_utils.py
@@ -588,11 +588,11 @@ class TrafficData:
             self.nonces[sender] += 1
 
     def check_ok(self, source_node, target_node):
+        check_num_txs(source_node, target_node)
         keys = target_node.get_access_key_list(self.keyless_account0)
         assert len(keys['result']['keys']) > 0, keys
         keys = target_node.get_access_key_list(self.keyless_account1)
         assert len(keys['result']['keys']) > 0, keys
-        check_num_txs(source_node, target_node)
 
 
 def added_keys_send_transfers(nodes, added_keys, receivers, amount, block_hash):
diff --git a/runtime/runtime/src/verifier.rs b/runtime/runtime/src/verifier.rs
index 8930b78a1..87b9c4529 100644
--- a/runtime/runtime/src/verifier.rs
+++ b/runtime/runtime/src/verifier.rs
@@ -115,11 +115,11 @@ pub fn validate_transaction(
     let transaction_size = signed_transaction.get_size();
     let max_transaction_size = config.wasm_config.limit_config.max_transaction_size;
     if transaction_size > max_transaction_size {
-        return Err(InvalidTxError::TransactionSizeExceeded {
-            size: transaction_size,
-            limit: max_transaction_size,
-        }
-        .into());
+        // return Err(InvalidTxError::TransactionSizeExceeded {
+        //     size: transaction_size,
+        //     limit: max_transaction_size,
+        // }
+        // .into());
     }
 
     validate_actions(

```

Even though it's a little broken, it still works okay and you can see that the number of transactions observed is around the same before/after this change

**Comment by marcelo-gonzalez** [comment]
> > > Coming back to [my previous request](https://github.com/near/nearcore/pull/11916#issuecomment-2331245947). This change would be a lot more readable if we would have a small diagram of how the data flows between the mainnet and forknet chain and how the threads arbitrate the data.
> > 
> > 
> > Yeah indeed! I just do not have time for this at the moment but it would be nice one day
> 
> I would push back on that approach. In the long run we all suffer from lack of documentation. It is easier to do it now while it is still fresh in your mind.

Don't have time at the moment. I think it doesn't make a ton of sense to block a strict bug fix because there are no visual diagrams. But if you insist, maybe I can get around to it in a few weeks. For now feel free to cherry pick this PR and your forknet tests should work fine

**Review by VanBarbascu — APPROVED** [review]
Writing documentation isn't just for others in the team—it's for you, too. Taking the time to document now can actually save you time in the future by reducing the need to explain how things work later on.
However, running forknet off custom branches can be a bit disorganized, and we've experienced slowdowns in the past due to divergence from the master branch.

I have also tested it on the new forknet v2 image and it works great! It ran for a good while with no issues. [Grafana](https://grafana.nearone.org/goto/k56m-FkNg?orgId=1)

Kudos for fixing this!!!

**Comment by marcelo-gonzalez** [comment]
> Writing documentation isn't just for others in the team—it's for you, too. Taking the time to document now can actually save you time in the future by reducing the need to explain how things work later on. However, running forknet off custom branches can be a bit disorganized, and we've experienced slowdowns in the past due to divergence from the master branch.
> 
> I have also tested it on the new forknet v2 image and it works great! It ran for a good while with no issues. [Grafana](https://grafana.nearone.org/goto/k56m-FkNg?orgId=1)
> 
> Kudos for fixing this!!!

yea it would be good indeed. I'll try to get to it within a few weeks!

**Pull request merged**
