### PR TITLE
feat: scaffold for dev guide

### PR DESCRIPTION
**Pull request by matklad**
First step of https://github.com/near/nearcore/issues/7670

### CODE REVIEW

**Comment by akhi3030** [comment]
Can you also provide a link to the rendered book please?  Just to make sure that the steps are working as expected.

**Comment by matklad** [comment]
It won't get rendered until this actually gets in master. I'd expect us needing at least three tries to get this right

**Review by akhi3030 — APPROVED** [review]

**Comment by matklad** [comment]
@rtsainear why this PR doesn't get merged? It seem to tick all checkboxes?

image

**Comment by matklad** [comment]
I am going to mere this manually to not block, but I'd love to see some configs/logs for our mergebot to be able to debug such issues in the future.

**Comment by matklad** [comment]
It's alive!

https://near.github.io/nearcore/

**Pull request merged**
