### PR TITLE
feat(congestion_control) - integration with state sync

### PR DESCRIPTION
**Pull request by wacban**
Implemented integration of state sync and congestion control. 

The primary issue to solve was that congestion control adds a dependency on the previous block when processing the current block. During state sync some of those blocks were not available. There are two pieces to the solution:
* When cleaning the data before starting state sync do not delete any blocks that may be needed to finalize state sync. 
  * This is tested pretty well in the `test_dump_epoch_missing_chunk_in_last_block` integration test
* When executing state sync request and wait for all of the blocks that may be needed to finalize state sync. 
  * I don't think it's tested today as it requires the full setup with actors. Looking for hints here. 

The list of blocks that are needed is as follows:
* always
  * sync hash block - (dunno why but it was done this way already)
  * prev of sync hash block - (we want post state of this block so we need to apply it) 
  * prev of prev of sync hash block - (in order to apply the block above we need it's prev block)
* if there are missing chunks
  * all blocks with height in range [min(height_included) - 1, h(prev(prev(sync_hash)]
  
@jakmeier Can you have a look at the congestion control side of things please? 
@VanBarbascu Can you have a look at the state sync side of things please? 
@pugachAG I recall there was some funkiness around the height included and if it's always set - can you remind me what that was and comment on if this can mess up this implementation?

### CODE REVIEW

**Comment by pugachAG** [comment]
> I recall there was some funkiness around the height included and if it's always set

`height_included` field is not set on chunk header when the chunk is produced and that kind of makes sense: the chunk is produced before the block, so the chunk producer doesn't know at which height the newly produced chunk will actually get included. Then block producer sets `height_included` for all new chunk headers: [source](https://github.com/near/nearcore/blob/253b2ab5eb1e06028f57f9df450d3261bda0d768/chain/client/src/client.rs#L744).
In my understanding the places when we should observe `height_included` not being set are:
- At block producer side when creating a block.
- When reading chunk from the db because chunks are distributed before the block is created. This is handled by using chunk header from the block and then setting `height_included` in [`get_chunk_clone_from_header`](https://github.com/near/nearcore/blob/48af8409f305d7e64f9951ff559979c3b3f1d21e/chain/chain/src/store/mod.rs#L114). I might have missed something, but I couldn't find any code overriding the chunk in the database after processing the block.

**Comment by VanBarbascu** [comment]
`I don't think it's tested today as it requires the full setup with actors. Looking for hints here.`
We are testing this in state sync integration tests (pytests). We do not explicitly look for those blocks.

This can be easily done in a test by running state sync, wait for it to finish, teardown all the nodes and run `view-state scan-db-column` with a given block hash 

```
./neard --unsafe-fast-startup view-state scan-db-column --column Block --from-hash Ac5gEnh1H2QcbiJMDPA1WQsuguMnC9JTZUPhR89e8JZF --to-hash Ac5gEnh1H2QcbiJMDPA1WQsuguMnC9JTZUPhR89e8JZG                                                                    
.... redacted startup logs
Ac5gEnh1H2QcbiJMDPA1WQsuguMnC9JTZUPhR89e8JZF: BlockV3(BlockV3 { header: BlockHeaderV4(BlockHeaderV4 { prev_hash: DLKuXm9pCZXcpJogGFG7n1rWQtFNkCSuxQAonWFDk69d,  
..... more block output
```


or 
```
./neard --unsafe-fast-startup view-state scan-db-column --column Block --from-hash Ac5gEnh1H2QcbiJMDPA1WQsuguMnC9JTZUPhR89e8JZF --max-keys 1
```
but make sure that the output line starts with `Ac5gEnh1H2QcbiJMDPA1WQsuguMnC9JTZUPhR89e8JZF`

**Comment by VanBarbascu** [comment]
@wacban,
1. 
```
if there are missing chunks
all blocks with height in range [min(height_included) - 1, h(prev(prev(sync_hash)]
```
Maybe I am missing something, but where are we handling the extra block for the above case?

2. Do you think that it is enough to do the implicit test of state sync without checking if the block exists? It is correct but maybe it adds more clarity in how this works if we have a test for it. 

Other than this, the logic to download the extra block looks good.

**Comment by wacban** [comment]
@VanBarbascu 
> Do you think that it is enough to do the implicit test of state sync without checking if the block exists? It is correct but maybe it adds more clarity in how this works if we have a test for it.

I am working on a nayduck test where we forcefully skip chunks for a few blocks before the epoch boundary and do state sync. I hope to get it done today. For starters here is a PR that adds adversarial controls to stop chunk production: #11247

**Review by VanBarbascu — APPROVED** [review]
Looks good!

**Pull request merged**
