### PR TITLE
client: add rustc_version to /status page

### PR DESCRIPTION
**Pull request by mina86**
Issue: https://github.com/near/nearcore/issues/5979

### CODE REVIEW

**Comment by matklad** [comment]
i'd rather write our own `build.rs` than use `rustc_version_runtime`:

* that crate doesn't seem particularly popular
* it uses semver 0.9, and semver 1.0 is a big improvement over that (dtolnay took over the maintenance and rewrote it to dtolnay's standard of quality)
* it just does a lot of extra stuff -- I don't think we want to parse rustc version, it seems best to just include the literal output of `rustc --version` (maaaybe `rustc --version --verbose`)
* it doesn't do enough of stuff -- there's no reason why this needs to use `once_cell` on top. This is a bit of static data, there shouldn't be any need for runtime initialization here.

**Comment by matklad** [comment]
Unrelated thing: we have the following bit of code: 

https://github.com/nearprotocol/nearcore/blob/34eef742285287ba384b192c4240af64dc767c4e/neard/src/main.rs#L16-L33

it seems to do conceptually the same thing. So it feels like both that (getting version of `neard` itself) and this (getting version of the compiler/standard library used to build near) should be implemented in a same, single place, and be exposed both via `RPC` and via `neard --version`. 

But overall big :+1: obviously!

**Comment by mina86** [comment]
> i'd rather write our own build.rs than use rustc_version_runtime:

I thought about that but consider that we already transitively depend on `rustc_version` (which `rustc_version_runtime` is just a run-time wrapper around).

**Comment by matklad** [comment]
The fact that it depends on `rustc_version 0.2` rather than current one `rustc_version 0.4` is sort-of red flag for me. Given how simple the actual thing we want to achieve, it seems that doing that ourselves would be less headache down the line.

**Pull request closed without merging**
