### PR TITLE
fix(migrations): Use ShardChunkV1 in migration_12_to_13

### PR DESCRIPTION
**Pull request by birchmd**
Fixes error in DB migration 12 to 13.

Test plan: applying migrations to old data.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
@frol please check if this fixes the issue 🙏

**Comment by frol** [comment]
It does not crash anymore! I am leaving it over night to ensure the completion.

**Comment by birchmd** [comment]
@frol did it complete?

**Comment by bowenwang1996** [comment]
I think it did

**Review by bowenwang1996 — APPROVED** [review]

**Comment by frol** [comment]
Yes, both 12->13 and 13->14 succeeded

**Pull request merged**
