### PR TITLE
store: increase the size of the CachedContractCode column cache

### PR DESCRIPTION
**Pull request by nagisa**
This possibly mitigates the RocksDB slowness of loading contracts from the storage after the another in-memory cache fronting RocksDB was removed in #9244. As part of the 1.35 release[^1] it turned out that this has caused a significant bimodality in chunk application times – mostly attributed to storage layer. This, we suspected, had started causing increased validator kick out numbers.

Original LRU cache fronting RocksDB stored 128 units of loaded contracts. At a rough estimate of 4MiB of machine code per contract, this comes out to 512MiB. Of course the two caches are still very different – this stores uncompressed blocks containing compiled machine code. The previous cache stored contracts loaded into memory. I'm confident that the overhead of loading the contract code into memory is not particularly notable at this point, though, so the difference is something we can live with.

[^1]: https://near.zulipchat.com/#narrow/stream/297873-pagoda.2Fnode/topic/release.201.2E36/near/379169243

### CODE REVIEW

**Review by Longarithm — COMMENTED** [review]
Did we already run experiment proving that it helps with contract loading slowness? If not, I'm not sure it should be in master already.

**Comment by nagisa** [comment]
There wasn’t one yet, indeed.

**Comment by nagisa** [comment]
So I went ahead and did some mirror mocknet runs with opentelemetry tracing in place. This has allowed me to collect precise information on the function execution durations and counts. I then randomly sampled two hour-long periods during the execution and did my best to match up the time ranges between the two runs based on the block heights.

From this we end up with two sets of duration histograms. Within these histograms on y-axis you can see the number of function executions that took x-axis time to execute. I have chosen to graph `NearVM::compile_and_load` here as that's the last function in our code that is instrumented with spans before calling out into the storage layer to load contracts.

The red-coloured graph is for 1.36 and the green one is this PR.

Screenshot 2024-01-20 at 12-41-57 Function Call Durations - nagisa - Dashboards - Grafana
Screenshot 2024-01-20 at 12-42-09 Function Call Durations - nagisa - Dashboards - Grafana
Screenshot 2024-01-20 at 12-45-47 View panel - Function Call Durations - nagisa - Dashboards - Grafana
Screenshot 2024-01-20 at 12-45-59 View panel - Function Call Durations - nagisa - Dashboards - Grafana

If you look closely you can see that the additional cache did improve the situation, but the improvement is extremely minor. In either case there's a strong evidence of bi-modal distribution which is the primary thing that I was hoping to mitigate here. Additional cache does make the function execution duration a little bit more predictable (e.g. there isn’t a pronounced spike at roughly 3ms anymore – this is probably what a cache miss costs us.)

But regardless it doesn’t seem worthwhile to land this. Or we could consider increasing the size of the cache for this column a little bit more conservatively.

**Comment by nagisa** [comment]
Ah, do note when interpreting these graphs that there was a lowpass filter of 1ms applied in order to reduce the number of the data points and to make the graphs ever-so-slightly more readable.

**Pull request closed without merging**
