### PR TITLE
[Memtrie] Do not use memtries for ViewClient.

### LINKED ISSUE #11312: [Memtrie] View client should not use memtries.
We should make sure that view clients do not use memtries to serve queries, as that would possibly cause lock contention. It doesn't make sense anyway since memtries do not have history.

### PR DESCRIPTION
**Pull request by robin-near**
Closes #11312 

@bowenwang1996 is it ok to always recreate the runtime (is it ok to have separate caches and whatever)? Or should we condition it to only do that if memtrie is enabled? I'm wary of making it too complex, as this is hard to test.

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
How difficult is it to allow using memtrie for optimistic queries (querying the latest state)? While memtrie does not have history, currently 70% of rpc traffic queries latest state. Since there is no in-place updates to trie nodes, I think it is okay to have view client concurrently access memtrie. We can also do it at a later time if it is complex to implement

**Comment by robin-near** [comment]
It's probably not difficult, but I would consider against it because it can introduce lock contention on block finalization (which happens on the ClientActor thread). Also, I doubt that rpc queries are dominated by disk latency. We might be able to save on some CPU, but even then I'm not sure the disk access part will be a dominating factor (compared to serialization/deserialization and handling the web request, etc.), especially since most requests at the latest state will probably be querying for some single piece of information (rather than like, 1000 keys).

**Comment by robin-near** [comment]
@bowenwang1996 Found a better way to fix this, and included a pytest to check that it works.

**Review by bowenwang1996 — APPROVED** [review]

**Comment by tayfunelmas** [comment]
Submitted in https://github.com/near/nearcore/pull/11562.

**Pull request closed without merging**
