### PR TITLE
store: cancel background RocksDB tasks before closing the database

### PR DESCRIPTION
**Pull request by mina86**
Per RocksDB FAQ:

> Q: Is it safe to close RocksDB while another thread is issuing read,
>    write or manual compaction requests?
> A: No.  The users of RocksDB need to make sure all functions have
>    finished before they close RocksDB.  You can speed up the waiting
>    by calling CancelAllBackgroundWork().

Better be safe than sorry so add the call before the rocksdb::DB object
is dropped.

Fixes: https://github.com/near/nearcore/issues/3266

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
@mina86 looks like the implementation is for feature `single_thread_rocksdb`, which is not enabled by default.

**Comment by mina86** [comment]
D’oh. So now it turns out we need to update rocksdb to 0.16 to get this to work.

**Comment by bowenwang1996** [comment]
> D’oh. So now it turns out we need to update rocksdb to 0.16 to get this to work.

Let's do that then

**Comment by mina86** [comment]
Yep, already in review queue: https://github.com/near/nearcore/pull/4442

**Review by bowenwang1996 — APPROVED** [review]

**Pull request merged**
