### PR TITLE
feat: WIP: Add performance/memory stats to `indexer`

### PR DESCRIPTION
**Pull request by pmnoxx**
We've been discussing about adding performance/memory stats to indexer.

Here are requires changes that need to be done to enable memory tracking.

### CODE REVIEW

**Comment by khorolets** [comment]
@pmnoxx have you checked if this is works and prints the required logs?

**Comment by khorolets** [comment]
In order to run this one:

if you don't have local data

```bash
cd tools/indexer/example
cargo run --release --home-dir ~/.near/localnet init --chain-id localnet
```

Then/if you have local data

```bash
cd tools/indexer/example
cargo run --release -- --home-dir ~/.near/locanet run
```

**Comment by pmnoxx** [comment]
> In order to run this one:
> 
> if you don't have local data
> 
> ```shell
> cd tools/indexer/example
> cargo run --release --home-dir ~/.near/localnet init --chain-id localnet
> ```
> 
> Then/if you have local data
> 
> ```shell
> cd tools/indexer/example
> cargo run --release -- --home-dir ~/.near/locanet run
> ```

```
error: Found argument '--home-dir' which wasn't expected, or isn't valid in this conte
```

**Comment by pmnoxx** [comment]
@khorolets I'll have to debug this
```
 .~/r/n/t/i/example piotr-rate-limiter-deepsize R cargo run --release  init --chain-id testnet                            
    Finished release [optimized + debuginfo] target(s) in 0.12s
     Running `/home/pmnoxx/repos/nearcore.master/target/release/indexer-example init --chain-id testnet`
thread 'main' panicked at 'Could not open genesis config file.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/pmnoxx/repos/nearcore.master/core/chain-configs/src/genesis_config.rs:301:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 .~/r/n/t/i/example piotr-rate-limiter-deepsize R cargo run --release  init --chain-id localnet
    Finished release [optimized + debuginfo] target(s) in 0.14s
     Running `/home/pmnoxx/repos/nearcore.master/target/release/indexer-example init --chain-id localnet`
thread 'main' panicked at 'Could not open genesis config file.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/pmnoxx/repos/nearcore.master/core/chain-configs/src/genesis_config.rs:301:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by pmnoxx** [comment]
@khorolets If you can let me know how to fix it. I'll update the indexer to print a help guide when genesis file is not found.

**Comment by pmnoxx** [comment]
@khorolets Something weird is happening. I tried changing `main()`, but that has no effect on `cargo -p indexer-example run --release init --chain-id localnet` Some other binary runs from some other place.

**Comment by pmnoxx** [comment]
`--` was missing
```
cargo run -p indexer-example --release -- --home-dir ~/.near/localnet init  --chain-id localnet

```

**Comment by pmnoxx** [comment]
```

ov 17 18:21:55.583  INFO indexer: Load config from /home/pmnoxx/.near/localnet...
thread 'main' panicked at 'Indexer should track at least one shard. 
Tip: You may want to update /home/pmnoxx/.near/localnet/config.json with `"tracked_shards": [0]`
            ', chain/indexer/src/lib.rs:100:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

What's the best way to do this for testnet?

**Comment by khorolets** [comment]
> What's the best way to do this for testnet?

@pmnoxx I've created an instance for you with testnet and your changes running. I've sent details to you in DM

**Comment by frol** [comment]
This turns a simple example into black magic. Let's integrate all of this into near-indexer crate under a simple feature flag, so if we want any of our partners to provide us with the performance stats, we just ask them to add `features = [ "performance_stats" ]` in their Cargo.toml.

**Comment by pmnoxx** [comment]
@khorolets What's the priority of this issue?

**Comment by bowenwang1996** [comment]
> @khorolets What's the priority of this issue?

I believe it is quite important. cc @khorolets @frol

**Comment by pmnoxx** [comment]
@khorolets Sorry, I didn't get back to doing this PR this week. I'll work on this next week.

**Comment by pmnoxx** [comment]
I'm going to rewrite `near-dump-analyzer` to `Rust`. It will be easier to mantain, and have a better api, making it easier to use for other people https://github.com/near/near-memory-tracker/issues/34.

Also, I'll improve performance, on the way, https://github.com/near/near-memory-tracker/issues/36

**Pull request closed without merging**
